// Code generated by modlock-sdkgen. DO NOT EDIT.

import * as pb from '../../proto/modlock/wasm.pb.js'
import { call } from './host.js'

/** Vector is a position or direction in the world, in game units. */
export interface Vector {
  x: number
  y: number
  z: number
}

/** Angles is a rotation in degrees. */
export interface Angles {
  pitch: number
  yaw: number
  roll: number
}

/** vector reads a wire vector, taking absent components as zero. */
function vector(value: { x?: number; y?: number; z?: number } | undefined): Vector {
  return { x: value?.x ?? 0, y: value?.y ?? 0, z: value?.z ?? 0 }
}

/** angles reads wire angles, taking absent components as zero. */
function angles(value: { pitch?: number; yaw?: number; roll?: number } | undefined): Angles {
  return { pitch: value?.pitch ?? 0, yaw: value?.yaw ?? 0, roll: value?.roll ?? 0 }
}

/** reply encodes a successful Reply holding response. */
function reply(response?: Uint8Array): Uint8Array {
  return pb.Reply.toBinary({ response })
}

/** MovementAction is a movement fact the game announced for a hero. */
export type MovementAction =
  | 'landed'
  | 'ziplineAttached'
  | 'groundDash'
  | 'slide'
  | 'bouncePad'
  | 'dashJump'
  | 'airJump'
  | 'wallJump'
  | 'airDash'
  | 'meleeStarted'
  | 'abilityExecuted'

/** movementActionNames decodes each MovementAction; an unknown value has no name. */
const movementActionNames: Partial<Record<number, MovementAction>> = {
  1: 'landed',
  2: 'ziplineAttached',
  3: 'groundDash',
  4: 'slide',
  5: 'bouncePad',
  6: 'dashJump',
  7: 'airJump',
  8: 'wallJump',
  9: 'airDash',
  10: 'meleeStarted',
  11: 'abilityExecuted',
}

/** ScreenEffect is a stock full-screen view effect. */
export type ScreenEffect =
  | 'killed'
  | 'black'
  | 'blinded'
  | 'darkness'
  | 'matchIntro'

/** screenEffectValues encodes each ScreenEffect. */
const screenEffectValues: Record<ScreenEffect, pb.ScreenEffect> = {
  killed: 0,
  black: 1,
  blinded: 2,
  darkness: 3,
  matchIntro: 4,
}

/** FieldType is how ReadField and WriteField interpret a field's storage. */
export type FieldType =
  | 'bool'
  | 'int8'
  | 'int16'
  | 'int32'
  | 'uint8'
  | 'uint16'
  | 'uint32'
  | 'int64'
  | 'uint64'
  | 'float32'
  | 'float64'
  | 'vector'
  | 'handle'
  | 'string'

/** fieldTypeValues encodes each FieldType. */
const fieldTypeValues: Record<FieldType, pb.FieldType> = {
  bool: 1,
  int8: 2,
  int16: 3,
  int32: 4,
  uint8: 5,
  uint16: 6,
  uint32: 7,
  int64: 8,
  uint64: 9,
  float32: 10,
  float64: 11,
  vector: 12,
  handle: 13,
  string: 14,
}

/** PickupKind is a kind of item players collect by walking over it. */
export type PickupKind =
  | 'urn'
  | 'movementBuff'

/** pickupKindValues encodes each PickupKind. */
const pickupKindValues: Record<PickupKind, pb.PickupKind> = {
  urn: 0,
  movementBuff: 1,
}

/** StartEvent describes the server the mod starts in. */
export interface StartEvent {
  /** args holds the arguments that follow -- on the host command line. */
  readonly args: string[]
  /**
   * checkOnly is true when the host checks the mod without starting a game;
   * every call but Log then fails.
   */
  readonly checkOnly: boolean
  /**
   * source holds an interpreted mod's entry, which the interpreter module
   * evaluates during start. It is empty for a compiled mod.
   */
  readonly source: Uint8Array
}

/** fromStartEvent decodes a StartEvent. */
function fromStartEvent(message: pb.StartEvent): StartEvent {
  return {
    args: message.args ?? [],
    checkOnly: message.checkOnly ?? false,
    source: message.source ?? new Uint8Array(),
  }
}

/** StartResult declares which events the mod consumes. */
export interface StartResult {
  /** frames asks for a Frame event every server frame. */
  frames: boolean
  /** damage asks for a damage event before each hit. */
  damage: boolean
  /** damaged asks for a damaged event after each hit. */
  damaged: boolean
}

/** FrameEvent identifies one server frame. */
export interface FrameEvent {
  /** tick is the server tick, or zero when the clock is unavailable. */
  readonly tick: bigint
  /** timeSeconds is the game clock at this frame, in seconds. */
  readonly timeSeconds: number
  /**
   * movement holds one sample per watched, live hero when this frame starts a
   * new tick, and is empty otherwise.
   */
  readonly movement: MovementSample[]
}

/** fromFrameEvent decodes a FrameEvent. */
function fromFrameEvent(message: pb.FrameEvent): FrameEvent {
  return {
    tick: message.tick ?? 0n,
    timeSeconds: message.timeSeconds ?? 0,
    movement: (message.movement ?? []).map((v) => fromMovementSample(v)),
  }
}

/**
 * MovementSample is one watched hero's movement on one tick, as the game keeps
 * it. A hero whose position, velocity or ground the game does not provide has
 * no sample; another field the game did not provide is absent or zero.
 */
export interface MovementSample {
  /** player is the hero's player slot. */
  readonly player: Player
  /** pawn is the hero's entity handle. */
  readonly pawn: number
  /** position is the hero's origin, at its feet. */
  readonly position: Vector
  /** velocity is the hero's motion in units per second. */
  readonly velocity: Vector
  /**
   * grounded is true while the hero stands on something. sliding, mantling,
   * climbing and dashing are the game's movement states.
   */
  readonly grounded: boolean
  readonly sliding: boolean
  readonly mantling: boolean
  readonly climbing: boolean
  readonly dashing: boolean
  /**
   * jumpAbility is the hero's jump ability, and wallJumps the game's count of
   * consecutive wall jumps on it.
   */
  readonly jumpAbility: number
  readonly wallJumps: number
  /**
   * mantleAbility is the hero's mantle ability, and mantleStart the game time
   * its latest mantle began.
   */
  readonly mantleAbility: number
  readonly mantleStart: number
  /**
   * wallContact is where the hero was when the jump ability last found a wall
   * to jump off; it holds still once no wall qualifies.
   */
  readonly wallContact: Vector
  /** wallNormal is the last wall touched, never cleared. */
  readonly wallNormal: Vector
  /** wallJumpNormal is the normal the latest wall jump used. */
  readonly wallJumpNormal: Vector
  /** wallJumpFacing is the game's EWallJumpFacing, zero when not on a wall. */
  readonly wallJumpFacing: number
  /**
   * ziplineTime is the game time the hero last rode a zipline; it advances on
   * every tick of a ride.
   */
  readonly ziplineTime?: number
  /** actions are the movement facts the game announced since the last tick. */
  readonly actions: MovementAction[]
  /**
   * casts are the abilities the hero cast since the last tick, one per
   * MOVEMENT_ACTION_ABILITY_EXECUTED, by entity handle as Ability.entity
   * reports it; Abilities names each one's slot.
   */
  readonly casts: number[]
  /**
   * command is the movement the hero's player commanded since the last
   * sample, absent before the game ran any of it.
   */
  readonly command?: MovementCommand
}

/** fromMovementSample decodes a MovementSample. */
function fromMovementSample(message: pb.MovementSample): MovementSample {
  return {
    player: new Player(message.player ?? 0),
    pawn: message.pawn ?? 0,
    position: vector(message.position),
    velocity: vector(message.velocity),
    grounded: message.grounded ?? false,
    sliding: message.sliding ?? false,
    mantling: message.mantling ?? false,
    climbing: message.climbing ?? false,
    dashing: message.dashing ?? false,
    jumpAbility: message.jumpAbility ?? 0,
    wallJumps: message.wallJumps ?? 0,
    mantleAbility: message.mantleAbility ?? 0,
    mantleStart: message.mantleStart ?? 0,
    wallContact: vector(message.wallContact),
    wallNormal: vector(message.wallNormal),
    wallJumpNormal: vector(message.wallJumpNormal),
    wallJumpFacing: message.wallJumpFacing ?? 0,
    ziplineTime: message.ziplineTime,
    actions: (message.actions ?? []).flatMap((v) => movementActionNames[v] ?? []),
    casts: message.casts ?? [],
    command: message.command === undefined ? undefined : fromMovementCommand(message.command),
  }
}

/**
 * MovementCommand is the movement a player commanded over one tick. The
 * server runs a player's commands as they arrive, so a tick may run several
 * or none: every press among them is kept once, and a tick that ran none
 * holds the last buttons without pressing them again.
 */
export interface MovementCommand {
  /**
   * held, changed and scroll are the game's InButtonState masks as Buttons
   * bits: the buttons down, the buttons that went down or up, and the
   * presses of scroll-wheel buttons.
   */
  held: bigint
  changed: bigint
  scroll: bigint
  /** forward, left and up are the movement axes, from -1 to 1. */
  forward: number
  left: number
  up: number
  /** grounded is true when the hero stood on something as the tick began. */
  grounded: boolean
}

/** fromMovementCommand decodes a MovementCommand. */
function fromMovementCommand(message: pb.MovementCommand): MovementCommand {
  return {
    held: message.held ?? 0n,
    changed: message.changed ?? 0n,
    scroll: message.scroll ?? 0n,
    forward: message.forward ?? 0,
    left: message.left ?? 0,
    up: message.up ?? 0,
    grounded: message.grounded ?? false,
  }
}

/**
 * CommandEvent carries one command line from a player: a chat line that
 * starts with a slash (or ".", "+" or "-"), without that prefix, or a console
 * command the server received.
 */
export interface CommandEvent {
  /** player is the player who typed the command. */
  readonly player: Player
  /** line is the complete command line, starting with the command name. */
  readonly line: string
}

/** fromCommandEvent decodes a CommandEvent. */
function fromCommandEvent(message: pb.CommandEvent): CommandEvent {
  return {
    player: new Player(message.player ?? 0),
    line: message.line ?? '',
  }
}

/** CommandResult answers whether the mod handled a command. */
export interface CommandResult {
  /**
   * claimed ends the command's dispatch; the game and later mods do not see
   * it.
   */
  claimed: boolean
}

/** WorldEvent announces a loaded world. */
export interface WorldEvent {
  /** map names the world's map. */
  readonly map: string
}

/** fromWorldEvent decodes a WorldEvent. */
function fromWorldEvent(message: pb.WorldEvent): WorldEvent {
  return {
    map: message.map ?? '',
  }
}

/** UiPressEvent reports a press on a button in a player's interface. */
export interface UiPressEvent {
  /** player is the player who pressed. */
  readonly player: Player
  /** node is the id of the pressed button. */
  readonly node: string
}

/** fromUiPressEvent decodes an UiPressEvent. */
function fromUiPressEvent(message: pb.UiPressEvent): UiPressEvent {
  return {
    player: new Player(message.player ?? 0),
    node: message.node ?? '',
  }
}

/**
 * ServiceCall calls one method of a service outside Modlock. A host that
 * embeds Modlock provides services of its own, such as a game mode's match,
 * and a mod may serve one to the host. The service and its caller agree on
 * the payload's encoding.
 */
export interface ServiceCall {
  /** service names the service, such as "arena.match". */
  readonly service: string
  /** method names the method within the service. */
  readonly method: string
  /** payload is the call's argument. */
  readonly payload: Uint8Array
}

/** fromServiceCall decodes a ServiceCall. */
function fromServiceCall(message: pb.ServiceCall): ServiceCall {
  return {
    service: message.service ?? '',
    method: message.method ?? '',
    payload: message.payload ?? new Uint8Array(),
  }
}

/** ServiceReply is a service's answer. */
export interface ServiceReply {
  /** payload is the answer. */
  payload: Uint8Array
}

/**
 * DamageEvent is one hit before the game applies it. Handles are zero when
 * the game names no such entity.
 */
export interface DamageEvent {
  /** victim is the entity taking the hit. */
  readonly victim: number
  /**
   * attacker is the entity credited with the hit. Zero makes the hit a
   * hazard, such as poison gas, which credits no one and ignores the
   * inflictor and hit group.
   */
  readonly attacker: number
  /** inflictor is what delivered the hit, such as a projectile. */
  readonly inflictor: number
  /** ability is the ability that dealt the hit. */
  readonly ability: number
  /** flags are the game's damage flags. */
  readonly flags: bigint
  /** hitGroup is the body part hit; 1 is the head and -1 means none. */
  readonly hitGroup: number
  /** amount is the hit's damage before resistances. */
  readonly amount: number
}

/** fromDamageEvent decodes a DamageEvent. */
function fromDamageEvent(message: pb.DamageEvent): DamageEvent {
  return {
    victim: message.victim ?? 0,
    attacker: message.attacker ?? 0,
    inflictor: message.inflictor ?? 0,
    ability: message.ability ?? 0,
    flags: message.flags ?? 0n,
    hitGroup: message.hitGroup ?? 0,
    amount: message.amount ?? 0,
  }
}

/**
 * DamageResult answers a DamageEvent. An empty result lets the hit through.
 */
export interface DamageResult {
  /** block cancels the hit's health loss, force, effects and procs. */
  block?: boolean
  /** amount replaces the hit's damage when present. */
  amount?: number
}

/** DamagedEvent reports one hit the game applied. */
export interface DamagedEvent {
  /** victim is the entity that took the hit. */
  readonly victim: number
  /** attacker is the entity credited with the hit, or zero for a hazard. */
  readonly attacker: number
  /** ability is the ability that dealt the hit. */
  readonly ability: number
  /** healthLost is the health the hit removed, after resistances. */
  readonly healthLost: number
  /**
   * healthBefore is the victim's health before the hit; a hit that removes
   * all of it kills.
   */
  readonly healthBefore: number
  /**
   * dealt is the hit's damage after resistances, before the victim's health
   * capped it.
   */
  readonly dealt: number
}

/** fromDamagedEvent decodes a DamagedEvent. */
function fromDamagedEvent(message: pb.DamagedEvent): DamagedEvent {
  return {
    victim: message.victim ?? 0,
    attacker: message.attacker ?? 0,
    ability: message.ability ?? 0,
    healthLost: message.healthLost ?? 0,
    healthBefore: message.healthBefore ?? 0,
    dealt: message.dealt ?? 0,
  }
}

/** InputEvent is one player's watched buttons that went down or up. */
export interface InputEvent {
  /** player is the player who pressed. */
  readonly player: Player
  /** pressed holds one bit per button that went down. */
  readonly pressed: bigint
  /** released holds one bit per button that went up. */
  readonly released: bigint
}

/** fromInputEvent decodes an InputEvent. */
function fromInputEvent(message: pb.InputEvent): InputEvent {
  return {
    player: new Player(message.player ?? 0),
    pressed: message.pressed ?? 0n,
    released: message.released ?? 0n,
  }
}

/** RestoredEvent reports how a RestoreHero ended. */
export interface RestoredEvent {
  /** player is the player whose hero was restored. */
  readonly player: Player
  /**
   * error describes why the hero does not match its target, or is empty when
   * it held the target for a second.
   */
  readonly error: string
}

/** fromRestoredEvent decodes a RestoredEvent. */
function fromRestoredEvent(message: pb.RestoredEvent): RestoredEvent {
  return {
    player: new Player(message.player ?? 0),
    error: message.error ?? '',
  }
}

/** NpcsRestoredEvent reports how a RestoreNpcs ended. */
export interface NpcsRestoredEvent {
  /**
   * error describes the unit that does not match its target, or is empty
   * when every target was found in place.
   */
  readonly error: string
}

/** fromNpcsRestoredEvent decodes a NpcsRestoredEvent. */
function fromNpcsRestoredEvent(message: pb.NpcsRestoredEvent): NpcsRestoredEvent {
  return {
    error: message.error ?? '',
  }
}

/** LaunchEvent is a watched projectile's first frame. */
export interface LaunchEvent {
  /** entity is the projectile's entity handle. */
  readonly entity: number
  /** name is the projectile's designer name. */
  readonly name: string
  /** owner is the entity that fired it, or zero. */
  readonly owner: number
  /** player is the slot of the player whose hero fired it, or -1. */
  readonly player: Player
  /** position is where the projectile is. */
  readonly position: Vector
}

/** fromLaunchEvent decodes a LaunchEvent. */
function fromLaunchEvent(message: pb.LaunchEvent): LaunchEvent {
  return {
    entity: message.entity ?? 0,
    name: message.name ?? '',
    owner: message.owner ?? 0,
    player: new Player(message.player ?? 0),
    position: vector(message.position),
  }
}

/** ImpactEvent is a watched projectile striking something. */
export interface ImpactEvent {
  /** entity is the projectile's entity handle. */
  readonly entity: number
  /** name is the projectile's designer name. */
  readonly name: string
  /** owner is the entity that fired it, or zero. */
  readonly owner: number
  /** player is the slot of the player whose hero fired it, or -1. */
  readonly player: Player
  /**
   * start and end are the projectile's movement this frame, which ended in
   * the strike.
   */
  readonly start: Vector
  readonly end: Vector
  /** position is where it struck. */
  readonly position: Vector
  /** hit is the entity struck, or zero for the world. */
  readonly hit: number
}

/** fromImpactEvent decodes an ImpactEvent. */
function fromImpactEvent(message: pb.ImpactEvent): ImpactEvent {
  return {
    entity: message.entity ?? 0,
    name: message.name ?? '',
    owner: message.owner ?? 0,
    player: new Player(message.player ?? 0),
    start: vector(message.start),
    end: vector(message.end),
    position: vector(message.position),
    hit: message.hit ?? 0,
  }
}

/** LandedEvent is one hero landing. */
export interface LandedEvent {
  /** player is the slot of the player who landed. */
  readonly player: Player
  /** on is the slot of the player landed on, or -1 for the world. */
  readonly on: number
  /** speed is the downward speed just before landing, in units per second. */
  readonly speed: number
}

/** fromLandedEvent decodes a LandedEvent. */
function fromLandedEvent(message: pb.LandedEvent): LandedEvent {
  return {
    player: new Player(message.player ?? 0),
    on: message.on ?? 0,
    speed: message.speed ?? 0,
  }
}

/** SettingChangedEvent is one player's new value of one setting. */
export interface SettingChangedEvent {
  /** player is the player's server slot. */
  readonly player: Player
  /** key names the setting. */
  readonly key: string
  /** value is the new value. */
  readonly value: string
}

/** fromSettingChangedEvent decodes a SettingChangedEvent. */
function fromSettingChangedEvent(message: pb.SettingChangedEvent): SettingChangedEvent {
  return {
    player: new Player(message.player ?? 0),
    key: message.key ?? '',
    value: message.value ?? '',
  }
}

/** PrecacheOptions names what the next world loads ahead of use. */
export interface PrecacheOptions {
  /** heroes are hero names, such as hero_wraith. */
  heroes?: readonly string[]
  /**
   * resources are model and particle paths, such as models/props/crate.vmdl.
   */
  resources?: readonly string[]
}

/** toPrecacheOptions encodes a PrecacheOptions. */
function toPrecacheOptions(value: PrecacheOptions): pb.PrecacheOptions {
  return {
    heroes: value.heroes?.slice(),
    resources: value.resources?.slice(),
  }
}

/** Connection is one occupied player slot. */
export interface Connection {
  /** player is the connection's server slot. */
  readonly player: Player
  /** steamId identifies a human's account, or is zero for a bot. */
  readonly steamId: bigint
  /** name is the player's name. */
  readonly name: string
  /** bot is true for a bot player. */
  readonly bot: boolean
  /**
   * ready is true once a human has finished joining; bots are always ready.
   */
  readonly ready: boolean
  /** generation changes each time a new connection takes the slot. */
  readonly generation: number
}

/** fromConnection decodes a Connection. */
function fromConnection(message: pb.Connection): Connection {
  return {
    player: new Player(message.player ?? 0),
    steamId: message.steamId ?? 0n,
    name: message.name ?? '',
    bot: message.bot ?? false,
    ready: message.ready ?? false,
    generation: message.generation ?? 0,
  }
}

/** Pawn is one player's hero this frame. */
export interface Pawn {
  /** entity is the hero's entity handle, which ReadField reads. */
  readonly entity: number
  /** hero identifies the hero, as SelectHero returns it. */
  readonly hero: number
  /** team is the hero's team number. */
  readonly team: number
  /** health is the hero's health; zero or less is dead. */
  readonly health: number
  /** maxHealth is the hero's networked maximum health. */
  readonly maxHealth: number
  /** position is the hero's origin, at its feet. */
  readonly position: Vector
  /** eyeAngles is where the hero aims. */
  readonly eyeAngles: Angles
  /** cameraAngles is where the player's camera looks. */
  readonly cameraAngles: Angles
  /** stamina is the hero's stamina, absent until it has spawned fully. */
  readonly stamina?: number
  /** maxStamina is the hero's maximum stamina, present with stamina. */
  readonly maxStamina?: number
  /** generation is the connection generation the hero belongs to. */
  readonly generation: number
  /** souls is the souls the player holds. */
  readonly souls: number
  /** eyePosition is where the hero's view starts, for aiming traces. */
  readonly eyePosition: Vector
  /** velocity is the hero's motion in units per second. */
  readonly velocity: Vector
  /**
   * carryingUrn is whether the hero carries the soul urn, absent when the
   * game's modifier states cannot be read.
   */
  readonly carryingUrn?: boolean
}

/** fromPawn decodes a Pawn. */
function fromPawn(message: pb.Pawn): Pawn {
  return {
    entity: message.entity ?? 0,
    hero: message.hero ?? 0,
    team: message.team ?? 0,
    health: message.health ?? 0,
    maxHealth: message.maxHealth ?? 0,
    position: vector(message.position),
    eyeAngles: angles(message.eyeAngles),
    cameraAngles: angles(message.cameraAngles),
    stamina: message.stamina,
    maxStamina: message.maxStamina,
    generation: message.generation ?? 0,
    souls: message.souls ?? 0,
    eyePosition: vector(message.eyePosition),
    velocity: vector(message.velocity),
    carryingUrn: message.carryingUrn,
  }
}

/** Ability is one ability a hero owns. */
export interface Ability {
  /** name is the ability's name, such as citadel_ability_hornet_snipe. */
  readonly name: string
  /** slot is the ability's place on the hero: 0 to 3 are the ability keys. */
  readonly slot: number
  /**
   * entity is the ability's entity handle, as DamageEvent.ability reports
   * it.
   */
  readonly entity: number
  /**
   * upgrades holds the bought tiers: bit 0 unlocks it and bits 1 to 3 are
   * its upgrades.
   */
  readonly upgrades: number
  /** charges is the charges the ability holds. */
  readonly charges: number
  /** cooldownEnd is the game time its cooldown ends, or zero without one. */
  readonly cooldownEnd: number
  /** id identifies the ability's definition, as replays record it. */
  readonly id: number
  /** state is the packed upgrade word; its high half is upgrades. */
  readonly state: number
  /** cooldownStart is the game time its cooldown began. */
  readonly cooldownStart: number
  /** rechargeStart is the game time its next charge began recovering. */
  readonly rechargeStart: number
  /**
   * rechargeEnd is the game time its next charge returns, or zero without
   * one.
   */
  readonly rechargeEnd: number
}

/** fromAbility decodes an Ability. */
function fromAbility(message: pb.Ability): Ability {
  return {
    name: message.name ?? '',
    slot: message.slot ?? 0,
    entity: message.entity ?? 0,
    upgrades: message.upgrades ?? 0,
    charges: message.charges ?? 0,
    cooldownEnd: message.cooldownEnd ?? 0,
    id: message.id ?? 0,
    state: message.state ?? 0,
    cooldownStart: message.cooldownStart ?? 0,
    rechargeStart: message.rechargeStart ?? 0,
    rechargeEnd: message.rechargeEnd ?? 0,
  }
}

/** AbilityOptions changes one ability of a player's hero. */
export interface AbilityOptions {
  /** ability is the ability's name. */
  ability: string
  /**
   * upgrades replaces the bought tiers, as ability.upgrades: 0b1111 unlocks
   * it with all three upgrades.
   */
  upgrades?: number
  /** charges replaces the charges the ability holds, keeping its timers. */
  charges?: number
  /** cooldownEnd replaces the game time its cooldown ends. */
  cooldownEnd?: number
  /** rechargeEnd replaces the game time its next charge returns. */
  rechargeEnd?: number
}

/** toAbilityOptions encodes an AbilityOptions. */
function toAbilityOptions(value: AbilityOptions): pb.AbilityOptions {
  return {
    ability: value.ability,
    upgrades: value.upgrades,
    charges: value.charges,
    cooldownEnd: value.cooldownEnd,
    rechargeEnd: value.rechargeEnd,
  }
}

/** Steering is one recorded movement command and the pose its step ends on. */
export interface Steering {
  command: MovementCommand
  /** position, velocity and grounded are the pose the step ends on. */
  position: Vector
  velocity: Vector
  grounded: boolean
  /**
   * facing is where the command looks, which aims the hero and its animation.
   */
  facing: Angles
}

/** ProjectileOptions selects the projectiles a mod watches. */
export interface ProjectileOptions {
  /** names lists designer names, such as rocket_launcher_rocket_projectile. */
  names?: readonly string[]
  /**
   * keepMomentum gives each live hero back the motion it had before a
   * watched projectile's explosion, so the mod's Impact handler sets the
   * push.
   */
  keepMomentum?: boolean
}

/** toProjectileOptions encodes a ProjectileOptions. */
function toProjectileOptions(value: ProjectileOptions): pb.ProjectileOptions {
  return {
    names: value.names?.slice(),
    keepMomentum: value.keepMomentum,
  }
}

/**
 * HeroTarget is the state RestoreHero gives one hero. Omitted parts keep the
 * hero's own.
 */
export interface HeroTarget {
  /** position is the hero's origin. */
  position: Vector
  /** facing is where the camera faces; a bot's hero faces it. */
  facing: Angles
  /**
   * fresh gives full health and stamina and readies every ability, in place
   * of health, max health, upgrade bonuses and timers. A bot's ability
   * upgrades may grow while the restore runs.
   */
  fresh?: boolean
  /** level sets the hero's level. */
  level?: number
  /**
   * health and maxHealth set the hero's health and its base maximum. Both
   * are required unless the target is fresh.
   */
  health?: number
  maxHealth?: number
  /**
   * upgradeBonuses are the three stat bonuses purchases add, as replays
   * record them.
   */
  upgradeBonuses?: readonly number[]
  /** abilities sets the hero's abilities in their slots. */
  abilities?: readonly EquipmentTarget[]
  /**
   * items lists the items that replace the hero's when replaceItems is set.
   */
  items?: readonly EquipmentTarget[]
  /**
   * replaceItems replaces every item the hero owns with items; an empty list
   * removes them.
   */
  replaceItems?: boolean
  /** timers sets the charges and cooldowns of owned abilities and items. */
  timers?: readonly TimerTarget[]
}

/** toHeroTarget encodes a HeroTarget. */
function toHeroTarget(value: HeroTarget): pb.HeroTarget {
  return {
    position: value.position,
    facing: value.facing,
    fresh: value.fresh,
    level: value.level,
    health: value.health,
    maxHealth: value.maxHealth,
    upgradeBonuses: value.upgradeBonuses?.slice(),
    abilities: value.abilities?.slice(),
    items: value.items?.slice(),
    replaceItems: value.replaceItems,
    timers: value.timers?.slice(),
  }
}

/** EquipmentTarget is one ability or item a HeroTarget gives the hero. */
export interface EquipmentTarget {
  /** id identifies the definition, as Ability.id. */
  id: number
  /**
   * slot is its place on the hero, as Ability.slot; abilities need one, and
   * an item without one goes where the game puts it.
   */
  slot?: number
  /** state is the packed upgrade word, as Ability.state. */
  state: number
}

/**
 * TimerTarget sets one owned ability's or item's charges and cooldowns.
 * Times are seconds from the moment the host writes them; an omitted start
 * and end mean no timer.
 */
export interface TimerTarget {
  /** id identifies the ability, as Ability.id. */
  id: number
  /** charges is the charges it holds. */
  charges: number
  /** cooldownStart and cooldownEnd bound its cooldown. */
  cooldownStart?: number
  cooldownEnd?: number
  /** rechargeStart and rechargeEnd bound the recovery of its next charge. */
  rechargeStart?: number
  rechargeEnd?: number
}

/** ScreenTiming is a screen effect's timing in seconds. */
export interface ScreenTiming {
  /** delay is the time before the effect starts. */
  delay?: number
  /** fadeIn is the time the effect takes to reach full strength. */
  fadeIn?: number
  /** hold is the time the effect stays at full strength. */
  hold?: number
  /** fadeOut is the time the effect takes to end. */
  fadeOut?: number
}

/**
 * FieldValue is one field's value. The host accepts any numeric case for a
 * numeric type and answers with the case its type reads as: a boolean, a
 * number for a type of 32 bits or less and a handle, an integer for a 64-bit
 * type, a vector or text.
 */
export type FieldValue = boolean | number | bigint | string | Vector

/** toFieldValue encodes a FieldValue. */
function toFieldValue(value: FieldValue): pb.FieldValue {
  return { value: typeof value === 'boolean' ? { case: 'boolean' as const, value: value } : typeof value === 'number' ? { case: 'number' as const, value: value } : typeof value === 'bigint' ? { case: 'integer' as const, value: value } : typeof value === 'string' ? { case: 'text' as const, value: value } : { case: 'vector' as const, value: value } }
}

/** fromFieldValue decodes a FieldValue, or undefined when it holds none. */
function fromFieldValue(message: pb.FieldValue | undefined): FieldValue | undefined {
  const value = message?.value
  if (value === undefined || value.case === undefined) return undefined
  switch (value.case) {
    case 'vector':
      return vector(value.value)
  }
  return value.value
}

/** ModelOptions describes a model placed in the world. */
export interface ModelOptions {
  /** resource is the model's path, which the mod precached. */
  resource: string
  /** position is the model's origin. */
  position: Vector
  /** facing is the model's rotation. */
  facing?: Angles
  /** scale multiplies the model's size; the default is 1. */
  scale?: number
  /** color tints the model as 0xRRGGBBAA. */
  color?: number
  /** glow outlines the model through walls. */
  glow?: boolean
  /**
   * solid makes heroes and traces collide with the model's physics shape,
   * scaled with the model. Without it, everything passes through.
   */
  solid?: boolean
}

/** TextOptions describes text that floats in the world. */
export interface TextOptions {
  /** text is the words to show; a newline starts a second line. */
  text: string
  /** position is the text's origin. */
  position: Vector
  /** facing is the text's rotation when it does not face the camera. */
  facing?: Angles
  /** fontSize is the text's size; the default is 100. */
  fontSize?: number
  /** color is the text's color as 0xRRGGBBAA; the default is white. */
  color?: number
  /** faceCamera turns the text toward each viewer. */
  faceCamera?: boolean
  /** scale multiplies the text's size in the world; the default is 1. */
  scale?: number
}

/** ParticleOptions describes a particle effect. */
export interface ParticleOptions {
  /**
   * resource is the particle system's path, which the mod precached, such
   * as particles/abilities/assassinate_laser_targetting.vpcf.
   */
  resource: string
  /** position is the effect's origin. */
  position: Vector
  /** facing is the effect's rotation. */
  facing?: Angles
  /** color tints the effect as 0xRRGGBBAA. */
  color?: number
  /** tintPoint is the control point the color sets. */
  tintPoint?: number
  /** point sets one control point to a position, such as a beam's far end. */
  point?: ParticlePoint
  /**
   * parent is the handle of an entity the effect follows, such as a hero's.
   */
  parent?: number
}

/** ParticlePoint places one control point of a particle effect. */
export interface ParticlePoint {
  /** index is the control point's number. */
  index: number
  /** position is the control point's value. */
  position: Vector
}

/** FogOptions describes an oriented box of tinted fog. */
export interface FogOptions {
  /** position is the box's origin. */
  position: Vector
  /** facing is the box's rotation. */
  facing?: Angles
  /** mins is the box's lower corner, relative to position. */
  mins: Vector
  /** maxs is the box's upper corner, relative to position. */
  maxs: Vector
  /** strength is the fog's density. */
  strength: number
  /** color tints the fog as 0xRRGGBBAA; alpha is ignored. */
  color: number
}

/** EntityClassName names one entity's class two ways. */
export interface EntityClassName {
  /** className is the server schema class, such as CCitadelPlayerPawn. */
  readonly className: string
  /** designerName is the name maps and spawns use, such as npc_trooper. */
  readonly designerName: string
}

/** fromEntityClassName decodes an EntityClassName. */
function fromEntityClassName(message: pb.EntityClassName): EntityClassName {
  return {
    className: message.className ?? '',
    designerName: message.designerName ?? '',
  }
}

/** BotOptions describes a bot player. */
export interface BotOptions {
  /** name is the bot's player name. */
  name: string
  /** team is the team number to join: 2 or 3. */
  team: number
  /**
   * hero names the bot's hero, such as hero_wraith, or gives its identifier
   * as Pawn.hero reports it.
   */
  hero?: string | number
  /** position is where the bot appears. */
  position?: Vector
}

/** toBotOptions encodes a BotOptions. */
function toBotOptions(value: BotOptions): pb.BotOptions {
  return {
    name: value.name,
    team: value.team,
    hero: value.hero === undefined ? undefined : typeof value.hero === 'string' ? { case: 'heroName' as const, value: value.hero } : { case: 'heroId' as const, value: value.hero },
    position: value.position,
  }
}

/** EntityOptions describes an entity to create. */
export interface EntityOptions {
  /** designerName is the entity's designer name, such as npc_trooper_boss. */
  designerName: string
  /**
   * subclass names the entity's game data entry, such as npc_boss_tier1 for
   * the lane Guardian, for an entity that reads one while spawning. An NPC
   * needs one.
   */
  subclass: string
  /** team is the entity's team number; 4 is neutral. */
  team: number
  /** position is the entity's origin. */
  position: Vector
  /** facing is where the entity faces. */
  facing?: Angles
  /**
   * keyValues are the entity's spawn key values, as a map sets them, such as
   * model or rendercolor.
   */
  keyValues?: readonly KeyValue[]
  /**
   * fields are schema fields the host writes after it creates the entity and
   * before the entity spawns. A write that fails cancels the creation.
   */
  fields?: readonly FieldWrite[]
}

/** toEntityOptions encodes an EntityOptions. */
function toEntityOptions(value: EntityOptions): pb.EntityOptions {
  return {
    designerName: value.designerName,
    subclass: value.subclass,
    team: value.team,
    position: value.position,
    facing: value.facing,
    keyValues: value.keyValues?.map((v) => toKeyValue(v)),
    fields: value.fields?.map((v) => toFieldWrite(v)),
  }
}

/** KeyValue is one spawn key value. */
export interface KeyValue {
  /** key is the key value's name, such as skin. */
  key: string
  /** value is the key value's value. */
  value: EntityValue
}

/** toKeyValue encodes a KeyValue. */
function toKeyValue(value: KeyValue): pb.KeyValue {
  return {
    key: value.key,
    value: toEntityValue(value.value),
  }
}

/**
 * EntityValue is a value a map gives an entity: a spawn key value or an
 * input's parameter. An input reads its parameter as the type it takes, such
 * as an integer for Skin or a color, as 0xRRGGBBAA, for Color, and does not
 * convert text.
 */
export type EntityValue =
  | { readonly boolean: boolean }
  | { readonly integer: number }
  | { readonly number: number }
  | { readonly text: string }
  | { readonly vector: Vector }
  | { readonly color: number }

/** toEntityValue encodes an EntityValue. */
function toEntityValue(value: EntityValue): pb.EntityValue {
  if ('boolean' in value) return { value: { case: 'boolean', value: value.boolean } }
  if ('integer' in value) return { value: { case: 'integer', value: value.integer } }
  if ('number' in value) return { value: { case: 'number', value: value.number } }
  if ('text' in value) return { value: { case: 'text', value: value.text } }
  if ('vector' in value) return { value: { case: 'vector', value: value.vector } }
  return { value: { case: 'color', value: value.color } }
}

/** NpcOptions describes a unit that is not a player, such as a trooper. */
export interface NpcOptions {
  /**
   * className is the unit's entity class, such as npc_trooper or
   * npc_trooper_boss.
   */
  className: string
  /**
   * unit names the unit's game data entry, such as trooper_melee, or is empty
   * for a unit that needs none.
   */
  unit: string
  /** team is the unit's team number; 4 is neutral. */
  team: number
  /** position is the unit's origin, at its feet. */
  position: Vector
  /** facing is where the unit faces. */
  facing?: Angles
  /** health is the unit's health; the default is the unit's own. */
  health?: number
  /** maxHealth is the unit's maximum health; the default is health. */
  maxHealth?: number
  /**
   * lane is the lane the unit walks. A unit whose class walks none, unlike a
   * trooper, refuses it.
   */
  lane?: number
  /**
   * fields are schema fields the host writes after it creates the unit and
   * before the unit spawns, such as m_iInitialTeamNum, which the game reads
   * only while spawning. A write that fails cancels the spawn.
   */
  fields?: readonly FieldWrite[]
}

/** toNpcOptions encodes a NpcOptions. */
function toNpcOptions(value: NpcOptions): pb.NpcOptions {
  return {
    className: value.className,
    unit: value.unit,
    team: value.team,
    position: value.position,
    facing: value.facing,
    health: value.health,
    maxHealth: value.maxHealth,
    lane: value.lane,
    fields: value.fields?.map((v) => toFieldWrite(v)),
  }
}

/** FieldWrite writes one schema field of an entity the host creates. */
export interface FieldWrite {
  /** className is the server class that declares the field, or a subclass. */
  className: string
  /** field is the field's schema name, such as m_iLane. */
  field: string
  /** type is how to write the field. */
  type: FieldType
  /** value is the field's value. */
  value: FieldValue
}

/** toFieldWrite encodes a FieldWrite. */
function toFieldWrite(value: FieldWrite): pb.FieldWrite {
  return {
    className: value.className,
    field: value.field,
    type: fieldTypeValues[value.type],
    value: toFieldValue(value.value),
  }
}

/** NpcState is a unit's state this frame. */
export interface NpcState {
  /** position is the unit's origin. */
  readonly position: Vector
  /** facing is where the unit faces. */
  readonly facing: Angles
  /** health is the unit's health. */
  readonly health: number
  /** maxHealth is the unit's maximum health. */
  readonly maxHealth: number
  /** team is the unit's team number. */
  readonly team: number
}

/** fromNpcState decodes a NpcState. */
function fromNpcState(message: pb.NpcState): NpcState {
  return {
    position: vector(message.position),
    facing: angles(message.facing),
    health: message.health ?? 0,
    maxHealth: message.maxHealth ?? 0,
    team: message.team ?? 0,
  }
}

/** HitOptions describes damage the mod deals. */
export interface HitOptions {
  /** victim is the entity to hurt. */
  victim: number
  /**
   * attacker is the entity credited with the hit. Without one the hit is a
   * hazard, such as poison gas, which credits no one and ignores the
   * inflictor and hit group.
   */
  attacker?: number
  /** inflictor is what delivered the hit; the default is the attacker. */
  inflictor?: number
  /** amount is the damage before resistances. */
  amount: number
  /**
   * hitGroup is the body part hit; 1 is the head. The default is the game's
   * choice.
   */
  hitGroup?: number
  /**
   * ability is the entity handle of the ability that dealt the hit, as
   * ability.entity reports it.
   */
  ability?: number
}

/**
 * TraceOptions describes a line to test against the world. Layers are bits
 * of the game's collision layers: bit 0 is solid, 2 trigger, 4 player clip,
 * 18 player and 19 NPC.
 */
export interface TraceOptions {
  /** start is where the line begins. */
  start: Vector
  /** end is where the line ends. */
  end: Vector
  /**
   * layers selects what the line can hit; the default is solid and
   * hitboxes.
   */
  layers?: bigint
  /** exclude removes things in these layers from the hits. */
  exclude?: bigint
  /** ignore lists entity handles the line passes through. */
  ignore?: readonly number[]
}

/** toTraceOptions encodes a TraceOptions. */
function toTraceOptions(value: TraceOptions): pb.TraceOptions {
  return {
    start: value.start,
    end: value.end,
    layers: value.layers,
    exclude: value.exclude,
    ignore: value.ignore?.slice(),
  }
}

/** TraceHit is where a traced line first hit something. */
export interface TraceHit {
  /** position is the hit point. */
  readonly position: Vector
  /** normal is the surface's direction at the hit point. */
  readonly normal: Vector
  /** startSolid is true when the line began inside something solid. */
  readonly startSolid: boolean
  /** entity is the entity hit, or zero for the world. */
  readonly entity: number
}

/** fromTraceHit decodes a TraceHit. */
function fromTraceHit(message: pb.TraceHit): TraceHit {
  return {
    position: vector(message.position),
    normal: vector(message.normal),
    startSolid: message.startSolid ?? false,
    entity: message.entity ?? 0,
  }
}

/**
 * NpcTarget is one unit or objective RestoreNpcs places, as replays record
 * it.
 */
export interface NpcTarget {
  /**
   * className is the unit's entity class: npc_trooper, npc_trooper_neutral,
   * npc_boss_tier2, npc_boss_tier3, npc_barrack_boss,
   * npc_base_defense_sentry, npc_super_neutral or
   * npc_neutral_sinners_sacrifice.
   */
  className: string
  /** id identifies the unit's game data entry. */
  id: number
  /** team is the unit's team number; 4 is neutral. */
  team: number
  /** position is the unit's origin, at its feet. */
  position: Vector
  /** facing is where the unit faces. */
  facing: Angles
  /** velocity is the unit's motion in units per second. */
  velocity?: Vector
  /** health and maxHealth are the unit's health. */
  health: number
  maxHealth: number
  /** lane is the lane a trooper walks; troopers need one. */
  lane?: number
}

/**
 * RiftState is the Rift objective's timing as the game holds it. Times are
 * game times in seconds, or zero when unset.
 */
export interface RiftState {
  /** scoringTeam is the team holding the Rift, or zero. */
  readonly scoringTeam: number
  readonly scoringTime: number
  readonly cashInStarted: number
  readonly giveUpTime: number
  /** nextSpawn is when the Rift next opens. */
  readonly nextSpawn: number
  readonly spawnWindow: number
}

/** fromRiftState decodes a RiftState. */
function fromRiftState(message: pb.RiftState): RiftState {
  return {
    scoringTeam: message.scoringTeam ?? 0,
    scoringTime: message.scoringTime ?? 0,
    cashInStarted: message.cashInStarted ?? 0,
    giveUpTime: message.giveUpTime ?? 0,
    nextSpawn: message.nextSpawn ?? 0,
    spawnWindow: message.spawnWindow ?? 0,
  }
}

/** Player addresses one connected player by their server slot. */
export class Player {
  /** slot identifies the player on the server. */
  readonly slot: number

  constructor(slot: number) {
    this.slot = slot
  }

  /** chat sends a server chat line to the player. */
  chat(text: string): boolean {
    return call('Chat', pb.ChatRequest.toBinary({ player: this.slot, text })) !== undefined
  }

  /**
   * centerText shows text in the middle of the player's screen until it is
   * replaced. Empty text clears it.
   */
  centerText(text: string): boolean {
    return call('CenterText', pb.CenterTextRequest.toBinary({ player: this.slot, text })) !== undefined
  }

  /** announce shows a game announcement with a title to the player. */
  announce(title: string, text: string): boolean {
    return call('Announce', pb.AnnounceRequest.toBinary({ player: this.slot, title, text })) !== undefined
  }

  /** pawn returns the player's hero this frame, or nothing without one. */
  pawn(): Pawn | undefined {
    const reply = call('Pawn', pb.PlayerRequest.toBinary({ player: this.slot }))
    if (reply === undefined) return undefined
    const response = pb.PawnResponse.fromBinary(reply)
    return response.pawn === undefined ? undefined : fromPawn(response.pawn)
  }

  /**
   * setting returns the player's value of a setting the manifest
   * declares: the value they chose, or the setting's default. A bot has the
   * defaults.
   */
  setting(key: string): string | undefined {
    const reply = call('PlayerSetting', pb.PlayerSettingRequest.toBinary({ player: this.slot, key }))
    if (reply === undefined) return undefined
    const response = pb.SettingResponse.fromBinary(reply)
    return response.value ?? ''
  }

  /**
   * setSetting changes the player's value of a setting the manifest
   * declares. The value follows the player to later games and other mods'
   * servers of the same mod; a bot keeps the defaults.
   */
  setSetting(key: string, value: string): boolean {
    return call('SetPlayerSetting', pb.SetPlayerSettingRequest.toBinary({ player: this.slot, key, value })) !== undefined
  }

  /**
   * addMetric adds to the player's total of a metric the manifest declares.
   * The host keeps each player's totals in memory and hands them on once,
   * when the player leaves or the mod stops; a bot keeps none.
   */
  addMetric(name: string, value: number, label?: string): boolean {
    return call('AddMetric', pb.AddMetricRequest.toBinary({ player: this.slot, name, value, label })) !== undefined
  }

  /**
   * selectHero gives the player a hero on a team, 2 or 3, and returns the
   * hero's identifier as Pawn.hero reports it. The hero appears on a later
   * frame.
   */
  selectHero(hero: string | number, team: number): number | undefined {
    const reply = call('SelectHero', pb.SelectHeroRequest.toBinary({ player: this.slot, hero: typeof hero === 'string' ? { case: 'heroName' as const, value: hero } : { case: 'heroId' as const, value: hero }, team }))
    if (reply === undefined) return undefined
    const response = pb.HeroResponse.fromBinary(reply)
    return response.hero ?? 0
  }

  /**
   * spectate moves the player to the spectators, without a hero. The player
   * watches until a hero selection seats them again.
   */
  spectate(): boolean {
    return call('Spectate', pb.PlayerRequest.toBinary({ player: this.slot })) !== undefined
  }

  /** respawn revives the player's dead hero. */
  respawn(): boolean {
    return call('Respawn', pb.PlayerRequest.toBinary({ player: this.slot })) !== undefined
  }

  /** clearItems removes every item the player's hero owns. */
  clearItems(): boolean {
    return call('ClearItems', pb.PlayerRequest.toBinary({ player: this.slot })) !== undefined
  }

  /**
   * freeze holds the player's hero in place, without input or damage, until
   * it is released. Stopping the mod releases it.
   */
  freeze(frozen?: boolean): boolean {
    return call('Freeze', pb.FreezeRequest.toBinary({ player: this.slot, frozen })) !== undefined
  }

  /** restoreStamina refills the player's stamina. */
  restoreStamina(): boolean {
    return call('RestoreStamina', pb.PlayerRequest.toBinary({ player: this.slot })) !== undefined
  }

  /**
   * refreshAbility ends the cooldown of the hero's ability named ability,
   * such as citadel_ability_melee_parry.
   */
  refreshAbility(ability: string): boolean {
    return call('RefreshAbility', pb.RefreshAbilityRequest.toBinary({ player: this.slot, ability })) !== undefined
  }

  /**
   * abilities lists the abilities of the player's hero in the hero's order,
   * or none without a live hero.
   */
  abilities(): Ability[] {
    const reply = call('Abilities', pb.PlayerRequest.toBinary({ player: this.slot }))
    if (reply === undefined) return []
    const response = pb.AbilitiesResponse.fromBinary(reply)
    return (response.abilities ?? []).map((v) => fromAbility(v))
  }

  /**
   * setAbility changes the upgrades, charges or timers of one of the hero's
   * abilities. An omitted option stays as it is.
   */
  setAbility(options: AbilityOptions): boolean {
    return call('SetAbility', pb.AbilityOptions.toBinary({ player: this.slot, ...toAbilityOptions(options) })) !== undefined
  }

  /**
   * giveItem gives the hero an item, enabled and free. A hero that owns it
   * keeps its one copy.
   */
  giveItem(item: string): boolean {
    return call('GiveItem', pb.GiveItemRequest.toBinary({ player: this.slot, item })) !== undefined
  }

  /**
   * replaceAbility puts the ability named ability, untrained, in the hero's
   * ability slot index, as Ability.slot, removing the ability there.
   */
  replaceAbility(index: number, ability: string): boolean {
    return call('ReplaceAbility', pb.ReplaceAbilityRequest.toBinary({ player: this.slot, index, ability })) !== undefined
  }

  /**
   * holdModifier keeps an ability's modifier, named "<ability>/<modifier>",
   * on the hero with no expiry, giving it back whenever the game removes it
   * or the hero returns. The hero must own the ability or item. Every hero
   * that gains the modifier from the same ability keeps it until the hold
   * ends. Releasing leaves the hero's current modifier until it dies.
   */
  holdModifier(modifier: string, active?: boolean): boolean {
    return call('HoldModifier', pb.HoldModifierRequest.toBinary({ player: this.slot, modifier, active })) !== undefined
  }

  /**
   * giveModifier gives the hero an ability's modifier, named
   * "<ability>/<modifier>", for seconds, as if the hero's own ability applied
   * it; a hero without that ability applies it with its first ability. The
   * game may end it sooner, as invisibility ends on a shot.
   */
  giveModifier(modifier: string, seconds: number): boolean {
    return call('GiveModifier', pb.GiveModifierRequest.toBinary({ player: this.slot, modifier, seconds })) !== undefined
  }

  /**
   * teleport moves the player's hero and turns it and the camera. With a
   * velocity it also sets the hero's motion, as a launch, and the camera
   * follows the hero.
   */
  teleport(position: Vector, facing: Angles, velocity?: Vector): boolean {
    return call('Teleport', pb.TeleportRequest.toBinary({ player: this.slot, position, facing, velocity })) !== undefined
  }

  /**
   * move carries the player's hero to a position as continuous motion,
   * as a recording plays back. Unlike Teleport it keeps the hero's animated
   * model drawn when repeated every tick, and leaves the camera alone.
   */
  move(position: Vector, facing: Angles, velocity?: Vector): boolean {
    return call('MovePlayer', pb.MovePlayerRequest.toBinary({ player: this.slot, position, facing, velocity })) !== undefined
  }

  /**
   * steer replays a recorded movement command on the player's hero, usually a
   * bot: the game runs the command's buttons and axes, so the hero crouches,
   * slides, jumps and mantles with its own animation, and the step then ends
   * on the recorded pose. The steering stays until the next Steer replaces
   * it, its presses counting once; a Steer without one releases the hero.
   */
  steer(steering?: Steering): boolean {
    return call('Steer', pb.SteerRequest.toBinary({ player: this.slot, steering })) !== undefined
  }

  /**
   * adjustSouls gives the player delta souls, or takes them when delta is
   * negative. A spend larger than the player's souls fails and spends
   * nothing. Silent skips the pickup's sound and number.
   */
  adjustSouls(delta: number, silent?: boolean): boolean {
    return call('AdjustSouls', pb.AdjustSoulsRequest.toBinary({ player: this.slot, delta, silent })) !== undefined
  }

  /** startingSouls sets the souls the player's hero spawns with. */
  startingSouls(souls: number): boolean {
    return call('StartingSouls', pb.StartingSoulsRequest.toBinary({ player: this.slot, souls })) !== undefined
  }

  /** heal restores health to the player's hero, up to its maximum. */
  heal(amount: number): boolean {
    return call('Heal', pb.HealRequest.toBinary({ player: this.slot, amount })) !== undefined
  }

  /**
   * sound plays a game sound event, such as Damage.Send.Crit, on the
   * player's hero.
   */
  sound(sound: string): boolean {
    return call('Sound', pb.SoundRequest.toBinary({ player: this.slot, sound })) !== undefined
  }

  /**
   * restoreHero gives the player's live hero target over the next few
   * seconds: the build first, then health, stamina and pose once it settles,
   * then charges and cooldowns. A Restored event reports when the result has
   * held for a second, or why it could not. A new call replaces the running
   * one.
   */
  restoreHero(target: HeroTarget): boolean {
    return call('RestoreHero', pb.RestoreHeroRequest.toBinary({ player: this.slot, target: toHeroTarget(target) })) !== undefined
  }

  /**
   * screenEffect plays a full-screen effect on the player's view. Effects of
   * one kind stack. The player's hero must be alive.
   */
  screenEffect(effect: ScreenEffect, timing?: ScreenTiming): boolean {
    return call('ScreenEffect', pb.ScreenEffectRequest.toBinary({ player: this.slot, effect: screenEffectValues[effect], timing })) !== undefined
  }

  /**
   * clearScreenEffect ends every running instance of effect on the player's
   * view.
   */
  clearScreenEffect(effect: ScreenEffect): boolean {
    return call('ClearScreenEffect', pb.ClearScreenEffectRequest.toBinary({ player: this.slot, effect: screenEffectValues[effect] })) !== undefined
  }

  /** removeBot removes a bot the mod added. */
  removeBot(): boolean {
    return call('RemoveBot', pb.PlayerRequest.toBinary({ player: this.slot })) !== undefined
  }

  /**
   * blockInput withholds buttons from the player's hero until called
   * again, on top of the block on everyone. Zero releases the player.
   */
  blockInput(buttons: bigint): boolean {
    return call('BlockPlayerInput', pb.PlayerInputRequest.toBinary({ player: this.slot, buttons })) !== undefined
  }

  /**
   * press presses buttons at the player's next input, even through a block.
   * A bot presses them as a player would.
   */
  press(buttons: bigint): boolean {
    return call('Press', pb.PlayerInputRequest.toBinary({ player: this.slot, buttons })) !== undefined
  }

  /** kill kills a player's hero, crediting no one. */
  kill(): boolean {
    return call('Kill', pb.PlayerRequest.toBinary({ player: this.slot })) !== undefined
  }

  /** setVelocity replaces the motion of a player's hero without moving it. */
  setVelocity(velocity: Vector): boolean {
    return call('SetVelocity', pb.SetVelocityRequest.toBinary({ player: this.slot, velocity })) !== undefined
  }

  /**
   * buttons returns the buttons a player holds, as Buttons bits, while the
   * player is alive or dead.
   */
  buttons(): bigint | undefined {
    const reply = call('Buttons', pb.PlayerRequest.toBinary({ player: this.slot }))
    if (reply === undefined) return undefined
    const response = pb.ButtonsResponse.fromBinary(reply)
    return response.buttons ?? 0n
  }

  /**
   * watchMovement adds a player's hero to the movement samples of each Frame
   * event on a new tick, or removes it.
   */
  watchMovement(watch: boolean): boolean {
    return call('WatchMovement', pb.WatchMovementRequest.toBinary({ player: this.slot, watch })) !== undefined
  }
}

/** WorldObject is one object the mod placed in the world. */
export class WorldObject {
  /** id identifies the object among the mod's objects. */
  readonly id: number

  constructor(id: number) {
    this.id = id
  }

  /** move places the object at position, turning it to facing. */
  move(position: Vector, facing?: Angles): boolean {
    return call('MoveObject', pb.MoveObjectRequest.toBinary({ object: this.id, position, facing })) !== undefined
  }

  /** setText replaces a text object's words. */
  setText(text: string): boolean {
    return call('SetText', pb.SetTextRequest.toBinary({ object: this.id, text })) !== undefined
  }

  /** remove takes the object out of the world. */
  remove(): boolean {
    return call('RemoveObject', pb.ObjectRequest.toBinary({ object: this.id })) !== undefined
  }

  /** entity returns the entity handle of a model, as traces report it. */
  entity(): number | undefined {
    const reply = call('ObjectEntity', pb.ObjectRequest.toBinary({ object: this.id }))
    if (reply === undefined) return undefined
    const response = pb.EntityResponse.fromBinary(reply)
    return response.entity ?? 0
  }
}

/** Npc is one unit the mod spawned. */
export class Npc {
  /** entity is the unit's entity handle, as damage events report it. */
  readonly entity: number

  constructor(entity: number) {
    this.entity = entity
  }

  /** read returns the unit's state, or nothing once it is gone. */
  read(): NpcState | undefined {
    const reply = call('ReadNpc', pb.NpcRequest.toBinary({ npc: this.entity }))
    if (reply === undefined) return undefined
    const response = pb.NpcStateResponse.fromBinary(reply)
    return response.state === undefined ? undefined : fromNpcState(response.state)
  }

  /**
   * move places the unit and sets its velocity, which drives its walk
   * animation. It reports false once the unit is gone.
   */
  move(position: Vector, facing?: Angles, velocity?: Vector): boolean {
    const reply = call('MoveNpc', pb.MoveNpcRequest.toBinary({ npc: this.entity, position, facing, velocity }))
    if (reply === undefined) return false
    const response = pb.AliveResponse.fromBinary(reply)
    return response.alive ?? false
  }

  /**
   * setHealth sets the unit's health, and its maximum when given. It
   * reports false once the unit is gone.
   */
  setHealth(health: number, maxHealth?: number): boolean {
    const reply = call('SetNpcHealth', pb.SetNpcHealthRequest.toBinary({ npc: this.entity, health, maxHealth }))
    if (reply === undefined) return false
    const response = pb.AliveResponse.fromBinary(reply)
    return response.alive ?? false
  }

  /**
   * remove takes a unit the mod spawned out of the world without rewards.
   * It reports false when the unit was already gone.
   */
  remove(): boolean {
    const reply = call('RemoveNpc', pb.NpcRequest.toBinary({ npc: this.entity }))
    if (reply === undefined) return false
    const response = pb.AliveResponse.fromBinary(reply)
    return response.alive ?? false
  }
}

/** Pickup is one pickup the mod placed. */
export class Pickup {
  /** entity is the pickup's entity handle. */
  readonly entity: number

  constructor(entity: number) {
    this.entity = entity
  }

  /**
   * present reports whether the pickup still lies in the world,
   * uncollected.
   */
  present(): boolean {
    const reply = call('PickupPresent', pb.PickupRequest.toBinary({ pickup: this.entity }))
    if (reply === undefined) return false
    const response = pb.AliveResponse.fromBinary(reply)
    return response.alive ?? false
  }

  /**
   * remove takes the pickup out of the world. It reports false when a
   * player had collected it.
   */
  remove(): boolean {
    const reply = call('RemovePickup', pb.PickupRequest.toBinary({ pickup: this.entity }))
    if (reply === undefined) return false
    const response = pb.AliveResponse.fromBinary(reply)
    return response.alive ?? false
  }
}

/** log writes one line to the server log under the mod's name. */
export function log(message: string): boolean {
  return call('Log', pb.LogRequest.toBinary({ message })) !== undefined
}

/**
 * serverCommand runs one line at the server console, as if typed there. A
 * line that sets a variable may set a development-only or cheat-protected
 * one.
 */
export function serverCommand(command: string): boolean {
  return call('ServerCommand', pb.ServerCommandRequest.toBinary({ command })) !== undefined
}

/**
 * precache loads heroes and resources with the next world. Call it during
 * start, before the first world loads.
 */
export function precache(options: PrecacheOptions): boolean {
  return call('Precache', pb.PrecacheOptions.toBinary(toPrecacheOptions(options))) !== undefined
}

/** players lists the occupied player slots in slot order. */
export function players(): Connection[] {
  const reply = call('Players', new Uint8Array())
  if (reply === undefined) return []
  const response = pb.PlayersResponse.fromBinary(reply)
  return (response.players ?? []).map((v) => fromConnection(v))
}

/**
 * readField reads one schema field of a live entity, such as the int32
 * m_iHealth of CBaseEntity. The host finds the field by name, so it
 * survives game updates that move it, and refuses an entity that is not of
 * the named class or a subclass.
 */
export function readField(entity: number, className: string, field: string, type: FieldType): FieldValue | undefined {
  const reply = call('ReadField', pb.ReadFieldRequest.toBinary({ entity, className, field, type: fieldTypeValues[type] }))
  if (reply === undefined) return undefined
  const response = pb.FieldResponse.fromBinary(reply)
  return fromFieldValue(response.value)
}

/**
 * writeField writes one schema field of a live entity and sends the change
 * to the players. The value takes the form ReadField returns for the type;
 * text fields cannot be written.
 */
export function writeField(entity: number, className: string, field: string, type: FieldType, value: FieldValue): boolean {
  return call('WriteField', pb.WriteFieldRequest.toBinary({ entity, className, field, type: fieldTypeValues[type], value: toFieldValue(value) })) !== undefined
}

/**
 * entityClass returns a live entity's schema class, such as
 * CCitadelPlayerPawn, whose fields ReadField reads, and its designer name.
 */
export function entityClass(entity: number): EntityClassName | undefined {
  const reply = call('EntityClass', pb.EntityRequest.toBinary({ entity }))
  if (reply === undefined) return undefined
  const response = pb.EntityClassResponse.fromBinary(reply)
  return response.name === undefined ? undefined : fromEntityClassName(response.name)
}

/**
 * modifierState reports whether an entity has a modifier state, such as
 * MODIFIER_STATE_PARRY_ACTIVE.
 */
export function modifierState(entity: number, state: string): boolean {
  const reply = call('ModifierState', pb.ModifierStateRequest.toBinary({ entity, state }))
  if (reply === undefined) return false
  const response = pb.ActiveResponse.fromBinary(reply)
  return response.active ?? false
}

/**
 * holdModifierState holds a modifier state, such as
 * MODIFIER_STATE_FRIENDLY_FIRE_ENABLED, on an entity while the mod runs, or
 * releases the hold. The hold ends with the entity.
 */
export function holdModifierState(entity: number, state: string, active?: boolean): boolean {
  return call('HoldModifierState', pb.HoldModifierStateRequest.toBinary({ entity, state, active })) !== undefined
}

/**
 * createModel places a model in the world, solid when the options ask.
 * The world removes it when the world ends; stopping the mod removes it
 * too.
 */
export function createModel(options: ModelOptions): WorldObject | undefined {
  const reply = call('CreateModel', pb.ModelOptions.toBinary(options))
  if (reply === undefined) return undefined
  const response = pb.ObjectResponse.fromBinary(reply)
  return new WorldObject(response.object ?? 0)
}

/** createText places text that floats in the world. */
export function createText(options: TextOptions): WorldObject | undefined {
  const reply = call('CreateText', pb.TextOptions.toBinary(options))
  if (reply === undefined) return undefined
  const response = pb.ObjectResponse.fromBinary(reply)
  return new WorldObject(response.object ?? 0)
}

/**
 * createParticle starts a particle effect. Removing the object stops it;
 * moving it moves the effect.
 */
export function createParticle(options: ParticleOptions): WorldObject | undefined {
  const reply = call('CreateParticle', pb.ParticleOptions.toBinary(options))
  if (reply === undefined) return undefined
  const response = pb.ObjectResponse.fromBinary(reply)
  return new WorldObject(response.object ?? 0)
}

/**
 * createFog fills a box with tinted fog whose density fades across the
 * box's boundary. Removing the object clears it; moving it moves the box.
 */
export function createFog(options: FogOptions): WorldObject | undefined {
  const reply = call('CreateFog', pb.FogOptions.toBinary(options))
  if (reply === undefined) return undefined
  const response = pb.ObjectResponse.fromBinary(reply)
  return new WorldObject(response.object ?? 0)
}

/**
 * addBot adds a bot player and returns it. The bot leaves when the world
 * ends or the mod stops.
 */
export function addBot(options: BotOptions): Player | undefined {
  const reply = call('AddBot', pb.BotOptions.toBinary(toBotOptions(options)))
  if (reply === undefined) return undefined
  const response = pb.BotResponse.fromBinary(reply)
  return new Player(response.player ?? 0)
}

/**
 * blockInput withholds buttons from every player's hero until called
 * again. Stopping the mod releases them.
 */
export function blockInput(buttons: bigint): boolean {
  return call('BlockInput', pb.InputRequest.toBinary({ buttons })) !== undefined
}

/**
 * watchInput replaces the buttons whose presses and releases arrive as
 * Input events. Watching does not withhold a press; block it with
 * BlockInput.
 */
export function watchInput(buttons: bigint): boolean {
  return call('WatchInput', pb.InputRequest.toBinary({ buttons })) !== undefined
}

/**
 * remapInput makes the from buttons act as the to buttons for every
 * player's hero until called again; from reads as up. With repeat, a held
 * from button uses the to ability again as soon as it is ready. A zero from
 * stops remapping, and stopping the mod does too. BlockInput applies after
 * the remap.
 */
export function remapInput(from: bigint, to: bigint, repeat?: boolean): boolean {
  return call('RemapInput', pb.RemapInputRequest.toBinary({ from, to, repeat })) !== undefined
}

/**
 * callService calls method of a service the host provides outside Modlock,
 * such as a game mode's match, and returns the service's answer. The
 * service defines the payload's encoding.
 */
export function callService(service: string, method: string, payload: Uint8Array): Uint8Array | undefined {
  const reply = call('CallService', pb.ServiceCall.toBinary({ service, method, payload }))
  if (reply === undefined) return undefined
  const response = pb.ServiceReply.fromBinary(reply)
  return response.payload ?? new Uint8Array()
}

/**
 * createEntity creates any entity the server knows by its designer name,
 * such as npc_trooper_boss or prop_dynamic, with spawn key values and fields
 * written before it spawns. The world removes it when the world ends;
 * stopping the mod removes it too. It refuses an ability, item or weapon,
 * which only a hero holds: GiveItem and ReplaceAbility give one.
 */
export function createEntity(options: EntityOptions): number | undefined {
  const reply = call('CreateEntity', pb.EntityOptions.toBinary(toEntityOptions(options)))
  if (reply === undefined) return undefined
  const response = pb.EntityResponse.fromBinary(reply)
  return response.entity ?? 0
}

/**
 * fireInput sends an input to a live entity, as a map's output would, such
 * as Skin with the integer 1. The value must have the type the input reads.
 * It reports false once the entity is gone.
 */
export function fireInput(entity: number, input: string, value?: EntityValue): boolean {
  const reply = call('FireInput', pb.FireInputRequest.toBinary({ entity, input, value: value === undefined ? undefined : toEntityValue(value) }))
  if (reply === undefined) return false
  const response = pb.AliveResponse.fromBinary(reply)
  return response.alive ?? false
}

/**
 * removeEntity takes an entity the mod created out of the world without
 * rewards. It reports false when the entity was already gone.
 */
export function removeEntity(entity: number): boolean {
  const reply = call('RemoveEntity', pb.EntityRequest.toBinary({ entity }))
  if (reply === undefined) return false
  const response = pb.AliveResponse.fromBinary(reply)
  return response.alive ?? false
}

/**
 * spawnNpc adds a unit that is not a player, such as a trooper, as
 * CreateEntity does, then sets its health and lane. It thinks from the next
 * frame. The world removes it when the world ends; stopping
 * the mod removes it too.
 */
export function spawnNpc(options: NpcOptions): Npc | undefined {
  const reply = call('SpawnNpc', pb.NpcOptions.toBinary(toNpcOptions(options)))
  if (reply === undefined) return undefined
  const response = pb.NpcResponse.fromBinary(reply)
  return new Npc(response.npc ?? 0)
}

/**
 * createPickup places an urn, which a hero carries once collected, or a
 * movement buff. Stopping the mod removes it.
 */
export function createPickup(kind: PickupKind, position: Vector): Pickup | undefined {
  const reply = call('CreatePickup', pb.CreatePickupRequest.toBinary({ kind: pickupKindValues[kind], position }))
  if (reply === undefined) return undefined
  const response = pb.PickupResponse.fromBinary(reply)
  return new Pickup(response.pickup ?? 0)
}

/**
 * removeEntities removes every entity of a class, such as npc_trooper,
 * without rewards, and returns how many it removed.
 */
export function removeEntities(className: string): number | undefined {
  const reply = call('RemoveEntities', pb.RemoveEntitiesRequest.toBinary({ className }))
  if (reply === undefined) return undefined
  const response = pb.CountResponse.fromBinary(reply)
  return response.count ?? 0
}

/**
 * clearMap removes the map's own units and objectives, such as troopers,
 * guardians and walkers, so a mode can use the map as an arena.
 */
export function clearMap(): boolean {
  return call('ClearMap', new Uint8Array()) !== undefined
}

/**
 * damage deals a hit as the game would. The mod's Damage events do not
 * include its own hits.
 */
export function damage(options: HitOptions): boolean {
  return call('Damage', pb.HitOptions.toBinary(options)) !== undefined
}

/**
 * trace returns where a line first hits something, or nothing when it hits
 * nothing or the world's collision is not ready.
 */
export function trace(options: TraceOptions): TraceHit | undefined {
  const reply = call('Trace', pb.TraceOptions.toBinary(toTraceOptions(options)))
  if (reply === undefined) return undefined
  const response = pb.TraceResponse.fromBinary(reply)
  return response.hit === undefined ? undefined : fromTraceHit(response.hit)
}

/**
 * restoreNpcs replaces the map's lane units and objectives with targets
 * over the next frames. Units of these classes not in the list are
 * removed, structures that match are kept, and moving units are spawned
 * again in place. An NpcsRestored event reports when every target stands
 * as its own unit, or why not. A new call replaces the running one.
 */
export function restoreNpcs(npcs?: readonly NpcTarget[]): boolean {
  return call('RestoreNpcs', pb.RestoreNpcsRequest.toBinary({ npcs: npcs?.slice() })) !== undefined
}

/**
 * pause stops or resumes the game clock, as the pause command would.
 * Stopping the mod resumes it.
 */
export function pause(paused: boolean): boolean {
  return call('Pause', pb.PauseRequest.toBinary({ paused })) !== undefined
}

/** matchClock returns the match time in seconds that the scoreboard shows. */
export function matchClock(): number | undefined {
  const reply = call('MatchClock', new Uint8Array())
  if (reply === undefined) return undefined
  const response = pb.MatchClockResponse.fromBinary(reply)
  return response.seconds ?? 0
}

/**
 * holdMatchClock keeps the match time at seconds every frame until called
 * again; omitted seconds let it run.
 */
export function holdMatchClock(seconds?: number): boolean {
  return call('HoldMatchClock', pb.HoldMatchClockRequest.toBinary({ seconds })) !== undefined
}

/** rift reads the Rift objective's state. */
export function rift(): RiftState | undefined {
  const reply = call('Rift', new Uint8Array())
  if (reply === undefined) return undefined
  const response = pb.RiftResponse.fromBinary(reply)
  return response.state === undefined ? undefined : fromRiftState(response.state)
}

/** startRift opens the Rift objective at position now. */
export function startRift(position: Vector): boolean {
  return call('StartRift', pb.StartRiftRequest.toBinary({ position })) !== undefined
}

/**
 * moveEntity places any entity, such as a projectile, and replaces its
 * facing and motion when given.
 */
export function moveEntity(entity: number, position: Vector, facing?: Angles, velocity?: Vector): boolean {
  return call('MoveEntity', pb.MoveEntityRequest.toBinary({ entity, position, facing, velocity })) !== undefined
}

/** emitSound plays one game sound on any entity, such as a projectile. */
export function emitSound(entity: number, sound: string): boolean {
  return call('EmitSound', pb.EmitSoundRequest.toBinary({ entity, sound })) !== undefined
}

/**
 * watchProjectiles reports the projectiles with these designer names, such
 * as rocket_launcher_rocket_projectile, in Launch and Impact events. A new
 * call replaces the list; an empty list stops watching.
 */
export function watchProjectiles(options: ProjectileOptions): boolean {
  return call('WatchProjectiles', pb.ProjectileOptions.toBinary(toProjectileOptions(options))) !== undefined
}

/** ModHandlers handles the events the game delivers to the mod. */
export interface ModHandlers {
  /** start begins the mod's active lifetime, once, before any other event. */
  start(event: StartEvent): StartResult
  /** frame runs once per server frame while the mod asked for frames. */
  frame(event: FrameEvent): void
  /** command offers one command a player typed. */
  command(event: CommandEvent): CommandResult
  /**
   * world follows each world load, and start when a world has already
   * loaded. Objects and bots from an earlier world are gone by then.
   */
  world(event: WorldEvent): void
  /** uiPress reports a press on a button in a player's interface. */
  uiPress(event: UiPressEvent): void
  /** serve calls a service the mod serves from the host. */
  serve(event: ServiceCall): ServiceReply
  /**
   * damage offers one hit before the game applies it, while the mod asked
   * for damage. The mod's answer may block the hit or change its amount.
   */
  damage(event: DamageEvent): DamageResult
  /**
   * damaged reports one hit the game applied, while the mod asked for
   * damage reports. Hits arrive before the next frame.
   */
  damaged(event: DamagedEvent): void
  /**
   * input reports one player's presses of watched buttons, before the next
   * frame. A block in place still withholds them from the hero.
   */
  input(event: InputEvent): void
  /** restored ends one RestoreHero, before the next frame. */
  restored(event: RestoredEvent): void
  /** npcsRestored ends one RestoreNpcs, before the next frame. */
  npcsRestored(event: NpcsRestoredEvent): void
  /**
   * launch reports a watched projectile's first frame, before the next frame.
   */
  launch(event: LaunchEvent): void
  /**
   * impact reports a watched projectile striking something, inside the
   * game's impact and after its own explosion. The mod's calls apply before
   * the game continues.
   */
  impact(event: ImpactEvent): void
  /**
   * landed reports a hero landing under the manifest's QuakeWorld movement,
   * before the next frame.
   */
  landed(event: LandedEvent): void
  /**
   * settingChanged reports a player's setting that changed outside the mod,
   * such as on the player's profile. A mod's own SetPlayerSetting reports
   * nothing.
   */
  settingChanged(event: SettingChangedEvent): void
}

/**
 * serveMod runs the encoded Call in bytes on handlers and returns the encoded
 * Reply. A handler that throws answers with its error.
 */
export function serveMod(handlers: ModHandlers, bytes: Uint8Array): Uint8Array {
  const request = pb.Call.fromBinary(bytes)
  const input = request.request ?? new Uint8Array()
  try {
    switch (request.method) {
      case 'Start':
        return reply(pb.StartResult.toBinary(handlers.start(fromStartEvent(pb.StartEvent.fromBinary(input)))))
      case 'Frame':
        handlers.frame(fromFrameEvent(pb.FrameEvent.fromBinary(input)))
        return reply()
      case 'Command':
        return reply(pb.CommandResult.toBinary(handlers.command(fromCommandEvent(pb.CommandEvent.fromBinary(input)))))
      case 'World':
        handlers.world(fromWorldEvent(pb.WorldEvent.fromBinary(input)))
        return reply()
      case 'UiPress':
        handlers.uiPress(fromUiPressEvent(pb.UiPressEvent.fromBinary(input)))
        return reply()
      case 'Serve':
        return reply(pb.ServiceReply.toBinary(handlers.serve(fromServiceCall(pb.ServiceCall.fromBinary(input)))))
      case 'Damage':
        return reply(pb.DamageResult.toBinary(handlers.damage(fromDamageEvent(pb.DamageEvent.fromBinary(input)))))
      case 'Damaged':
        handlers.damaged(fromDamagedEvent(pb.DamagedEvent.fromBinary(input)))
        return reply()
      case 'Input':
        handlers.input(fromInputEvent(pb.InputEvent.fromBinary(input)))
        return reply()
      case 'Restored':
        handlers.restored(fromRestoredEvent(pb.RestoredEvent.fromBinary(input)))
        return reply()
      case 'NpcsRestored':
        handlers.npcsRestored(fromNpcsRestoredEvent(pb.NpcsRestoredEvent.fromBinary(input)))
        return reply()
      case 'Launch':
        handlers.launch(fromLaunchEvent(pb.LaunchEvent.fromBinary(input)))
        return reply()
      case 'Impact':
        handlers.impact(fromImpactEvent(pb.ImpactEvent.fromBinary(input)))
        return reply()
      case 'Landed':
        handlers.landed(fromLandedEvent(pb.LandedEvent.fromBinary(input)))
        return reply()
      case 'SettingChanged':
        handlers.settingChanged(fromSettingChangedEvent(pb.SettingChangedEvent.fromBinary(input)))
        return reply()
    }
  } catch (error) {
    return pb.Reply.toBinary({ error: String(error) })
  }
  return pb.Reply.toBinary({ error: `the mod has no method ${request.method}` })
}
