// Code generated by protoc-gen-go-lite. DO NOT EDIT.
// protoc-gen-go-lite version: v0.17.0
// source: github.com/paralin/modlock/proto/modlock/publish/publish.proto

package publish

import (
	fmt "fmt"
	io "io"
	slices "slices"
	strconv "strconv"

	protobuf_go_lite "github.com/aperturerobotics/protobuf-go-lite"
	json "github.com/aperturerobotics/protobuf-go-lite/json"
)

// ReviewState is a release's review decision.
type ReviewState int32

const (
	// REVIEW_STATE_UNKNOWN awaits a decision, as PENDING does.
	ReviewState_REVIEW_STATE_UNKNOWN ReviewState = 0
	// REVIEW_STATE_PENDING awaits a person's decision.
	ReviewState_REVIEW_STATE_PENDING ReviewState = 1
	// REVIEW_STATE_APPROVED may be played.
	ReviewState_REVIEW_STATE_APPROVED ReviewState = 2
	// REVIEW_STATE_REJECTED was refused.
	ReviewState_REVIEW_STATE_REJECTED ReviewState = 3
)

// Enum value maps for ReviewState.
var (
	ReviewState_name = map[int32]string{
		0: "REVIEW_STATE_UNKNOWN",
		1: "REVIEW_STATE_PENDING",
		2: "REVIEW_STATE_APPROVED",
		3: "REVIEW_STATE_REJECTED",
	}
	ReviewState_value = map[string]int32{
		"REVIEW_STATE_UNKNOWN":  0,
		"REVIEW_STATE_PENDING":  1,
		"REVIEW_STATE_APPROVED": 2,
		"REVIEW_STATE_REJECTED": 3,
	}
)

func (x ReviewState) Enum() *ReviewState {
	p := new(ReviewState)
	*p = x
	return p
}

func (x ReviewState) String() string {
	name, valid := ReviewState_name[int32(x)]
	if valid {
		return name
	}
	return strconv.Itoa(int(x))
}

// SignInExchange trades the one-use code the browser handed back, with the
// verifier that proves this command line started the sign-in, for a session.
type SignInExchange struct {
	unknownFields []byte
	// Code is the one-use code from the browser.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Verifier is the secret whose hash the sign-in page received.
	Verifier string `protobuf:"bytes,2,opt,name=verifier,proto3" json:"verifier,omitempty"`
}

func (x *SignInExchange) Reset() {
	*x = SignInExchange{}
}

func (*SignInExchange) ProtoMessage() {}

func (x *SignInExchange) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SignInExchange) GetVerifier() string {
	if x != nil {
		return x.Verifier
	}
	return ""
}

// SignedIn is the session the exchange returns.
type SignedIn struct {
	unknownFields []byte
	// Token is the bearer credential.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// ExpiresAt is the session's expiry in Unix milliseconds.
	ExpiresAt int64 `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expiresAt,omitempty"`
	// Account is the signed-in account.
	Account *Account `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
}

func (x *SignedIn) Reset() {
	*x = SignedIn{}
}

func (*SignedIn) ProtoMessage() {}

func (x *SignedIn) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SignedIn) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *SignedIn) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

// Account names the signed-in player.
type Account struct {
	unknownFields []byte
	// DisplayName is the player's name.
	DisplayName string `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"displayName,omitempty"`
	// SteamId64 is the player's Steam account.
	SteamId64 uint64 `protobuf:"varint,6,opt,name=steam_id64,json=steamId64,proto3" json:"steamId64,omitempty"`
}

func (x *Account) Reset() {
	*x = Account{}
}

func (*Account) ProtoMessage() {}

func (x *Account) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Account) GetSteamId64() uint64 {
	if x != nil {
		return x.SteamId64
	}
	return 0
}

// Release is a published release as the service reports it.
type Release struct {
	unknownFields []byte
	// Slug is the mod's slug.
	Slug string `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	// Version is the release's version.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Name is the mod's name.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// ReviewState is the release's review decision.
	ReviewState ReviewState `protobuf:"varint,10,opt,name=review_state,json=reviewState,proto3" json:"reviewState,omitempty"`
	// ReviewNote explains the decision.
	ReviewNote string `protobuf:"bytes,13,opt,name=review_note,json=reviewNote,proto3" json:"reviewNote,omitempty"`
}

func (x *Release) Reset() {
	*x = Release{}
}

func (*Release) ProtoMessage() {}

func (x *Release) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Release) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Release) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Release) GetReviewState() ReviewState {
	if x != nil {
		return x.ReviewState
	}
	return ReviewState_REVIEW_STATE_UNKNOWN
}

func (x *Release) GetReviewNote() string {
	if x != nil {
		return x.ReviewNote
	}
	return ""
}

// Error is a refused request's explanation.
type Error struct {
	unknownFields []byte
	// Code names the refusal for programs.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Message explains the refusal to the creator.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
}

func (*Error) ProtoMessage() {}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Session is the saved sign-in for one service origin.
type Session struct {
	unknownFields []byte
	// Origin is the service that issued the session.
	Origin string `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	// Token is the bearer credential.
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	// ExpiresAt is the session's expiry in Unix milliseconds.
	ExpiresAt int64 `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expiresAt,omitempty"`
	// Name is the signed-in player's name.
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Session) Reset() {
	*x = Session{}
}

func (*Session) ProtoMessage() {}

func (x *Session) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *Session) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Session) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *Session) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (m *SignInExchange) CloneVT() *SignInExchange {
	if m == nil {
		return (*SignInExchange)(nil)
	}
	r := new(SignInExchange)
	r.Code = m.Code
	r.Verifier = m.Verifier
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *SignInExchange) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *SignedIn) CloneVT() *SignedIn {
	if m == nil {
		return (*SignedIn)(nil)
	}
	r := new(SignedIn)
	r.Token = m.Token
	r.ExpiresAt = m.ExpiresAt
	r.Account = protobuf_go_lite.CloneVTValue(m.Account)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *SignedIn) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *Account) CloneVT() *Account {
	if m == nil {
		return (*Account)(nil)
	}
	r := new(Account)
	r.DisplayName = m.DisplayName
	r.SteamId64 = m.SteamId64
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *Account) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *Release) CloneVT() *Release {
	if m == nil {
		return (*Release)(nil)
	}
	r := new(Release)
	r.Slug = m.Slug
	r.Version = m.Version
	r.Name = m.Name
	r.ReviewState = m.ReviewState
	r.ReviewNote = m.ReviewNote
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *Release) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *Error) CloneVT() *Error {
	if m == nil {
		return (*Error)(nil)
	}
	r := new(Error)
	r.Code = m.Code
	r.Message = m.Message
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *Error) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *Session) CloneVT() *Session {
	if m == nil {
		return (*Session)(nil)
	}
	r := new(Session)
	r.Origin = m.Origin
	r.Token = m.Token
	r.ExpiresAt = m.ExpiresAt
	r.Name = m.Name
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *Session) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (this *SignInExchange) EqualVT(that *SignInExchange) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Code != that.Code {
		return false
	}
	if this.Verifier != that.Verifier {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *SignInExchange) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*SignInExchange)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *SignedIn) EqualVT(that *SignedIn) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Token != that.Token {
		return false
	}
	if this.ExpiresAt != that.ExpiresAt {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.Account, that.Account) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *SignedIn) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*SignedIn)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *Account) EqualVT(that *Account) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.DisplayName != that.DisplayName {
		return false
	}
	if this.SteamId64 != that.SteamId64 {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Account) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*Account)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *Release) EqualVT(that *Release) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Slug != that.Slug {
		return false
	}
	if this.Version != that.Version {
		return false
	}
	if this.Name != that.Name {
		return false
	}
	if this.ReviewState != that.ReviewState {
		return false
	}
	if this.ReviewNote != that.ReviewNote {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Release) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*Release)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *Error) EqualVT(that *Error) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Code != that.Code {
		return false
	}
	if this.Message != that.Message {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Error) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*Error)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *Session) EqualVT(that *Session) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Origin != that.Origin {
		return false
	}
	if this.Token != that.Token {
		return false
	}
	if this.ExpiresAt != that.ExpiresAt {
		return false
	}
	if this.Name != that.Name {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Session) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*Session)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

// MarshalProtoJSON marshals the ReviewState to JSON.
func (x ReviewState) MarshalProtoJSON(s *json.MarshalState) {
	s.WriteEnum(int32(x), ReviewState_name)
}

// MarshalText marshals the ReviewState to text.
func (x ReviewState) MarshalText() ([]byte, error) {
	return []byte(json.GetEnumString(int32(x), ReviewState_name)), nil
}

// MarshalJSON marshals the ReviewState to JSON.
func (x ReviewState) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the ReviewState from JSON.
func (x *ReviewState) UnmarshalProtoJSON(s *json.UnmarshalState) {
	v := s.ReadEnum(ReviewState_value)
	if err := s.Err(); err != nil {
		s.SetErrorf("could not read ReviewState enum: %v", err)
		return
	}
	*x = ReviewState(v)
}

// UnmarshalText unmarshals the ReviewState from text.
func (x *ReviewState) UnmarshalText(b []byte) error {
	i, err := json.ParseEnumString(string(b), ReviewState_value)
	if err != nil {
		return err
	}
	*x = ReviewState(i)
	return nil
}

// UnmarshalJSON unmarshals the ReviewState from JSON.
func (x *ReviewState) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the SignInExchange message to JSON.
func (x *SignInExchange) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Code != "" || s.HasField("code") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("code")
		s.WriteString(x.Code)
	}
	if x.Verifier != "" || s.HasField("verifier") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("verifier")
		s.WriteString(x.Verifier)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the SignInExchange to JSON.
func (x *SignInExchange) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the SignInExchange message from JSON.
func (x *SignInExchange) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "code":
			s.AddField("code")
			x.Code = s.ReadString()
		case "verifier":
			s.AddField("verifier")
			x.Verifier = s.ReadString()
		}
	})
}

// UnmarshalJSON unmarshals the SignInExchange from JSON.
func (x *SignInExchange) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the SignedIn message to JSON.
func (x *SignedIn) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Token != "" || s.HasField("token") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("token")
		s.WriteString(x.Token)
	}
	if x.ExpiresAt != 0 || s.HasField("expiresAt") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("expiresAt")
		s.WriteInt64(x.ExpiresAt)
	}
	if x.Account != nil || s.HasField("account") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("account")
		x.Account.MarshalProtoJSON(s.WithField("account"))
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the SignedIn to JSON.
func (x *SignedIn) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the SignedIn message from JSON.
func (x *SignedIn) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "token":
			s.AddField("token")
			x.Token = s.ReadString()
		case "expires_at", "expiresAt":
			s.AddField("expires_at")
			x.ExpiresAt = s.ReadInt64()
		case "account":
			if s.ReadNil() {
				x.Account = nil
				return
			}
			x.Account = &Account{}
			x.Account.UnmarshalProtoJSON(s.WithField("account", true))
		}
	})
}

// UnmarshalJSON unmarshals the SignedIn from JSON.
func (x *SignedIn) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the Account message to JSON.
func (x *Account) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.DisplayName != "" || s.HasField("displayName") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("displayName")
		s.WriteString(x.DisplayName)
	}
	if x.SteamId64 != 0 || s.HasField("steamId64") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("steamId64")
		s.WriteUint64(x.SteamId64)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the Account to JSON.
func (x *Account) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the Account message from JSON.
func (x *Account) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "display_name", "displayName":
			s.AddField("display_name")
			x.DisplayName = s.ReadString()
		case "steam_id64", "steamId64":
			s.AddField("steam_id64")
			x.SteamId64 = s.ReadUint64()
		}
	})
}

// UnmarshalJSON unmarshals the Account from JSON.
func (x *Account) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the Release message to JSON.
func (x *Release) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Slug != "" || s.HasField("slug") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("slug")
		s.WriteString(x.Slug)
	}
	if x.Version != "" || s.HasField("version") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("version")
		s.WriteString(x.Version)
	}
	if x.Name != "" || s.HasField("name") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("name")
		s.WriteString(x.Name)
	}
	if x.ReviewState != 0 || s.HasField("reviewState") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("reviewState")
		x.ReviewState.MarshalProtoJSON(s)
	}
	if x.ReviewNote != "" || s.HasField("reviewNote") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("reviewNote")
		s.WriteString(x.ReviewNote)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the Release to JSON.
func (x *Release) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the Release message from JSON.
func (x *Release) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "slug":
			s.AddField("slug")
			x.Slug = s.ReadString()
		case "version":
			s.AddField("version")
			x.Version = s.ReadString()
		case "name":
			s.AddField("name")
			x.Name = s.ReadString()
		case "review_state", "reviewState":
			s.AddField("review_state")
			x.ReviewState.UnmarshalProtoJSON(s)
		case "review_note", "reviewNote":
			s.AddField("review_note")
			x.ReviewNote = s.ReadString()
		}
	})
}

// UnmarshalJSON unmarshals the Release from JSON.
func (x *Release) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the Error message to JSON.
func (x *Error) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Code != "" || s.HasField("code") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("code")
		s.WriteString(x.Code)
	}
	if x.Message != "" || s.HasField("message") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("message")
		s.WriteString(x.Message)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the Error to JSON.
func (x *Error) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the Error message from JSON.
func (x *Error) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "code":
			s.AddField("code")
			x.Code = s.ReadString()
		case "message":
			s.AddField("message")
			x.Message = s.ReadString()
		}
	})
}

// UnmarshalJSON unmarshals the Error from JSON.
func (x *Error) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the Session message to JSON.
func (x *Session) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Origin != "" || s.HasField("origin") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("origin")
		s.WriteString(x.Origin)
	}
	if x.Token != "" || s.HasField("token") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("token")
		s.WriteString(x.Token)
	}
	if x.ExpiresAt != 0 || s.HasField("expiresAt") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("expiresAt")
		s.WriteInt64(x.ExpiresAt)
	}
	if x.Name != "" || s.HasField("name") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("name")
		s.WriteString(x.Name)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the Session to JSON.
func (x *Session) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the Session message from JSON.
func (x *Session) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "origin":
			s.AddField("origin")
			x.Origin = s.ReadString()
		case "token":
			s.AddField("token")
			x.Token = s.ReadString()
		case "expires_at", "expiresAt":
			s.AddField("expires_at")
			x.ExpiresAt = s.ReadInt64()
		case "name":
			s.AddField("name")
			x.Name = s.ReadString()
		}
	})
}

// UnmarshalJSON unmarshals the Session from JSON.
func (x *Session) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

func (m *SignInExchange) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SignInExchange) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *SignInExchange) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if len(m.Verifier) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.Verifier)
		i--
		dAtA[i] = 0x12
	}
	if len(m.Code) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.Code)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SignedIn) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SignedIn) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *SignedIn) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.Account != nil {
		size, err := m.Account.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x1a
	}
	if m.ExpiresAt != 0 {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(m.ExpiresAt))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Token) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.Token)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Account) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Account) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Account) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.SteamId64 != 0 {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(m.SteamId64))
		i--
		dAtA[i] = 0x30
	}
	if len(m.DisplayName) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.DisplayName)
		i--
		dAtA[i] = 0x22
	}
	return len(dAtA) - i, nil
}

func (m *Release) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Release) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Release) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if len(m.ReviewNote) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.ReviewNote)
		i--
		dAtA[i] = 0x6a
	}
	if m.ReviewState != 0 {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(m.ReviewState))
		i--
		dAtA[i] = 0x50
	}
	if len(m.Name) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.Name)
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Version) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.Version)
		i--
		dAtA[i] = 0x12
	}
	if len(m.Slug) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.Slug)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Error) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Error) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Error) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if len(m.Message) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.Message)
		i--
		dAtA[i] = 0x12
	}
	if len(m.Code) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.Code)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Session) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Session) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Session) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if len(m.Name) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.Name)
		i--
		dAtA[i] = 0x22
	}
	if m.ExpiresAt != 0 {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(m.ExpiresAt))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Token) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.Token)
		i--
		dAtA[i] = 0x12
	}
	if len(m.Origin) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.Origin)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SignInExchange) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.Code)
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.Verifier)
	n += len(m.unknownFields)
	return n
}

func (m *SignedIn) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.Token)
	n += protobuf_go_lite.SizeVarintNonZero(1, m.ExpiresAt)
	if m.Account != nil {
		l = m.Account.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	n += len(m.unknownFields)
	return n
}

func (m *Account) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.DisplayName)
	n += protobuf_go_lite.SizeVarintNonZero(1, m.SteamId64)
	n += len(m.unknownFields)
	return n
}

func (m *Release) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.Slug)
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.Version)
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.Name)
	n += protobuf_go_lite.SizeVarintNonZero(1, m.ReviewState)
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.ReviewNote)
	n += len(m.unknownFields)
	return n
}

func (m *Error) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.Code)
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.Message)
	n += len(m.unknownFields)
	return n
}

func (m *Session) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.Origin)
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.Token)
	n += protobuf_go_lite.SizeVarintNonZero(1, m.ExpiresAt)
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.Name)
	n += len(m.unknownFields)
	return n
}

func (x ReviewState) MarshalProtoText() string {
	return x.String()
}

func (x *SignInExchange) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "SignInExchange")
	if x.Code != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "code")
		protobuf_go_lite.TextWriteString(&sb, x.Code)
	}
	if x.Verifier != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "verifier")
		protobuf_go_lite.TextWriteString(&sb, x.Verifier)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *SignInExchange) String() string {
	return x.MarshalProtoText()
}

func (x *SignedIn) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "SignedIn")
	if x.Token != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "token")
		protobuf_go_lite.TextWriteString(&sb, x.Token)
	}
	if x.ExpiresAt != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "expires_at")
		protobuf_go_lite.TextWriteInt(&sb, x.ExpiresAt)
	}
	if x.Account != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "account")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.Account)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *SignedIn) String() string {
	return x.MarshalProtoText()
}

func (x *Account) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "Account")
	if x.DisplayName != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "display_name")
		protobuf_go_lite.TextWriteString(&sb, x.DisplayName)
	}
	if x.SteamId64 != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "steam_id64")
		protobuf_go_lite.TextWriteUint(&sb, x.SteamId64)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *Account) String() string {
	return x.MarshalProtoText()
}

func (x *Release) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "Release")
	if x.Slug != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "slug")
		protobuf_go_lite.TextWriteString(&sb, x.Slug)
	}
	if x.Version != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "version")
		protobuf_go_lite.TextWriteString(&sb, x.Version)
	}
	if x.Name != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "name")
		protobuf_go_lite.TextWriteString(&sb, x.Name)
	}
	if x.ReviewState != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "review_state")
		protobuf_go_lite.TextWriteStringer(&sb, ReviewState(x.ReviewState))
	}
	if x.ReviewNote != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "review_note")
		protobuf_go_lite.TextWriteString(&sb, x.ReviewNote)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *Release) String() string {
	return x.MarshalProtoText()
}

func (x *Error) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "Error")
	if x.Code != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "code")
		protobuf_go_lite.TextWriteString(&sb, x.Code)
	}
	if x.Message != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "message")
		protobuf_go_lite.TextWriteString(&sb, x.Message)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *Error) String() string {
	return x.MarshalProtoText()
}

func (x *Session) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "Session")
	if x.Origin != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "origin")
		protobuf_go_lite.TextWriteString(&sb, x.Origin)
	}
	if x.Token != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "token")
		protobuf_go_lite.TextWriteString(&sb, x.Token)
	}
	if x.ExpiresAt != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "expires_at")
		protobuf_go_lite.TextWriteInt(&sb, x.ExpiresAt)
	}
	if x.Name != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "name")
		protobuf_go_lite.TextWriteString(&sb, x.Name)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *Session) String() string {
	return x.MarshalProtoText()
}

func (m *SignInExchange) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SignInExchange: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SignInExchange: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Code = v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Verifier", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Verifier = v
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *SignedIn) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SignedIn: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SignedIn: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Token = v
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiresAt", wireType)
			}
			m.ExpiresAt = 0
			m.ExpiresAt, iNdEx, err = protobuf_go_lite.DecodeVarintInt64(dAtA, iNdEx)
			if err != nil {
				return err
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.Account == nil {
				m.Account = &Account{}
			}
			if err := m.Account.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *Account) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Account: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Account: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisplayName", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.DisplayName = v
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SteamId64", wireType)
			}
			m.SteamId64 = 0
			m.SteamId64, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			if err != nil {
				return err
			}
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *Release) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Release: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Release: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Slug", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Slug = v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Version = v
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Name = v
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReviewState", wireType)
			}
			m.ReviewState = 0
			var _v uint64
			_v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			m.ReviewState = ReviewState(_v)
			if err != nil {
				return err
			}
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReviewNote", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.ReviewNote = v
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *Error) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Error: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Error: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Code = v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Message = v
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *Session) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Session: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Session: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Origin", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Origin = v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Token = v
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiresAt", wireType)
			}
			m.ExpiresAt = 0
			m.ExpiresAt, iNdEx, err = protobuf_go_lite.DecodeVarintInt64(dAtA, iNdEx)
			if err != nil {
				return err
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Name = v
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
