// Code generated by protoc-gen-go-lite. DO NOT EDIT.
// protoc-gen-go-lite version: v0.17.0
// source: github.com/paralin/modlock/proto/modlock/ui.proto

package ui

import (
	fmt "fmt"
	protobuf_go_lite "github.com/aperturerobotics/protobuf-go-lite"
	json "github.com/aperturerobotics/protobuf-go-lite/json"
	io "io"
	math "math"
	slices "slices"
	strconv "strconv"
)

// Kind selects the panel a node draws.
type Kind int32

const (
	// KIND_PANEL groups and lays out its children.
	Kind_KIND_PANEL Kind = 0
	// KIND_LABEL shows text.
	Kind_KIND_LABEL Kind = 1
	// KIND_IMAGE shows an image.
	Kind_KIND_IMAGE Kind = 2
	// KIND_BUTTON holds its children and reports each press to the mod. A
	// button takes clicks only while the player has a cursor.
	Kind_KIND_BUTTON Kind = 3
)

// Enum value maps for Kind.
var (
	Kind_name = map[int32]string{
		0: "KIND_PANEL",
		1: "KIND_LABEL",
		2: "KIND_IMAGE",
		3: "KIND_BUTTON",
	}
	Kind_value = map[string]int32{
		"KIND_PANEL":  0,
		"KIND_LABEL":  1,
		"KIND_IMAGE":  2,
		"KIND_BUTTON": 3,
	}
)

func (x Kind) Enum() *Kind {
	p := new(Kind)
	*p = x
	return p
}

func (x Kind) String() string {
	name, valid := Kind_name[int32(x)]
	if valid {
		return name
	}
	return strconv.Itoa(int(x))
}

// Flow arranges a node's children.
type Flow int32

const (
	// FLOW_NONE stacks children on top of each other.
	Flow_FLOW_NONE Flow = 0
	// FLOW_DOWN places children in a column.
	Flow_FLOW_DOWN Flow = 1
	// FLOW_RIGHT places children in a row.
	Flow_FLOW_RIGHT Flow = 2
)

// Enum value maps for Flow.
var (
	Flow_name = map[int32]string{
		0: "FLOW_NONE",
		1: "FLOW_DOWN",
		2: "FLOW_RIGHT",
	}
	Flow_value = map[string]int32{
		"FLOW_NONE":  0,
		"FLOW_DOWN":  1,
		"FLOW_RIGHT": 2,
	}
)

func (x Flow) Enum() *Flow {
	p := new(Flow)
	*p = x
	return p
}

func (x Flow) String() string {
	name, valid := Flow_name[int32(x)]
	if valid {
		return name
	}
	return strconv.Itoa(int(x))
}

// Align places a node or text along one axis.
type Align int32

const (
	// ALIGN_START places it at the left or top.
	Align_ALIGN_START Align = 0
	// ALIGN_CENTER centers it.
	Align_ALIGN_CENTER Align = 1
	// ALIGN_END places it at the right or bottom.
	Align_ALIGN_END Align = 2
)

// Enum value maps for Align.
var (
	Align_name = map[int32]string{
		0: "ALIGN_START",
		1: "ALIGN_CENTER",
		2: "ALIGN_END",
	}
	Align_value = map[string]int32{
		"ALIGN_START":  0,
		"ALIGN_CENTER": 1,
		"ALIGN_END":    2,
	}
)

func (x Align) Enum() *Align {
	p := new(Align)
	*p = x
	return p
}

func (x Align) String() string {
	name, valid := Align_name[int32(x)]
	if valid {
		return name
	}
	return strconv.Itoa(int(x))
}

// Node is one panel in a tree. The root's id is empty; it is a full-screen
// panel that lets clicks through to the game.
type Node struct {
	unknownFields []byte
	// Id names the node within its tree.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Kind selects the panel the node draws.
	Kind Kind `protobuf:"varint,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// Children lists the ids of the node's children in drawing order. A node
	// that no parent lists is not drawn.
	Children []string `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"`
	// Text is a label's words.
	Text string `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	// Image is an image's path in the game's content, such as
	// "file://{images}/heroes/wraith_card.psd".
	Image string `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	// Style lays out and paints the node.
	Style *Style `protobuf:"bytes,6,opt,name=style,proto3" json:"style,omitempty"`
}

func (x *Node) Reset() {
	*x = Node{}
}

func (*Node) ProtoMessage() {}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_KIND_PANEL
}

func (x *Node) GetChildren() []string {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *Node) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Node) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Node) GetStyle() *Style {
	if x != nil {
		return x.Style
	}
	return nil
}

// Style is the closed set of layout and paint properties a node may set. A
// zero value leaves the panel's default.
type Style struct {
	unknownFields []byte
	// Width is the node's width.
	Width *Length `protobuf:"bytes,1,opt,name=width,proto3" json:"width,omitempty"`
	// Height is the node's height.
	Height *Length `protobuf:"bytes,2,opt,name=height,proto3" json:"height,omitempty"`
	// Flow arranges the node's children.
	Flow Flow `protobuf:"varint,3,opt,name=flow,proto3" json:"flow,omitempty"`
	// HorizontalAlign places the node within its parent's width.
	HorizontalAlign Align `protobuf:"varint,4,opt,name=horizontal_align,json=horizontalAlign,proto3" json:"horizontalAlign,omitempty"`
	// VerticalAlign places the node within its parent's height.
	VerticalAlign Align `protobuf:"varint,5,opt,name=vertical_align,json=verticalAlign,proto3" json:"verticalAlign,omitempty"`
	// Margin is the space outside the node, in pixels.
	Margin *Edges `protobuf:"bytes,6,opt,name=margin,proto3" json:"margin,omitempty"`
	// Padding is the space between the node's edge and its children, in pixels.
	Padding *Edges `protobuf:"bytes,7,opt,name=padding,proto3" json:"padding,omitempty"`
	// Background is the fill color as 0xRRGGBBAA; zero is transparent.
	Background uint32 `protobuf:"fixed32,8,opt,name=background,proto3" json:"background,omitempty"`
	// Color is the text color as 0xRRGGBBAA; zero keeps the default.
	Color uint32 `protobuf:"fixed32,9,opt,name=color,proto3" json:"color,omitempty"`
	// FontSize is the text size in pixels; zero keeps the default.
	FontSize float32 `protobuf:"fixed32,10,opt,name=font_size,json=fontSize,proto3" json:"fontSize,omitempty"`
	// Bold sets bold text.
	Bold bool `protobuf:"varint,11,opt,name=bold,proto3" json:"bold,omitempty"`
	// TextAlign places text within a label.
	TextAlign Align `protobuf:"varint,12,opt,name=text_align,json=textAlign,proto3" json:"textAlign,omitempty"`
	// BorderRadius rounds the corners, in pixels.
	BorderRadius float32 `protobuf:"fixed32,13,opt,name=border_radius,json=borderRadius,proto3" json:"borderRadius,omitempty"`
	// Opacity fades the node and its children, from 0 to 1; unset is opaque.
	Opacity *float32 `protobuf:"fixed32,14,opt,name=opacity,proto3,oneof" json:"opacity,omitempty"`
}

func (x *Style) Reset() {
	*x = Style{}
}

func (*Style) ProtoMessage() {}

func (x *Style) GetWidth() *Length {
	if x != nil {
		return x.Width
	}
	return nil
}

func (x *Style) GetHeight() *Length {
	if x != nil {
		return x.Height
	}
	return nil
}

func (x *Style) GetFlow() Flow {
	if x != nil {
		return x.Flow
	}
	return Flow_FLOW_NONE
}

func (x *Style) GetHorizontalAlign() Align {
	if x != nil {
		return x.HorizontalAlign
	}
	return Align_ALIGN_START
}

func (x *Style) GetVerticalAlign() Align {
	if x != nil {
		return x.VerticalAlign
	}
	return Align_ALIGN_START
}

func (x *Style) GetMargin() *Edges {
	if x != nil {
		return x.Margin
	}
	return nil
}

func (x *Style) GetPadding() *Edges {
	if x != nil {
		return x.Padding
	}
	return nil
}

func (x *Style) GetBackground() uint32 {
	if x != nil {
		return x.Background
	}
	return 0
}

func (x *Style) GetColor() uint32 {
	if x != nil {
		return x.Color
	}
	return 0
}

func (x *Style) GetFontSize() float32 {
	if x != nil {
		return x.FontSize
	}
	return 0
}

func (x *Style) GetBold() bool {
	if x != nil {
		return x.Bold
	}
	return false
}

func (x *Style) GetTextAlign() Align {
	if x != nil {
		return x.TextAlign
	}
	return Align_ALIGN_START
}

func (x *Style) GetBorderRadius() float32 {
	if x != nil {
		return x.BorderRadius
	}
	return 0
}

func (x *Style) GetOpacity() float32 {
	if x != nil && x.Opacity != nil {
		return *x.Opacity
	}
	return 0
}

// Length is a size along one axis.
type Length struct {
	unknownFields []byte
	// Value selects the unit.
	//
	// Types that are assignable to Value:
	//
	//	*Length_Pixels
	//	*Length_Percent
	//	*Length_FitChildren
	//	*Length_Fill
	Value isLength_Value `protobuf_oneof:"value"`
}

func (x *Length) Reset() {
	*x = Length{}
}

func (*Length) ProtoMessage() {}

func (m *Length) GetValue() isLength_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *Length) GetPixels() float32 {
	if x, ok := x.GetValue().(*Length_Pixels); ok {
		return x.Pixels
	}
	return 0
}

func (x *Length) GetPercent() float32 {
	if x, ok := x.GetValue().(*Length_Percent); ok {
		return x.Percent
	}
	return 0
}

func (x *Length) GetFitChildren() bool {
	if x, ok := x.GetValue().(*Length_FitChildren); ok {
		return x.FitChildren
	}
	return false
}

func (x *Length) GetFill() float32 {
	if x, ok := x.GetValue().(*Length_Fill); ok {
		return x.Fill
	}
	return 0
}

type isLength_Value interface {
	isLength_Value()
}

type Length_Pixels struct {
	// Pixels is a fixed size.
	Pixels float32 `protobuf:"fixed32,1,opt,name=pixels,proto3,oneof"`
}

type Length_Percent struct {
	// Percent is a share of the parent's size, from 0 to 100.
	Percent float32 `protobuf:"fixed32,2,opt,name=percent,proto3,oneof"`
}

type Length_FitChildren struct {
	// FitChildren sizes the node to its children.
	FitChildren bool `protobuf:"varint,3,opt,name=fit_children,json=fitChildren,proto3,oneof"`
}

type Length_Fill struct {
	// Fill shares the space left in the parent's flow by this weight.
	Fill float32 `protobuf:"fixed32,4,opt,name=fill,proto3,oneof"`
}

func (*Length_Pixels) isLength_Value() {}

func (*Length_Percent) isLength_Value() {}

func (*Length_FitChildren) isLength_Value() {}

func (*Length_Fill) isLength_Value() {}

// Edges are pixel distances on each side.
type Edges struct {
	unknownFields []byte
	// Top is the distance on the top side.
	Top float32 `protobuf:"fixed32,1,opt,name=top,proto3" json:"top,omitempty"`
	// Right is the distance on the right side.
	Right float32 `protobuf:"fixed32,2,opt,name=right,proto3" json:"right,omitempty"`
	// Bottom is the distance on the bottom side.
	Bottom float32 `protobuf:"fixed32,3,opt,name=bottom,proto3" json:"bottom,omitempty"`
	// Left is the distance on the left side.
	Left float32 `protobuf:"fixed32,4,opt,name=left,proto3" json:"left,omitempty"`
}

func (x *Edges) Reset() {
	*x = Edges{}
}

func (*Edges) ProtoMessage() {}

func (x *Edges) GetTop() float32 {
	if x != nil {
		return x.Top
	}
	return 0
}

func (x *Edges) GetRight() float32 {
	if x != nil {
		return x.Right
	}
	return 0
}

func (x *Edges) GetBottom() float32 {
	if x != nil {
		return x.Bottom
	}
	return 0
}

func (x *Edges) GetLeft() float32 {
	if x != nil {
		return x.Left
	}
	return 0
}

// Change updates one player's tree. Reset clears the tree first; then each
// node in set replaces the node with its id, and each id in removed drops
// that node.
type Change struct {
	unknownFields []byte
	// Reset clears the tree before the rest of the change applies.
	Reset_ bool `protobuf:"varint,1,opt,name=reset,proto3" json:"reset,omitempty"`
	// Set holds the new or changed nodes.
	Set []*Node `protobuf:"bytes,2,rep,name=set,proto3" json:"set,omitempty"`
	// Removed holds the ids of the nodes to drop.
	Removed []string `protobuf:"bytes,3,rep,name=removed,proto3" json:"removed,omitempty"`
}

func (x *Change) Reset() {
	*x = Change{}
}

func (*Change) ProtoMessage() {}

func (x *Change) GetReset_() bool {
	if x != nil {
		return x.Reset_
	}
	return false
}

func (x *Change) GetSet() []*Node {
	if x != nil {
		return x.Set
	}
	return nil
}

func (x *Change) GetRemoved() []string {
	if x != nil {
		return x.Removed
	}
	return nil
}

// Tree is one mod's whole tree for one player.
type Tree struct {
	unknownFields []byte
	// Mod is the mod's name.
	Mod string `protobuf:"bytes,1,opt,name=mod,proto3" json:"mod,omitempty"`
	// Nodes holds every node, the root included.
	Nodes []*Node `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *Tree) Reset() {
	*x = Tree{}
}

func (*Tree) ProtoMessage() {}

func (x *Tree) GetMod() string {
	if x != nil {
		return x.Mod
	}
	return ""
}

func (x *Tree) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

// Screen is everything one player's renderer draws: each mod's tree.
type Screen struct {
	unknownFields []byte
	// Trees holds one tree per mod that shows this player anything.
	Trees []*Tree `protobuf:"bytes,1,rep,name=trees,proto3" json:"trees,omitempty"`
}

func (x *Screen) Reset() {
	*x = Screen{}
}

func (*Screen) ProtoMessage() {}

func (x *Screen) GetTrees() []*Tree {
	if x != nil {
		return x.Trees
	}
	return nil
}

func (m *Node) CloneVT() *Node {
	if m == nil {
		return (*Node)(nil)
	}
	r := new(Node)
	r.Id = m.Id
	r.Kind = m.Kind
	r.Text = m.Text
	r.Image = m.Image
	r.Children = protobuf_go_lite.CloneSlice(m.Children)
	r.Style = protobuf_go_lite.CloneVTValue(m.Style)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *Node) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *Style) CloneVT() *Style {
	if m == nil {
		return (*Style)(nil)
	}
	r := new(Style)
	r.Flow = m.Flow
	r.HorizontalAlign = m.HorizontalAlign
	r.VerticalAlign = m.VerticalAlign
	r.Background = m.Background
	r.Color = m.Color
	r.FontSize = m.FontSize
	r.Bold = m.Bold
	r.TextAlign = m.TextAlign
	r.BorderRadius = m.BorderRadius
	r.Width = protobuf_go_lite.CloneVTValue(m.Width)
	r.Height = protobuf_go_lite.CloneVTValue(m.Height)
	r.Margin = protobuf_go_lite.CloneVTValue(m.Margin)
	r.Padding = protobuf_go_lite.CloneVTValue(m.Padding)
	r.Opacity = protobuf_go_lite.ClonePtr(m.Opacity)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *Style) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *Length) CloneVT() *Length {
	if m == nil {
		return (*Length)(nil)
	}
	r := new(Length)
	if m.Value != nil {
		r.Value = m.Value.(interface{ CloneOneofVT() isLength_Value }).CloneOneofVT()
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *Length) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *Length_Pixels) CloneVT() *Length_Pixels {
	if m == nil {
		return (*Length_Pixels)(nil)
	}
	r := new(Length_Pixels)
	r.Pixels = m.Pixels
	return r
}

func (m *Length_Pixels) CloneOneofVT() isLength_Value {
	return m.CloneVT()
}

func (m *Length_Percent) CloneVT() *Length_Percent {
	if m == nil {
		return (*Length_Percent)(nil)
	}
	r := new(Length_Percent)
	r.Percent = m.Percent
	return r
}

func (m *Length_Percent) CloneOneofVT() isLength_Value {
	return m.CloneVT()
}

func (m *Length_FitChildren) CloneVT() *Length_FitChildren {
	if m == nil {
		return (*Length_FitChildren)(nil)
	}
	r := new(Length_FitChildren)
	r.FitChildren = m.FitChildren
	return r
}

func (m *Length_FitChildren) CloneOneofVT() isLength_Value {
	return m.CloneVT()
}

func (m *Length_Fill) CloneVT() *Length_Fill {
	if m == nil {
		return (*Length_Fill)(nil)
	}
	r := new(Length_Fill)
	r.Fill = m.Fill
	return r
}

func (m *Length_Fill) CloneOneofVT() isLength_Value {
	return m.CloneVT()
}

func (m *Edges) CloneVT() *Edges {
	if m == nil {
		return (*Edges)(nil)
	}
	r := new(Edges)
	r.Top = m.Top
	r.Right = m.Right
	r.Bottom = m.Bottom
	r.Left = m.Left
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *Edges) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *Change) CloneVT() *Change {
	if m == nil {
		return (*Change)(nil)
	}
	r := new(Change)
	r.Reset_ = m.Reset_
	r.Set = protobuf_go_lite.CloneVTSlice(m.Set)
	r.Removed = protobuf_go_lite.CloneSlice(m.Removed)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *Change) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *Tree) CloneVT() *Tree {
	if m == nil {
		return (*Tree)(nil)
	}
	r := new(Tree)
	r.Mod = m.Mod
	r.Nodes = protobuf_go_lite.CloneVTSlice(m.Nodes)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *Tree) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *Screen) CloneVT() *Screen {
	if m == nil {
		return (*Screen)(nil)
	}
	r := new(Screen)
	r.Trees = protobuf_go_lite.CloneVTSlice(m.Trees)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *Screen) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (this *Node) EqualVT(that *Node) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Id != that.Id {
		return false
	}
	if this.Kind != that.Kind {
		return false
	}
	if !protobuf_go_lite.EqualSlice(this.Children, that.Children) {
		return false
	}
	if this.Text != that.Text {
		return false
	}
	if this.Image != that.Image {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.Style, that.Style) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Node) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*Node)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *Style) EqualVT(that *Style) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.Width, that.Width) {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.Height, that.Height) {
		return false
	}
	if this.Flow != that.Flow {
		return false
	}
	if this.HorizontalAlign != that.HorizontalAlign {
		return false
	}
	if this.VerticalAlign != that.VerticalAlign {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.Margin, that.Margin) {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.Padding, that.Padding) {
		return false
	}
	if this.Background != that.Background {
		return false
	}
	if this.Color != that.Color {
		return false
	}
	if this.FontSize != that.FontSize {
		return false
	}
	if this.Bold != that.Bold {
		return false
	}
	if this.TextAlign != that.TextAlign {
		return false
	}
	if this.BorderRadius != that.BorderRadius {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.Opacity, that.Opacity) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Style) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*Style)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *Length) EqualVT(that *Length) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Value == nil && that.Value != nil {
		return false
	} else if this.Value != nil {
		if that.Value == nil {
			return false
		}
		if !this.Value.(interface{ EqualVT(isLength_Value) bool }).EqualVT(that.Value) {
			return false
		}
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Length) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*Length)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *Length_Pixels) EqualVT(thatIface isLength_Value) bool {
	that, ok := thatIface.(*Length_Pixels)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if this.Pixels != that.Pixels {
		return false
	}
	return true
}

func (this *Length_Percent) EqualVT(thatIface isLength_Value) bool {
	that, ok := thatIface.(*Length_Percent)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if this.Percent != that.Percent {
		return false
	}
	return true
}

func (this *Length_FitChildren) EqualVT(thatIface isLength_Value) bool {
	that, ok := thatIface.(*Length_FitChildren)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if this.FitChildren != that.FitChildren {
		return false
	}
	return true
}

func (this *Length_Fill) EqualVT(thatIface isLength_Value) bool {
	that, ok := thatIface.(*Length_Fill)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if this.Fill != that.Fill {
		return false
	}
	return true
}

func (this *Edges) EqualVT(that *Edges) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Top != that.Top {
		return false
	}
	if this.Right != that.Right {
		return false
	}
	if this.Bottom != that.Bottom {
		return false
	}
	if this.Left != that.Left {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Edges) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*Edges)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *Change) EqualVT(that *Change) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Reset_ != that.Reset_ {
		return false
	}
	if !protobuf_go_lite.EqualVTSliceImplicit(this.Set, that.Set, func() *Node { return &Node{} }) {
		return false
	}
	if !protobuf_go_lite.EqualSlice(this.Removed, that.Removed) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Change) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*Change)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *Tree) EqualVT(that *Tree) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Mod != that.Mod {
		return false
	}
	if !protobuf_go_lite.EqualVTSliceImplicit(this.Nodes, that.Nodes, func() *Node { return &Node{} }) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Tree) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*Tree)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *Screen) EqualVT(that *Screen) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.EqualVTSliceImplicit(this.Trees, that.Trees, func() *Tree { return &Tree{} }) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Screen) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*Screen)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

// MarshalProtoJSON marshals the Kind to JSON.
func (x Kind) MarshalProtoJSON(s *json.MarshalState) {
	s.WriteEnum(int32(x), Kind_name)
}

// MarshalText marshals the Kind to text.
func (x Kind) MarshalText() ([]byte, error) {
	return []byte(json.GetEnumString(int32(x), Kind_name)), nil
}

// MarshalJSON marshals the Kind to JSON.
func (x Kind) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the Kind from JSON.
func (x *Kind) UnmarshalProtoJSON(s *json.UnmarshalState) {
	v := s.ReadEnum(Kind_value)
	if err := s.Err(); err != nil {
		s.SetErrorf("could not read Kind enum: %v", err)
		return
	}
	*x = Kind(v)
}

// UnmarshalText unmarshals the Kind from text.
func (x *Kind) UnmarshalText(b []byte) error {
	i, err := json.ParseEnumString(string(b), Kind_value)
	if err != nil {
		return err
	}
	*x = Kind(i)
	return nil
}

// UnmarshalJSON unmarshals the Kind from JSON.
func (x *Kind) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the Flow to JSON.
func (x Flow) MarshalProtoJSON(s *json.MarshalState) {
	s.WriteEnum(int32(x), Flow_name)
}

// MarshalText marshals the Flow to text.
func (x Flow) MarshalText() ([]byte, error) {
	return []byte(json.GetEnumString(int32(x), Flow_name)), nil
}

// MarshalJSON marshals the Flow to JSON.
func (x Flow) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the Flow from JSON.
func (x *Flow) UnmarshalProtoJSON(s *json.UnmarshalState) {
	v := s.ReadEnum(Flow_value)
	if err := s.Err(); err != nil {
		s.SetErrorf("could not read Flow enum: %v", err)
		return
	}
	*x = Flow(v)
}

// UnmarshalText unmarshals the Flow from text.
func (x *Flow) UnmarshalText(b []byte) error {
	i, err := json.ParseEnumString(string(b), Flow_value)
	if err != nil {
		return err
	}
	*x = Flow(i)
	return nil
}

// UnmarshalJSON unmarshals the Flow from JSON.
func (x *Flow) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the Align to JSON.
func (x Align) MarshalProtoJSON(s *json.MarshalState) {
	s.WriteEnum(int32(x), Align_name)
}

// MarshalText marshals the Align to text.
func (x Align) MarshalText() ([]byte, error) {
	return []byte(json.GetEnumString(int32(x), Align_name)), nil
}

// MarshalJSON marshals the Align to JSON.
func (x Align) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the Align from JSON.
func (x *Align) UnmarshalProtoJSON(s *json.UnmarshalState) {
	v := s.ReadEnum(Align_value)
	if err := s.Err(); err != nil {
		s.SetErrorf("could not read Align enum: %v", err)
		return
	}
	*x = Align(v)
}

// UnmarshalText unmarshals the Align from text.
func (x *Align) UnmarshalText(b []byte) error {
	i, err := json.ParseEnumString(string(b), Align_value)
	if err != nil {
		return err
	}
	*x = Align(i)
	return nil
}

// UnmarshalJSON unmarshals the Align from JSON.
func (x *Align) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the Node message to JSON.
func (x *Node) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Id != "" || s.HasField("id") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("id")
		s.WriteString(x.Id)
	}
	if x.Kind != 0 || s.HasField("kind") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("kind")
		x.Kind.MarshalProtoJSON(s)
	}
	if len(x.Children) > 0 || s.HasField("children") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("children")
		s.WriteStringArray(x.Children)
	}
	if x.Text != "" || s.HasField("text") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("text")
		s.WriteString(x.Text)
	}
	if x.Image != "" || s.HasField("image") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("image")
		s.WriteString(x.Image)
	}
	if x.Style != nil || s.HasField("style") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("style")
		x.Style.MarshalProtoJSON(s.WithField("style"))
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the Node to JSON.
func (x *Node) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the Node message from JSON.
func (x *Node) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "id":
			s.AddField("id")
			x.Id = s.ReadString()
		case "kind":
			s.AddField("kind")
			x.Kind.UnmarshalProtoJSON(s)
		case "children":
			s.AddField("children")
			if s.ReadNil() {
				x.Children = nil
				return
			}
			x.Children = s.ReadStringArray()
		case "text":
			s.AddField("text")
			x.Text = s.ReadString()
		case "image":
			s.AddField("image")
			x.Image = s.ReadString()
		case "style":
			if s.ReadNil() {
				x.Style = nil
				return
			}
			x.Style = &Style{}
			x.Style.UnmarshalProtoJSON(s.WithField("style", true))
		}
	})
}

// UnmarshalJSON unmarshals the Node from JSON.
func (x *Node) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the Style message to JSON.
func (x *Style) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Width != nil || s.HasField("width") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("width")
		x.Width.MarshalProtoJSON(s.WithField("width"))
	}
	if x.Height != nil || s.HasField("height") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("height")
		x.Height.MarshalProtoJSON(s.WithField("height"))
	}
	if x.Flow != 0 || s.HasField("flow") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("flow")
		x.Flow.MarshalProtoJSON(s)
	}
	if x.HorizontalAlign != 0 || s.HasField("horizontalAlign") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("horizontalAlign")
		x.HorizontalAlign.MarshalProtoJSON(s)
	}
	if x.VerticalAlign != 0 || s.HasField("verticalAlign") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("verticalAlign")
		x.VerticalAlign.MarshalProtoJSON(s)
	}
	if x.Margin != nil || s.HasField("margin") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("margin")
		x.Margin.MarshalProtoJSON(s.WithField("margin"))
	}
	if x.Padding != nil || s.HasField("padding") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("padding")
		x.Padding.MarshalProtoJSON(s.WithField("padding"))
	}
	if x.Background != 0 || s.HasField("background") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("background")
		s.WriteUint32(x.Background)
	}
	if x.Color != 0 || s.HasField("color") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("color")
		s.WriteUint32(x.Color)
	}
	if x.FontSize != 0 || s.HasField("fontSize") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("fontSize")
		s.WriteFloat32(x.FontSize)
	}
	if x.Bold || s.HasField("bold") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("bold")
		s.WriteBool(x.Bold)
	}
	if x.TextAlign != 0 || s.HasField("textAlign") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("textAlign")
		x.TextAlign.MarshalProtoJSON(s)
	}
	if x.BorderRadius != 0 || s.HasField("borderRadius") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("borderRadius")
		s.WriteFloat32(x.BorderRadius)
	}
	if x.Opacity != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("opacity")
		s.WriteFloat32(*x.Opacity)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the Style to JSON.
func (x *Style) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the Style message from JSON.
func (x *Style) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "width":
			if s.ReadNil() {
				x.Width = nil
				return
			}
			x.Width = &Length{}
			x.Width.UnmarshalProtoJSON(s.WithField("width", true))
		case "height":
			if s.ReadNil() {
				x.Height = nil
				return
			}
			x.Height = &Length{}
			x.Height.UnmarshalProtoJSON(s.WithField("height", true))
		case "flow":
			s.AddField("flow")
			x.Flow.UnmarshalProtoJSON(s)
		case "horizontal_align", "horizontalAlign":
			s.AddField("horizontal_align")
			x.HorizontalAlign.UnmarshalProtoJSON(s)
		case "vertical_align", "verticalAlign":
			s.AddField("vertical_align")
			x.VerticalAlign.UnmarshalProtoJSON(s)
		case "margin":
			if s.ReadNil() {
				x.Margin = nil
				return
			}
			x.Margin = &Edges{}
			x.Margin.UnmarshalProtoJSON(s.WithField("margin", true))
		case "padding":
			if s.ReadNil() {
				x.Padding = nil
				return
			}
			x.Padding = &Edges{}
			x.Padding.UnmarshalProtoJSON(s.WithField("padding", true))
		case "background":
			s.AddField("background")
			x.Background = s.ReadUint32()
		case "color":
			s.AddField("color")
			x.Color = s.ReadUint32()
		case "font_size", "fontSize":
			s.AddField("font_size")
			x.FontSize = s.ReadFloat32()
		case "bold":
			s.AddField("bold")
			x.Bold = s.ReadBool()
		case "text_align", "textAlign":
			s.AddField("text_align")
			x.TextAlign.UnmarshalProtoJSON(s)
		case "border_radius", "borderRadius":
			s.AddField("border_radius")
			x.BorderRadius = s.ReadFloat32()
		case "opacity":
			s.AddField("opacity")
			if s.ReadNil() {
				x.Opacity = nil
				return
			}
			t := s.ReadFloat32()
			x.Opacity = &t
		}
	})
}

// UnmarshalJSON unmarshals the Style from JSON.
func (x *Style) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the Length message to JSON.
func (x *Length) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Value != nil {
		switch ov := x.Value.(type) {
		case *Length_Pixels:
			s.WriteMoreIf(&wroteField)
			s.WriteObjectField("pixels")
			s.WriteFloat32(ov.Pixels)
		case *Length_Percent:
			s.WriteMoreIf(&wroteField)
			s.WriteObjectField("percent")
			s.WriteFloat32(ov.Percent)
		case *Length_FitChildren:
			s.WriteMoreIf(&wroteField)
			s.WriteObjectField("fitChildren")
			s.WriteBool(ov.FitChildren)
		case *Length_Fill:
			s.WriteMoreIf(&wroteField)
			s.WriteObjectField("fill")
			s.WriteFloat32(ov.Fill)
		}
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the Length to JSON.
func (x *Length) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the Length message from JSON.
func (x *Length) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "pixels":
			s.AddField("pixels")
			ov := &Length_Pixels{}
			x.Value = ov
			ov.Pixels = s.ReadFloat32()
		case "percent":
			s.AddField("percent")
			ov := &Length_Percent{}
			x.Value = ov
			ov.Percent = s.ReadFloat32()
		case "fit_children", "fitChildren":
			s.AddField("fit_children")
			ov := &Length_FitChildren{}
			x.Value = ov
			ov.FitChildren = s.ReadBool()
		case "fill":
			s.AddField("fill")
			ov := &Length_Fill{}
			x.Value = ov
			ov.Fill = s.ReadFloat32()
		}
	})
}

// UnmarshalJSON unmarshals the Length from JSON.
func (x *Length) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the Edges message to JSON.
func (x *Edges) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Top != 0 || s.HasField("top") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("top")
		s.WriteFloat32(x.Top)
	}
	if x.Right != 0 || s.HasField("right") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("right")
		s.WriteFloat32(x.Right)
	}
	if x.Bottom != 0 || s.HasField("bottom") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("bottom")
		s.WriteFloat32(x.Bottom)
	}
	if x.Left != 0 || s.HasField("left") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("left")
		s.WriteFloat32(x.Left)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the Edges to JSON.
func (x *Edges) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the Edges message from JSON.
func (x *Edges) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "top":
			s.AddField("top")
			x.Top = s.ReadFloat32()
		case "right":
			s.AddField("right")
			x.Right = s.ReadFloat32()
		case "bottom":
			s.AddField("bottom")
			x.Bottom = s.ReadFloat32()
		case "left":
			s.AddField("left")
			x.Left = s.ReadFloat32()
		}
	})
}

// UnmarshalJSON unmarshals the Edges from JSON.
func (x *Edges) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the Change message to JSON.
func (x *Change) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Reset_ || s.HasField("reset") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("reset")
		s.WriteBool(x.Reset_)
	}
	if len(x.Set) > 0 || s.HasField("set") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("set")
		s.WriteArrayStart()
		var wroteElement bool
		for _, element := range x.Set {
			s.WriteMoreIf(&wroteElement)
			element.MarshalProtoJSON(s.WithField("set"))
		}
		s.WriteArrayEnd()
	}
	if len(x.Removed) > 0 || s.HasField("removed") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("removed")
		s.WriteStringArray(x.Removed)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the Change to JSON.
func (x *Change) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the Change message from JSON.
func (x *Change) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "reset":
			s.AddField("reset")
			x.Reset_ = s.ReadBool()
		case "set":
			s.AddField("set")
			if s.ReadNil() {
				x.Set = nil
				return
			}
			s.ReadArray(func() {
				if s.ReadNil() {
					x.Set = append(x.Set, nil)
					return
				}
				v := &Node{}
				v.UnmarshalProtoJSON(s.WithField("set", false))
				if s.Err() != nil {
					return
				}
				x.Set = append(x.Set, v)
			})
		case "removed":
			s.AddField("removed")
			if s.ReadNil() {
				x.Removed = nil
				return
			}
			x.Removed = s.ReadStringArray()
		}
	})
}

// UnmarshalJSON unmarshals the Change from JSON.
func (x *Change) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the Tree message to JSON.
func (x *Tree) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Mod != "" || s.HasField("mod") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("mod")
		s.WriteString(x.Mod)
	}
	if len(x.Nodes) > 0 || s.HasField("nodes") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("nodes")
		s.WriteArrayStart()
		var wroteElement bool
		for _, element := range x.Nodes {
			s.WriteMoreIf(&wroteElement)
			element.MarshalProtoJSON(s.WithField("nodes"))
		}
		s.WriteArrayEnd()
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the Tree to JSON.
func (x *Tree) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the Tree message from JSON.
func (x *Tree) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "mod":
			s.AddField("mod")
			x.Mod = s.ReadString()
		case "nodes":
			s.AddField("nodes")
			if s.ReadNil() {
				x.Nodes = nil
				return
			}
			s.ReadArray(func() {
				if s.ReadNil() {
					x.Nodes = append(x.Nodes, nil)
					return
				}
				v := &Node{}
				v.UnmarshalProtoJSON(s.WithField("nodes", false))
				if s.Err() != nil {
					return
				}
				x.Nodes = append(x.Nodes, v)
			})
		}
	})
}

// UnmarshalJSON unmarshals the Tree from JSON.
func (x *Tree) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the Screen message to JSON.
func (x *Screen) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if len(x.Trees) > 0 || s.HasField("trees") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("trees")
		s.WriteArrayStart()
		var wroteElement bool
		for _, element := range x.Trees {
			s.WriteMoreIf(&wroteElement)
			element.MarshalProtoJSON(s.WithField("trees"))
		}
		s.WriteArrayEnd()
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the Screen to JSON.
func (x *Screen) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the Screen message from JSON.
func (x *Screen) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "trees":
			s.AddField("trees")
			if s.ReadNil() {
				x.Trees = nil
				return
			}
			s.ReadArray(func() {
				if s.ReadNil() {
					x.Trees = append(x.Trees, nil)
					return
				}
				v := &Tree{}
				v.UnmarshalProtoJSON(s.WithField("trees", false))
				if s.Err() != nil {
					return
				}
				x.Trees = append(x.Trees, v)
			})
		}
	})
}

// UnmarshalJSON unmarshals the Screen from JSON.
func (x *Screen) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

func (m *Node) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Node) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Node) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.Style != nil {
		size, err := m.Style.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Image) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.Image)
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Text) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.Text)
		i--
		dAtA[i] = 0x22
	}
	if len(m.Children) > 0 {
		for iNdEx := len(m.Children) - 1; iNdEx >= 0; iNdEx-- {
			i = protobuf_go_lite.EncodeString(dAtA, i, m.Children[iNdEx])
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.Kind != 0 {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(m.Kind))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Id) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.Id)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Style) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Style) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Style) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.Opacity != nil {
		i = protobuf_go_lite.EncodeFixed32(dAtA, i, uint32(math.Float32bits(float32(*m.Opacity))))
		i--
		dAtA[i] = 0x75
	}
	if m.BorderRadius != 0 {
		i = protobuf_go_lite.EncodeFixed32(dAtA, i, uint32(math.Float32bits(float32(m.BorderRadius))))
		i--
		dAtA[i] = 0x6d
	}
	if m.TextAlign != 0 {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(m.TextAlign))
		i--
		dAtA[i] = 0x60
	}
	if m.Bold {
		i = protobuf_go_lite.EncodeBool(dAtA, i, m.Bold)
		i--
		dAtA[i] = 0x58
	}
	if m.FontSize != 0 {
		i = protobuf_go_lite.EncodeFixed32(dAtA, i, uint32(math.Float32bits(float32(m.FontSize))))
		i--
		dAtA[i] = 0x55
	}
	if m.Color != 0 {
		i = protobuf_go_lite.EncodeFixed32(dAtA, i, uint32(m.Color))
		i--
		dAtA[i] = 0x4d
	}
	if m.Background != 0 {
		i = protobuf_go_lite.EncodeFixed32(dAtA, i, uint32(m.Background))
		i--
		dAtA[i] = 0x45
	}
	if m.Padding != nil {
		size, err := m.Padding.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x3a
	}
	if m.Margin != nil {
		size, err := m.Margin.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x32
	}
	if m.VerticalAlign != 0 {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(m.VerticalAlign))
		i--
		dAtA[i] = 0x28
	}
	if m.HorizontalAlign != 0 {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(m.HorizontalAlign))
		i--
		dAtA[i] = 0x20
	}
	if m.Flow != 0 {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(m.Flow))
		i--
		dAtA[i] = 0x18
	}
	if m.Height != nil {
		size, err := m.Height.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x12
	}
	if m.Width != nil {
		size, err := m.Width.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Length) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Length) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Length) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if vtmsg, ok := m.Value.(interface {
		MarshalToSizedBufferVT([]byte) (int, error)
	}); ok {
		size, err := vtmsg.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
	}
	return len(dAtA) - i, nil
}

func (m *Length_Pixels) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Length_Pixels) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = protobuf_go_lite.EncodeFixed32(dAtA, i, uint32(math.Float32bits(float32(m.Pixels))))
	i--
	dAtA[i] = 0xd
	return len(dAtA) - i, nil
}
func (m *Length_Percent) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Length_Percent) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = protobuf_go_lite.EncodeFixed32(dAtA, i, uint32(math.Float32bits(float32(m.Percent))))
	i--
	dAtA[i] = 0x15
	return len(dAtA) - i, nil
}
func (m *Length_FitChildren) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Length_FitChildren) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = protobuf_go_lite.EncodeBool(dAtA, i, m.FitChildren)
	i--
	dAtA[i] = 0x18
	return len(dAtA) - i, nil
}
func (m *Length_Fill) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Length_Fill) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = protobuf_go_lite.EncodeFixed32(dAtA, i, uint32(math.Float32bits(float32(m.Fill))))
	i--
	dAtA[i] = 0x25
	return len(dAtA) - i, nil
}
func (m *Edges) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Edges) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Edges) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.Left != 0 {
		i = protobuf_go_lite.EncodeFixed32(dAtA, i, uint32(math.Float32bits(float32(m.Left))))
		i--
		dAtA[i] = 0x25
	}
	if m.Bottom != 0 {
		i = protobuf_go_lite.EncodeFixed32(dAtA, i, uint32(math.Float32bits(float32(m.Bottom))))
		i--
		dAtA[i] = 0x1d
	}
	if m.Right != 0 {
		i = protobuf_go_lite.EncodeFixed32(dAtA, i, uint32(math.Float32bits(float32(m.Right))))
		i--
		dAtA[i] = 0x15
	}
	if m.Top != 0 {
		i = protobuf_go_lite.EncodeFixed32(dAtA, i, uint32(math.Float32bits(float32(m.Top))))
		i--
		dAtA[i] = 0xd
	}
	return len(dAtA) - i, nil
}

func (m *Change) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Change) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Change) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if len(m.Removed) > 0 {
		for iNdEx := len(m.Removed) - 1; iNdEx >= 0; iNdEx-- {
			i = protobuf_go_lite.EncodeString(dAtA, i, m.Removed[iNdEx])
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Set) > 0 {
		for iNdEx := len(m.Set) - 1; iNdEx >= 0; iNdEx-- {
			size, err := m.Set[iNdEx].MarshalToSizedBufferVT(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Reset_ {
		i = protobuf_go_lite.EncodeBool(dAtA, i, m.Reset_)
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Tree) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Tree) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Tree) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if len(m.Nodes) > 0 {
		for iNdEx := len(m.Nodes) - 1; iNdEx >= 0; iNdEx-- {
			size, err := m.Nodes[iNdEx].MarshalToSizedBufferVT(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Mod) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.Mod)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Screen) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Screen) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Screen) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if len(m.Trees) > 0 {
		for iNdEx := len(m.Trees) - 1; iNdEx >= 0; iNdEx-- {
			size, err := m.Trees[iNdEx].MarshalToSizedBufferVT(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Node) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.Id)
	n += protobuf_go_lite.SizeVarintNonZero(1, m.Kind)
	n += protobuf_go_lite.SizeStringSlice(1, m.Children)
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.Text)
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.Image)
	if m.Style != nil {
		l = m.Style.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	n += len(m.unknownFields)
	return n
}

func (m *Style) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Width != nil {
		l = m.Width.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	if m.Height != nil {
		l = m.Height.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	n += protobuf_go_lite.SizeVarintNonZero(1, m.Flow)
	n += protobuf_go_lite.SizeVarintNonZero(1, m.HorizontalAlign)
	n += protobuf_go_lite.SizeVarintNonZero(1, m.VerticalAlign)
	if m.Margin != nil {
		l = m.Margin.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	if m.Padding != nil {
		l = m.Padding.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	n += protobuf_go_lite.SizeFixed32NonZero(1, m.Background)
	n += protobuf_go_lite.SizeFixed32NonZero(1, m.Color)
	n += protobuf_go_lite.SizeFixed32NonZero(1, m.FontSize)
	n += protobuf_go_lite.SizeBoolNonZero(1, m.Bold)
	n += protobuf_go_lite.SizeVarintNonZero(1, m.TextAlign)
	n += protobuf_go_lite.SizeFixed32NonZero(1, m.BorderRadius)
	n += protobuf_go_lite.SizeFixed32Ptr(1, m.Opacity)
	n += len(m.unknownFields)
	return n
}

func (m *Length) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if vtmsg, ok := m.Value.(interface{ SizeVT() int }); ok {
		n += vtmsg.SizeVT()
	}
	n += len(m.unknownFields)
	return n
}

func (m *Length_Pixels) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeFixed32Value(1)
	return n
}
func (m *Length_Percent) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeFixed32Value(1)
	return n
}
func (m *Length_FitChildren) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeBoolValue(1)
	return n
}
func (m *Length_Fill) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeFixed32Value(1)
	return n
}
func (m *Edges) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeFixed32NonZero(1, m.Top)
	n += protobuf_go_lite.SizeFixed32NonZero(1, m.Right)
	n += protobuf_go_lite.SizeFixed32NonZero(1, m.Bottom)
	n += protobuf_go_lite.SizeFixed32NonZero(1, m.Left)
	n += len(m.unknownFields)
	return n
}

func (m *Change) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeBoolNonZero(1, m.Reset_)
	for _, e := range m.Set {
		l = e.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	n += protobuf_go_lite.SizeStringSlice(1, m.Removed)
	n += len(m.unknownFields)
	return n
}

func (m *Tree) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.Mod)
	for _, e := range m.Nodes {
		l = e.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	n += len(m.unknownFields)
	return n
}

func (m *Screen) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	for _, e := range m.Trees {
		l = e.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	n += len(m.unknownFields)
	return n
}

func (x Kind) MarshalProtoText() string {
	return x.String()
}
func (x Flow) MarshalProtoText() string {
	return x.String()
}
func (x Align) MarshalProtoText() string {
	return x.String()
}
func (x *Node) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "Node")
	if x.Id != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "id")
		protobuf_go_lite.TextWriteString(&sb, x.Id)
	}
	if x.Kind != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "kind")
		protobuf_go_lite.TextWriteStringer(&sb, Kind(x.Kind))
	}
	if len(x.Children) > 0 {
		protobuf_go_lite.TextWriteListStart(&sb, initialLen, "children")
		for i, v := range x.Children {
			protobuf_go_lite.TextWriteListSeparator(&sb, i)
			protobuf_go_lite.TextWriteString(&sb, v)
		}
		protobuf_go_lite.TextWriteListEnd(&sb)
	}
	if x.Text != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "text")
		protobuf_go_lite.TextWriteString(&sb, x.Text)
	}
	if x.Image != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "image")
		protobuf_go_lite.TextWriteString(&sb, x.Image)
	}
	if x.Style != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "style")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.Style)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *Node) String() string {
	return x.MarshalProtoText()
}
func (x *Style) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "Style")
	if x.Width != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "width")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.Width)
	}
	if x.Height != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "height")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.Height)
	}
	if x.Flow != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "flow")
		protobuf_go_lite.TextWriteStringer(&sb, Flow(x.Flow))
	}
	if x.HorizontalAlign != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "horizontal_align")
		protobuf_go_lite.TextWriteStringer(&sb, Align(x.HorizontalAlign))
	}
	if x.VerticalAlign != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "vertical_align")
		protobuf_go_lite.TextWriteStringer(&sb, Align(x.VerticalAlign))
	}
	if x.Margin != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "margin")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.Margin)
	}
	if x.Padding != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "padding")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.Padding)
	}
	if x.Background != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "background")
		protobuf_go_lite.TextWriteUint(&sb, x.Background)
	}
	if x.Color != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "color")
		protobuf_go_lite.TextWriteUint(&sb, x.Color)
	}
	if x.FontSize != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "font_size")
		protobuf_go_lite.TextWriteFloat32(&sb, x.FontSize)
	}
	if x.Bold != false {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "bold")
		protobuf_go_lite.TextWriteBool(&sb, x.Bold)
	}
	if x.TextAlign != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "text_align")
		protobuf_go_lite.TextWriteStringer(&sb, Align(x.TextAlign))
	}
	if x.BorderRadius != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "border_radius")
		protobuf_go_lite.TextWriteFloat32(&sb, x.BorderRadius)
	}
	if x.Opacity != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "opacity")
		protobuf_go_lite.TextWriteFloat32(&sb, *x.Opacity)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *Style) String() string {
	return x.MarshalProtoText()
}
func (x *Length) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "Length")
	switch body := x.Value.(type) {
	case *Length_Pixels:
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "pixels")
		protobuf_go_lite.TextWriteFloat32(&sb, body.Pixels)
	case *Length_Percent:
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "percent")
		protobuf_go_lite.TextWriteFloat32(&sb, body.Percent)
	case *Length_FitChildren:
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "fit_children")
		protobuf_go_lite.TextWriteBool(&sb, body.FitChildren)
	case *Length_Fill:
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "fill")
		protobuf_go_lite.TextWriteFloat32(&sb, body.Fill)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *Length) String() string {
	return x.MarshalProtoText()
}
func (x *Edges) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "Edges")
	if x.Top != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "top")
		protobuf_go_lite.TextWriteFloat32(&sb, x.Top)
	}
	if x.Right != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "right")
		protobuf_go_lite.TextWriteFloat32(&sb, x.Right)
	}
	if x.Bottom != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "bottom")
		protobuf_go_lite.TextWriteFloat32(&sb, x.Bottom)
	}
	if x.Left != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "left")
		protobuf_go_lite.TextWriteFloat32(&sb, x.Left)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *Edges) String() string {
	return x.MarshalProtoText()
}
func (x *Change) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "Change")
	if x.Reset_ != false {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "reset")
		protobuf_go_lite.TextWriteBool(&sb, x.Reset_)
	}
	if len(x.Set) > 0 {
		protobuf_go_lite.TextWriteListStart(&sb, initialLen, "set")
		for i, v := range x.Set {
			protobuf_go_lite.TextWriteListSeparator(&sb, i)
			if v == nil {
				protobuf_go_lite.TextWriteTextMarshaler(&sb, &Node{})
			} else {
				protobuf_go_lite.TextWriteTextMarshaler(&sb, v)
			}
		}
		protobuf_go_lite.TextWriteListEnd(&sb)
	}
	if len(x.Removed) > 0 {
		protobuf_go_lite.TextWriteListStart(&sb, initialLen, "removed")
		for i, v := range x.Removed {
			protobuf_go_lite.TextWriteListSeparator(&sb, i)
			protobuf_go_lite.TextWriteString(&sb, v)
		}
		protobuf_go_lite.TextWriteListEnd(&sb)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *Change) String() string {
	return x.MarshalProtoText()
}
func (x *Tree) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "Tree")
	if x.Mod != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "mod")
		protobuf_go_lite.TextWriteString(&sb, x.Mod)
	}
	if len(x.Nodes) > 0 {
		protobuf_go_lite.TextWriteListStart(&sb, initialLen, "nodes")
		for i, v := range x.Nodes {
			protobuf_go_lite.TextWriteListSeparator(&sb, i)
			if v == nil {
				protobuf_go_lite.TextWriteTextMarshaler(&sb, &Node{})
			} else {
				protobuf_go_lite.TextWriteTextMarshaler(&sb, v)
			}
		}
		protobuf_go_lite.TextWriteListEnd(&sb)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *Tree) String() string {
	return x.MarshalProtoText()
}
func (x *Screen) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "Screen")
	if len(x.Trees) > 0 {
		protobuf_go_lite.TextWriteListStart(&sb, initialLen, "trees")
		for i, v := range x.Trees {
			protobuf_go_lite.TextWriteListSeparator(&sb, i)
			if v == nil {
				protobuf_go_lite.TextWriteTextMarshaler(&sb, &Tree{})
			} else {
				protobuf_go_lite.TextWriteTextMarshaler(&sb, v)
			}
		}
		protobuf_go_lite.TextWriteListEnd(&sb)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *Screen) String() string {
	return x.MarshalProtoText()
}
func (m *Node) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Node: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Node: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Id = v
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Kind", wireType)
			}
			m.Kind = 0
			var _v uint64
			_v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			m.Kind = Kind(_v)
			if err != nil {
				return err
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Children", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Children = append(m.Children, v)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Text", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Text = v
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Image", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Image = v
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Style", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.Style == nil {
				m.Style = &Style{}
			}
			if err := m.Style.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Style) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Style: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Style: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Width", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.Width == nil {
				m.Width = &Length{}
			}
			if err := m.Width.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.Height == nil {
				m.Height = &Length{}
			}
			if err := m.Height.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Flow", wireType)
			}
			m.Flow = 0
			var _v uint64
			_v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			m.Flow = Flow(_v)
			if err != nil {
				return err
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HorizontalAlign", wireType)
			}
			m.HorizontalAlign = 0
			var _v uint64
			_v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			m.HorizontalAlign = Align(_v)
			if err != nil {
				return err
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerticalAlign", wireType)
			}
			m.VerticalAlign = 0
			var _v uint64
			_v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			m.VerticalAlign = Align(_v)
			if err != nil {
				return err
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Margin", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.Margin == nil {
				m.Margin = &Edges{}
			}
			if err := m.Margin.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Padding", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.Padding == nil {
				m.Padding = &Edges{}
			}
			if err := m.Padding.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Background", wireType)
			}
			m.Background = 0
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Background = uint32(_v32)
		case 9:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Color", wireType)
			}
			m.Color = 0
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Color = uint32(_v32)
		case 10:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field FontSize", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			m.FontSize = float32(math.Float32frombits(v))
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bold", wireType)
			}
			var v bool
			v, iNdEx, err = protobuf_go_lite.DecodeVarintBool(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Bold = bool(v)
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TextAlign", wireType)
			}
			m.TextAlign = 0
			var _v uint64
			_v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			m.TextAlign = Align(_v)
			if err != nil {
				return err
			}
		case 13:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field BorderRadius", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			m.BorderRadius = float32(math.Float32frombits(v))
		case 14:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Opacity", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			v2 := float32(math.Float32frombits(v))
			m.Opacity = &v2
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Length) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Length: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Length: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pixels", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			m.Value = &Length_Pixels{Pixels: float32(math.Float32frombits(v))}
		case 2:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Percent", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			m.Value = &Length_Percent{Percent: float32(math.Float32frombits(v))}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FitChildren", wireType)
			}
			var v bool
			v, iNdEx, err = protobuf_go_lite.DecodeVarintBool(dAtA, iNdEx)
			if err != nil {
				return err
			}
			b := bool(v)
			m.Value = &Length_FitChildren{FitChildren: b}
		case 4:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fill", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			m.Value = &Length_Fill{Fill: float32(math.Float32frombits(v))}
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Edges) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Edges: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Edges: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Top", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			m.Top = float32(math.Float32frombits(v))
		case 2:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Right", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			m.Right = float32(math.Float32frombits(v))
		case 3:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bottom", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			m.Bottom = float32(math.Float32frombits(v))
		case 4:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Left", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			m.Left = float32(math.Float32frombits(v))
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Change) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Change: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Change: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reset_", wireType)
			}
			var v bool
			v, iNdEx, err = protobuf_go_lite.DecodeVarintBool(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Reset_ = bool(v)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Set", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Set = append(m.Set, &Node{})
			if err := m.Set[len(m.Set)-1].UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Removed", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Removed = append(m.Removed, v)
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Tree) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Tree: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Tree: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mod", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Mod = v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nodes", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Nodes = append(m.Nodes, &Node{})
			if err := m.Nodes[len(m.Nodes)-1].UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Screen) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Screen: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Screen: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Trees", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Trees = append(m.Trees, &Tree{})
			if err := m.Trees[len(m.Trees)-1].UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
