// Code generated by protoc-gen-go-lite. DO NOT EDIT.
// protoc-gen-go-lite version: v0.17.0
// source: github.com/paralin/modlock/proto/modlock/cli/cli.proto

package cli

import (
	fmt "fmt"
	io "io"
	slices "slices"

	protobuf_go_lite "github.com/aperturerobotics/protobuf-go-lite"
	json "github.com/aperturerobotics/protobuf-go-lite/json"
	control "github.com/paralin/modlock/proto/modlock/control"
	publish "github.com/paralin/modlock/proto/modlock/publish"
)

// Event is one thing the command line did or saw.
type Event struct {
	unknownFields []byte
	// Body selects the event.
	//
	// Types that are assignable to Body:
	//
	//	*Event_Note
	//	*Event_Building
	//	*Event_Built
	//	*Event_Host
	//	*Event_Published
	//	*Event_Sandbox
	Body isEvent_Body `protobuf_oneof:"body"`
}

func (x *Event) Reset() {
	*x = Event{}
}

func (*Event) ProtoMessage() {}

func (m *Event) GetBody() isEvent_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *Event) GetNote() string {
	if x, ok := x.GetBody().(*Event_Note); ok {
		return x.Note
	}
	return ""
}

func (x *Event) GetBuilding() *Building {
	if x, ok := x.GetBody().(*Event_Building); ok {
		return x.Building
	}
	return nil
}

func (x *Event) GetBuilt() *Built {
	if x, ok := x.GetBody().(*Event_Built); ok {
		return x.Built
	}
	return nil
}

func (x *Event) GetHost() *control.HostEvent {
	if x, ok := x.GetBody().(*Event_Host); ok {
		return x.Host
	}
	return nil
}

func (x *Event) GetPublished() *Published {
	if x, ok := x.GetBody().(*Event_Published); ok {
		return x.Published
	}
	return nil
}

func (x *Event) GetSandbox() *Sandbox {
	if x, ok := x.GetBody().(*Event_Sandbox); ok {
		return x.Sandbox
	}
	return nil
}

type isEvent_Body interface {
	isEvent_Body()
}

type Event_Note struct {
	// Note is a line of progress for the creator.
	Note string `protobuf:"bytes,1,opt,name=note,proto3,oneof"`
}

type Event_Building struct {
	// Building reports that a build of the project started.
	Building *Building `protobuf:"bytes,2,opt,name=building,proto3,oneof"`
}

type Event_Built struct {
	// Built reports a finished build.
	Built *Built `protobuf:"bytes,3,opt,name=built,proto3,oneof"`
}

type Event_Host struct {
	// Host carries an event from the running server.
	Host *control.HostEvent `protobuf:"bytes,4,opt,name=host,proto3,oneof"`
}

type Event_Published struct {
	// Published reports a release the provider recorded.
	Published *Published `protobuf:"bytes,5,opt,name=published,proto3,oneof"`
}

type Event_Sandbox struct {
	// Sandbox reports that the session runs the mods in the sandbox, without
	// the game, and why.
	Sandbox *Sandbox `protobuf:"bytes,6,opt,name=sandbox,proto3,oneof"`
}

func (*Event_Note) isEvent_Body() {}

func (*Event_Building) isEvent_Body() {}

func (*Event_Built) isEvent_Body() {}

func (*Event_Host) isEvent_Body() {}

func (*Event_Published) isEvent_Body() {}

func (*Event_Sandbox) isEvent_Body() {}

// Building identifies the project a build started for.
type Building struct {
	unknownFields []byte
	// Dir is the project directory.
	Dir string `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`
}

func (x *Building) Reset() {
	*x = Building{}
}

func (*Building) ProtoMessage() {}

func (x *Building) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

// Built reports a finished build. A failed build leaves the previous built mod
// in place.
type Built struct {
	unknownFields []byte
	// Dir is the project directory.
	Dir string `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`
	// Ok is true when the build wrote the built mod.
	Ok bool `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	// Error explains a failed build in one line.
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// Diagnostics lists the problems the checks and compilers found. A finished
	// build replaces the previous build's diagnostics.
	Diagnostics []*Diagnostic `protobuf:"bytes,4,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
}

func (x *Built) Reset() {
	*x = Built{}
}

func (*Built) ProtoMessage() {}

func (x *Built) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *Built) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Built) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Built) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

// Diagnostic is one problem found in a source file.
type Diagnostic struct {
	unknownFields []byte
	// File is the file's absolute path.
	File string `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	// Line is the 1-based line.
	Line uint32 `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`
	// Column is the 1-based column, zero when unknown.
	Column uint32 `protobuf:"varint,3,opt,name=column,proto3" json:"column,omitempty"`
	// Message describes the problem.
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// Source names the tool that found it: tsgo, esbuild, go vet or go build.
	Source string `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	// Code is the tool's code for the problem, such as TS2322, if it has one.
	Code string `protobuf:"bytes,6,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *Diagnostic) Reset() {
	*x = Diagnostic{}
}

func (*Diagnostic) ProtoMessage() {}

func (x *Diagnostic) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Diagnostic) GetLine() uint32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *Diagnostic) GetColumn() uint32 {
	if x != nil {
		return x.Column
	}
	return 0
}

func (x *Diagnostic) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Diagnostic) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Diagnostic) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// Sandbox reports a session in the sandbox: the mods run without the game,
// with a stand-in player who has no hero, and standard input carries the
// player's input.
type Sandbox struct {
	unknownFields []byte
	// Reason explains why the session runs in the sandbox, such as a missing
	// game.
	Reason string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *Sandbox) Reset() {
	*x = Sandbox{}
}

func (*Sandbox) ProtoMessage() {}

func (x *Sandbox) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Input is one thing the stand-in player does in the sandbox.
type Input struct {
	unknownFields []byte
	// Body selects the input.
	//
	// Types that are assignable to Body:
	//
	//	*Input_Command
	//	*Input_Press
	Body isInput_Body `protobuf_oneof:"body"`
}

func (x *Input) Reset() {
	*x = Input{}
}

func (*Input) ProtoMessage() {}

func (m *Input) GetBody() isInput_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *Input) GetCommand() string {
	if x, ok := x.GetBody().(*Input_Command); ok {
		return x.Command
	}
	return ""
}

func (x *Input) GetPress() *Press {
	if x, ok := x.GetBody().(*Input_Press); ok {
		return x.Press
	}
	return nil
}

type isInput_Body interface {
	isInput_Body()
}

type Input_Command struct {
	// Command is a line the player types in chat, such as "/hello".
	Command string `protobuf:"bytes,1,opt,name=command,proto3,oneof"`
}

type Input_Press struct {
	// Press presses a button in a mod's interface.
	Press *Press `protobuf:"bytes,2,opt,name=press,proto3,oneof"`
}

func (*Input_Command) isInput_Body() {}

func (*Input_Press) isInput_Body() {}

// Press identifies a button in the interface a mod shows a player.
type Press struct {
	unknownFields []byte
	// Mod is the mod's name.
	Mod string `protobuf:"bytes,1,opt,name=mod,proto3" json:"mod,omitempty"`
	// Slot identifies the player.
	Slot int32 `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	// Node is the button's id in the mod's tree.
	Node string `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
}

func (x *Press) Reset() {
	*x = Press{}
}

func (*Press) ProtoMessage() {}

func (x *Press) GetMod() string {
	if x != nil {
		return x.Mod
	}
	return ""
}

func (x *Press) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *Press) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

// Published reports a release.
type Published struct {
	unknownFields []byte
	// Provider is where the mod went: hyperline, archive or github.
	Provider string `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	// Release is the release hyperline.gg recorded.
	Release *publish.Release `protobuf:"bytes,2,opt,name=release,proto3" json:"release,omitempty"`
	// Location is the archive's path or the GitHub release tag.
	Location string `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *Published) Reset() {
	*x = Published{}
}

func (*Published) ProtoMessage() {}

func (x *Published) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Published) GetRelease() *publish.Release {
	if x != nil {
		return x.Release
	}
	return nil
}

func (x *Published) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (m *Event) CloneVT() *Event {
	if m == nil {
		return (*Event)(nil)
	}
	r := new(Event)
	if m.Body != nil {
		r.Body = m.Body.(interface{ CloneOneofVT() isEvent_Body }).CloneOneofVT()
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *Event) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *Event_Note) CloneVT() *Event_Note {
	if m == nil {
		return (*Event_Note)(nil)
	}
	r := new(Event_Note)
	r.Note = m.Note
	return r
}

func (m *Event_Note) CloneOneofVT() isEvent_Body {
	return m.CloneVT()
}

func (m *Event_Building) CloneVT() *Event_Building {
	if m == nil {
		return (*Event_Building)(nil)
	}
	r := new(Event_Building)
	r.Building = protobuf_go_lite.CloneVTValue(m.Building)
	return r
}

func (m *Event_Building) CloneOneofVT() isEvent_Body {
	return m.CloneVT()
}

func (m *Event_Built) CloneVT() *Event_Built {
	if m == nil {
		return (*Event_Built)(nil)
	}
	r := new(Event_Built)
	r.Built = protobuf_go_lite.CloneVTValue(m.Built)
	return r
}

func (m *Event_Built) CloneOneofVT() isEvent_Body {
	return m.CloneVT()
}

func (m *Event_Host) CloneVT() *Event_Host {
	if m == nil {
		return (*Event_Host)(nil)
	}
	r := new(Event_Host)
	r.Host = protobuf_go_lite.CloneVTValue(m.Host)
	return r
}

func (m *Event_Host) CloneOneofVT() isEvent_Body {
	return m.CloneVT()
}

func (m *Event_Published) CloneVT() *Event_Published {
	if m == nil {
		return (*Event_Published)(nil)
	}
	r := new(Event_Published)
	r.Published = protobuf_go_lite.CloneVTValue(m.Published)
	return r
}

func (m *Event_Published) CloneOneofVT() isEvent_Body {
	return m.CloneVT()
}

func (m *Event_Sandbox) CloneVT() *Event_Sandbox {
	if m == nil {
		return (*Event_Sandbox)(nil)
	}
	r := new(Event_Sandbox)
	r.Sandbox = protobuf_go_lite.CloneVTValue(m.Sandbox)
	return r
}

func (m *Event_Sandbox) CloneOneofVT() isEvent_Body {
	return m.CloneVT()
}

func (m *Building) CloneVT() *Building {
	if m == nil {
		return (*Building)(nil)
	}
	r := new(Building)
	r.Dir = m.Dir
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *Building) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *Built) CloneVT() *Built {
	if m == nil {
		return (*Built)(nil)
	}
	r := new(Built)
	r.Dir = m.Dir
	r.Ok = m.Ok
	r.Error = m.Error
	r.Diagnostics = protobuf_go_lite.CloneVTSlice(m.Diagnostics)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *Built) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *Diagnostic) CloneVT() *Diagnostic {
	if m == nil {
		return (*Diagnostic)(nil)
	}
	r := new(Diagnostic)
	r.File = m.File
	r.Line = m.Line
	r.Column = m.Column
	r.Message = m.Message
	r.Source = m.Source
	r.Code = m.Code
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *Diagnostic) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *Sandbox) CloneVT() *Sandbox {
	if m == nil {
		return (*Sandbox)(nil)
	}
	r := new(Sandbox)
	r.Reason = m.Reason
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *Sandbox) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *Input) CloneVT() *Input {
	if m == nil {
		return (*Input)(nil)
	}
	r := new(Input)
	if m.Body != nil {
		r.Body = m.Body.(interface{ CloneOneofVT() isInput_Body }).CloneOneofVT()
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *Input) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *Input_Command) CloneVT() *Input_Command {
	if m == nil {
		return (*Input_Command)(nil)
	}
	r := new(Input_Command)
	r.Command = m.Command
	return r
}

func (m *Input_Command) CloneOneofVT() isInput_Body {
	return m.CloneVT()
}

func (m *Input_Press) CloneVT() *Input_Press {
	if m == nil {
		return (*Input_Press)(nil)
	}
	r := new(Input_Press)
	r.Press = protobuf_go_lite.CloneVTValue(m.Press)
	return r
}

func (m *Input_Press) CloneOneofVT() isInput_Body {
	return m.CloneVT()
}

func (m *Press) CloneVT() *Press {
	if m == nil {
		return (*Press)(nil)
	}
	r := new(Press)
	r.Mod = m.Mod
	r.Slot = m.Slot
	r.Node = m.Node
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *Press) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *Published) CloneVT() *Published {
	if m == nil {
		return (*Published)(nil)
	}
	r := new(Published)
	r.Provider = m.Provider
	r.Location = m.Location
	r.Release = protobuf_go_lite.CloneVTValue(m.Release)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *Published) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (this *Event) EqualVT(that *Event) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Body == nil && that.Body != nil {
		return false
	} else if this.Body != nil {
		if that.Body == nil {
			return false
		}
		if !this.Body.(interface{ EqualVT(isEvent_Body) bool }).EqualVT(that.Body) {
			return false
		}
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Event) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*Event)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *Event_Note) EqualVT(thatIface isEvent_Body) bool {
	that, ok := thatIface.(*Event_Note)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if this.Note != that.Note {
		return false
	}
	return true
}

func (this *Event_Building) EqualVT(thatIface isEvent_Body) bool {
	that, ok := thatIface.(*Event_Building)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if !protobuf_go_lite.EqualVTImplicit(this.Building, that.Building, func() *Building { return &Building{} }) {
		return false
	}
	return true
}

func (this *Event_Built) EqualVT(thatIface isEvent_Body) bool {
	that, ok := thatIface.(*Event_Built)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if !protobuf_go_lite.EqualVTImplicit(this.Built, that.Built, func() *Built { return &Built{} }) {
		return false
	}
	return true
}

func (this *Event_Host) EqualVT(thatIface isEvent_Body) bool {
	that, ok := thatIface.(*Event_Host)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if !protobuf_go_lite.EqualVTImplicit(this.Host, that.Host, func() *control.HostEvent { return &control.HostEvent{} }) {
		return false
	}
	return true
}

func (this *Event_Published) EqualVT(thatIface isEvent_Body) bool {
	that, ok := thatIface.(*Event_Published)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if !protobuf_go_lite.EqualVTImplicit(this.Published, that.Published, func() *Published { return &Published{} }) {
		return false
	}
	return true
}

func (this *Event_Sandbox) EqualVT(thatIface isEvent_Body) bool {
	that, ok := thatIface.(*Event_Sandbox)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if !protobuf_go_lite.EqualVTImplicit(this.Sandbox, that.Sandbox, func() *Sandbox { return &Sandbox{} }) {
		return false
	}
	return true
}

func (this *Building) EqualVT(that *Building) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Dir != that.Dir {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Building) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*Building)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *Built) EqualVT(that *Built) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Dir != that.Dir {
		return false
	}
	if this.Ok != that.Ok {
		return false
	}
	if this.Error != that.Error {
		return false
	}
	if !protobuf_go_lite.EqualVTSliceImplicit(this.Diagnostics, that.Diagnostics, func() *Diagnostic { return &Diagnostic{} }) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Built) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*Built)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *Diagnostic) EqualVT(that *Diagnostic) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.File != that.File {
		return false
	}
	if this.Line != that.Line {
		return false
	}
	if this.Column != that.Column {
		return false
	}
	if this.Message != that.Message {
		return false
	}
	if this.Source != that.Source {
		return false
	}
	if this.Code != that.Code {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Diagnostic) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*Diagnostic)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *Sandbox) EqualVT(that *Sandbox) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Reason != that.Reason {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Sandbox) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*Sandbox)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *Input) EqualVT(that *Input) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Body == nil && that.Body != nil {
		return false
	} else if this.Body != nil {
		if that.Body == nil {
			return false
		}
		if !this.Body.(interface{ EqualVT(isInput_Body) bool }).EqualVT(that.Body) {
			return false
		}
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Input) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*Input)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *Input_Command) EqualVT(thatIface isInput_Body) bool {
	that, ok := thatIface.(*Input_Command)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if this.Command != that.Command {
		return false
	}
	return true
}

func (this *Input_Press) EqualVT(thatIface isInput_Body) bool {
	that, ok := thatIface.(*Input_Press)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if !protobuf_go_lite.EqualVTImplicit(this.Press, that.Press, func() *Press { return &Press{} }) {
		return false
	}
	return true
}

func (this *Press) EqualVT(that *Press) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Mod != that.Mod {
		return false
	}
	if this.Slot != that.Slot {
		return false
	}
	if this.Node != that.Node {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Press) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*Press)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *Published) EqualVT(that *Published) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Provider != that.Provider {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.Release, that.Release) {
		return false
	}
	if this.Location != that.Location {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Published) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*Published)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

// MarshalProtoJSON marshals the Event message to JSON.
func (x *Event) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Body != nil {
		switch ov := x.Body.(type) {
		case *Event_Note:
			s.WriteMoreIf(&wroteField)
			s.WriteObjectField("note")
			s.WriteString(ov.Note)
		case *Event_Building:
			s.WriteMoreIf(&wroteField)
			s.WriteObjectField("building")
			ov.Building.MarshalProtoJSON(s.WithField("building"))
		case *Event_Built:
			s.WriteMoreIf(&wroteField)
			s.WriteObjectField("built")
			ov.Built.MarshalProtoJSON(s.WithField("built"))
		case *Event_Host:
			s.WriteMoreIf(&wroteField)
			s.WriteObjectField("host")
			ov.Host.MarshalProtoJSON(s.WithField("host"))
		case *Event_Published:
			s.WriteMoreIf(&wroteField)
			s.WriteObjectField("published")
			ov.Published.MarshalProtoJSON(s.WithField("published"))
		case *Event_Sandbox:
			s.WriteMoreIf(&wroteField)
			s.WriteObjectField("sandbox")
			ov.Sandbox.MarshalProtoJSON(s.WithField("sandbox"))
		}
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the Event to JSON.
func (x *Event) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the Event message from JSON.
func (x *Event) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "note":
			s.AddField("note")
			ov := &Event_Note{}
			x.Body = ov
			ov.Note = s.ReadString()
		case "building":
			ov := &Event_Building{}
			x.Body = ov
			if s.ReadNil() {
				ov.Building = nil
				return
			}
			ov.Building = &Building{}
			ov.Building.UnmarshalProtoJSON(s.WithField("building", true))
		case "built":
			ov := &Event_Built{}
			x.Body = ov
			if s.ReadNil() {
				ov.Built = nil
				return
			}
			ov.Built = &Built{}
			ov.Built.UnmarshalProtoJSON(s.WithField("built", true))
		case "host":
			ov := &Event_Host{}
			x.Body = ov
			if s.ReadNil() {
				ov.Host = nil
				return
			}
			ov.Host = &control.HostEvent{}
			ov.Host.UnmarshalProtoJSON(s.WithField("host", true))
		case "published":
			ov := &Event_Published{}
			x.Body = ov
			if s.ReadNil() {
				ov.Published = nil
				return
			}
			ov.Published = &Published{}
			ov.Published.UnmarshalProtoJSON(s.WithField("published", true))
		case "sandbox":
			ov := &Event_Sandbox{}
			x.Body = ov
			if s.ReadNil() {
				ov.Sandbox = nil
				return
			}
			ov.Sandbox = &Sandbox{}
			ov.Sandbox.UnmarshalProtoJSON(s.WithField("sandbox", true))
		}
	})
}

// UnmarshalJSON unmarshals the Event from JSON.
func (x *Event) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the Building message to JSON.
func (x *Building) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Dir != "" || s.HasField("dir") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("dir")
		s.WriteString(x.Dir)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the Building to JSON.
func (x *Building) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the Building message from JSON.
func (x *Building) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "dir":
			s.AddField("dir")
			x.Dir = s.ReadString()
		}
	})
}

// UnmarshalJSON unmarshals the Building from JSON.
func (x *Building) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the Built message to JSON.
func (x *Built) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Dir != "" || s.HasField("dir") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("dir")
		s.WriteString(x.Dir)
	}
	if x.Ok || s.HasField("ok") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("ok")
		s.WriteBool(x.Ok)
	}
	if x.Error != "" || s.HasField("error") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("error")
		s.WriteString(x.Error)
	}
	if len(x.Diagnostics) > 0 || s.HasField("diagnostics") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("diagnostics")
		s.WriteArrayStart()
		var wroteElement bool
		for _, element := range x.Diagnostics {
			s.WriteMoreIf(&wroteElement)
			element.MarshalProtoJSON(s.WithField("diagnostics"))
		}
		s.WriteArrayEnd()
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the Built to JSON.
func (x *Built) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the Built message from JSON.
func (x *Built) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "dir":
			s.AddField("dir")
			x.Dir = s.ReadString()
		case "ok":
			s.AddField("ok")
			x.Ok = s.ReadBool()
		case "error":
			s.AddField("error")
			x.Error = s.ReadString()
		case "diagnostics":
			s.AddField("diagnostics")
			if s.ReadNil() {
				x.Diagnostics = nil
				return
			}
			s.ReadArray(func() {
				if s.ReadNil() {
					x.Diagnostics = append(x.Diagnostics, nil)
					return
				}
				v := &Diagnostic{}
				v.UnmarshalProtoJSON(s.WithField("diagnostics", false))
				if s.Err() != nil {
					return
				}
				x.Diagnostics = append(x.Diagnostics, v)
			})
		}
	})
}

// UnmarshalJSON unmarshals the Built from JSON.
func (x *Built) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the Diagnostic message to JSON.
func (x *Diagnostic) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.File != "" || s.HasField("file") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("file")
		s.WriteString(x.File)
	}
	if x.Line != 0 || s.HasField("line") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("line")
		s.WriteUint32(x.Line)
	}
	if x.Column != 0 || s.HasField("column") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("column")
		s.WriteUint32(x.Column)
	}
	if x.Message != "" || s.HasField("message") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("message")
		s.WriteString(x.Message)
	}
	if x.Source != "" || s.HasField("source") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("source")
		s.WriteString(x.Source)
	}
	if x.Code != "" || s.HasField("code") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("code")
		s.WriteString(x.Code)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the Diagnostic to JSON.
func (x *Diagnostic) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the Diagnostic message from JSON.
func (x *Diagnostic) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "file":
			s.AddField("file")
			x.File = s.ReadString()
		case "line":
			s.AddField("line")
			x.Line = s.ReadUint32()
		case "column":
			s.AddField("column")
			x.Column = s.ReadUint32()
		case "message":
			s.AddField("message")
			x.Message = s.ReadString()
		case "source":
			s.AddField("source")
			x.Source = s.ReadString()
		case "code":
			s.AddField("code")
			x.Code = s.ReadString()
		}
	})
}

// UnmarshalJSON unmarshals the Diagnostic from JSON.
func (x *Diagnostic) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the Sandbox message to JSON.
func (x *Sandbox) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Reason != "" || s.HasField("reason") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("reason")
		s.WriteString(x.Reason)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the Sandbox to JSON.
func (x *Sandbox) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the Sandbox message from JSON.
func (x *Sandbox) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "reason":
			s.AddField("reason")
			x.Reason = s.ReadString()
		}
	})
}

// UnmarshalJSON unmarshals the Sandbox from JSON.
func (x *Sandbox) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the Input message to JSON.
func (x *Input) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Body != nil {
		switch ov := x.Body.(type) {
		case *Input_Command:
			s.WriteMoreIf(&wroteField)
			s.WriteObjectField("command")
			s.WriteString(ov.Command)
		case *Input_Press:
			s.WriteMoreIf(&wroteField)
			s.WriteObjectField("press")
			ov.Press.MarshalProtoJSON(s.WithField("press"))
		}
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the Input to JSON.
func (x *Input) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the Input message from JSON.
func (x *Input) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "command":
			s.AddField("command")
			ov := &Input_Command{}
			x.Body = ov
			ov.Command = s.ReadString()
		case "press":
			ov := &Input_Press{}
			x.Body = ov
			if s.ReadNil() {
				ov.Press = nil
				return
			}
			ov.Press = &Press{}
			ov.Press.UnmarshalProtoJSON(s.WithField("press", true))
		}
	})
}

// UnmarshalJSON unmarshals the Input from JSON.
func (x *Input) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the Press message to JSON.
func (x *Press) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Mod != "" || s.HasField("mod") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("mod")
		s.WriteString(x.Mod)
	}
	if x.Slot != 0 || s.HasField("slot") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("slot")
		s.WriteInt32(x.Slot)
	}
	if x.Node != "" || s.HasField("node") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("node")
		s.WriteString(x.Node)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the Press to JSON.
func (x *Press) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the Press message from JSON.
func (x *Press) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "mod":
			s.AddField("mod")
			x.Mod = s.ReadString()
		case "slot":
			s.AddField("slot")
			x.Slot = s.ReadInt32()
		case "node":
			s.AddField("node")
			x.Node = s.ReadString()
		}
	})
}

// UnmarshalJSON unmarshals the Press from JSON.
func (x *Press) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the Published message to JSON.
func (x *Published) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Provider != "" || s.HasField("provider") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("provider")
		s.WriteString(x.Provider)
	}
	if x.Release != nil || s.HasField("release") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("release")
		x.Release.MarshalProtoJSON(s.WithField("release"))
	}
	if x.Location != "" || s.HasField("location") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("location")
		s.WriteString(x.Location)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the Published to JSON.
func (x *Published) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the Published message from JSON.
func (x *Published) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "provider":
			s.AddField("provider")
			x.Provider = s.ReadString()
		case "release":
			if s.ReadNil() {
				x.Release = nil
				return
			}
			x.Release = &publish.Release{}
			x.Release.UnmarshalProtoJSON(s.WithField("release", true))
		case "location":
			s.AddField("location")
			x.Location = s.ReadString()
		}
	})
}

// UnmarshalJSON unmarshals the Published from JSON.
func (x *Published) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

func (m *Event) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Event) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Event) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if vtmsg, ok := m.Body.(interface {
		MarshalToSizedBufferVT([]byte) (int, error)
	}); ok {
		size, err := vtmsg.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
	}
	return len(dAtA) - i, nil
}

func (m *Event_Note) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Event_Note) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = protobuf_go_lite.EncodeString(dAtA, i, m.Note)
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Event_Building) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Event_Building) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Building != nil {
		size, err := m.Building.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x12
	} else {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, 0)
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}

func (m *Event_Built) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Event_Built) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Built != nil {
		size, err := m.Built.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x1a
	} else {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, 0)
		i--
		dAtA[i] = 0x1a
	}
	return len(dAtA) - i, nil
}

func (m *Event_Host) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Event_Host) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Host != nil {
		size, err := m.Host.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x22
	} else {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, 0)
		i--
		dAtA[i] = 0x22
	}
	return len(dAtA) - i, nil
}

func (m *Event_Published) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Event_Published) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Published != nil {
		size, err := m.Published.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x2a
	} else {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, 0)
		i--
		dAtA[i] = 0x2a
	}
	return len(dAtA) - i, nil
}

func (m *Event_Sandbox) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Event_Sandbox) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Sandbox != nil {
		size, err := m.Sandbox.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x32
	} else {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, 0)
		i--
		dAtA[i] = 0x32
	}
	return len(dAtA) - i, nil
}

func (m *Building) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Building) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Building) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if len(m.Dir) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.Dir)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Built) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Built) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Built) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if len(m.Diagnostics) > 0 {
		for iNdEx := len(m.Diagnostics) - 1; iNdEx >= 0; iNdEx-- {
			size, err := m.Diagnostics[iNdEx].MarshalToSizedBufferVT(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Error) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.Error)
		i--
		dAtA[i] = 0x1a
	}
	if m.Ok {
		i = protobuf_go_lite.EncodeBool(dAtA, i, m.Ok)
		i--
		dAtA[i] = 0x10
	}
	if len(m.Dir) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.Dir)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Diagnostic) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Diagnostic) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Diagnostic) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if len(m.Code) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.Code)
		i--
		dAtA[i] = 0x32
	}
	if len(m.Source) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.Source)
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Message) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.Message)
		i--
		dAtA[i] = 0x22
	}
	if m.Column != 0 {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(m.Column))
		i--
		dAtA[i] = 0x18
	}
	if m.Line != 0 {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(m.Line))
		i--
		dAtA[i] = 0x10
	}
	if len(m.File) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.File)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Sandbox) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Sandbox) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Sandbox) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if len(m.Reason) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.Reason)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Input) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Input) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Input) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if vtmsg, ok := m.Body.(interface {
		MarshalToSizedBufferVT([]byte) (int, error)
	}); ok {
		size, err := vtmsg.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
	}
	return len(dAtA) - i, nil
}

func (m *Input_Command) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Input_Command) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = protobuf_go_lite.EncodeString(dAtA, i, m.Command)
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Input_Press) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Input_Press) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Press != nil {
		size, err := m.Press.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x12
	} else {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, 0)
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}

func (m *Press) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Press) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Press) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if len(m.Node) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.Node)
		i--
		dAtA[i] = 0x1a
	}
	if m.Slot != 0 {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(m.Slot))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Mod) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.Mod)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Published) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Published) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Published) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if len(m.Location) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.Location)
		i--
		dAtA[i] = 0x1a
	}
	if m.Release != nil {
		size, err := m.Release.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Provider) > 0 {
		i = protobuf_go_lite.EncodeString(dAtA, i, m.Provider)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Event) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if vtmsg, ok := m.Body.(interface{ SizeVT() int }); ok {
		n += vtmsg.SizeVT()
	}
	n += len(m.unknownFields)
	return n
}

func (m *Event_Note) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringValue(1, m.Note)
	return n
}

func (m *Event_Building) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Building != nil {
		l = m.Building.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	} else {
		n += 2
	}
	return n
}

func (m *Event_Built) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Built != nil {
		l = m.Built.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	} else {
		n += 2
	}
	return n
}

func (m *Event_Host) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Host != nil {
		l = m.Host.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	} else {
		n += 2
	}
	return n
}

func (m *Event_Published) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Published != nil {
		l = m.Published.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	} else {
		n += 2
	}
	return n
}

func (m *Event_Sandbox) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Sandbox != nil {
		l = m.Sandbox.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	} else {
		n += 2
	}
	return n
}

func (m *Building) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.Dir)
	n += len(m.unknownFields)
	return n
}

func (m *Built) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.Dir)
	n += protobuf_go_lite.SizeBoolNonZero(1, m.Ok)
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.Error)
	for _, e := range m.Diagnostics {
		l = e.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	n += len(m.unknownFields)
	return n
}

func (m *Diagnostic) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.File)
	n += protobuf_go_lite.SizeVarintNonZero(1, m.Line)
	n += protobuf_go_lite.SizeVarintNonZero(1, m.Column)
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.Message)
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.Source)
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.Code)
	n += len(m.unknownFields)
	return n
}

func (m *Sandbox) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.Reason)
	n += len(m.unknownFields)
	return n
}

func (m *Input) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if vtmsg, ok := m.Body.(interface{ SizeVT() int }); ok {
		n += vtmsg.SizeVT()
	}
	n += len(m.unknownFields)
	return n
}

func (m *Input_Command) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringValue(1, m.Command)
	return n
}

func (m *Input_Press) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Press != nil {
		l = m.Press.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	} else {
		n += 2
	}
	return n
}

func (m *Press) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.Mod)
	n += protobuf_go_lite.SizeVarintNonZero(1, m.Slot)
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.Node)
	n += len(m.unknownFields)
	return n
}

func (m *Published) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.Provider)
	if m.Release != nil {
		l = m.Release.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	n += protobuf_go_lite.SizeStringNonEmpty(1, m.Location)
	n += len(m.unknownFields)
	return n
}

func (x *Event) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "Event")
	switch body := x.Body.(type) {
	case *Event_Note:
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "note")
		protobuf_go_lite.TextWriteString(&sb, body.Note)
	case *Event_Building:
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "building")
		if body.Building == nil {
			protobuf_go_lite.TextWriteTextMarshaler(&sb, &Building{})
		} else {
			protobuf_go_lite.TextWriteTextMarshaler(&sb, body.Building)
		}
	case *Event_Built:
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "built")
		if body.Built == nil {
			protobuf_go_lite.TextWriteTextMarshaler(&sb, &Built{})
		} else {
			protobuf_go_lite.TextWriteTextMarshaler(&sb, body.Built)
		}
	case *Event_Host:
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "host")
		if body.Host == nil {
			protobuf_go_lite.TextWriteTextMarshaler(&sb, &control.HostEvent{})
		} else {
			protobuf_go_lite.TextWriteTextMarshaler(&sb, body.Host)
		}
	case *Event_Published:
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "published")
		if body.Published == nil {
			protobuf_go_lite.TextWriteTextMarshaler(&sb, &Published{})
		} else {
			protobuf_go_lite.TextWriteTextMarshaler(&sb, body.Published)
		}
	case *Event_Sandbox:
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "sandbox")
		if body.Sandbox == nil {
			protobuf_go_lite.TextWriteTextMarshaler(&sb, &Sandbox{})
		} else {
			protobuf_go_lite.TextWriteTextMarshaler(&sb, body.Sandbox)
		}
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *Event) String() string {
	return x.MarshalProtoText()
}

func (x *Building) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "Building")
	if x.Dir != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "dir")
		protobuf_go_lite.TextWriteString(&sb, x.Dir)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *Building) String() string {
	return x.MarshalProtoText()
}

func (x *Built) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "Built")
	if x.Dir != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "dir")
		protobuf_go_lite.TextWriteString(&sb, x.Dir)
	}
	if x.Ok != false {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "ok")
		protobuf_go_lite.TextWriteBool(&sb, x.Ok)
	}
	if x.Error != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "error")
		protobuf_go_lite.TextWriteString(&sb, x.Error)
	}
	if len(x.Diagnostics) > 0 {
		protobuf_go_lite.TextWriteListStart(&sb, initialLen, "diagnostics")
		for i, v := range x.Diagnostics {
			protobuf_go_lite.TextWriteListSeparator(&sb, i)
			if v == nil {
				protobuf_go_lite.TextWriteTextMarshaler(&sb, &Diagnostic{})
			} else {
				protobuf_go_lite.TextWriteTextMarshaler(&sb, v)
			}
		}
		protobuf_go_lite.TextWriteListEnd(&sb)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *Built) String() string {
	return x.MarshalProtoText()
}

func (x *Diagnostic) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "Diagnostic")
	if x.File != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "file")
		protobuf_go_lite.TextWriteString(&sb, x.File)
	}
	if x.Line != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "line")
		protobuf_go_lite.TextWriteUint(&sb, x.Line)
	}
	if x.Column != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "column")
		protobuf_go_lite.TextWriteUint(&sb, x.Column)
	}
	if x.Message != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "message")
		protobuf_go_lite.TextWriteString(&sb, x.Message)
	}
	if x.Source != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "source")
		protobuf_go_lite.TextWriteString(&sb, x.Source)
	}
	if x.Code != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "code")
		protobuf_go_lite.TextWriteString(&sb, x.Code)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *Diagnostic) String() string {
	return x.MarshalProtoText()
}

func (x *Sandbox) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "Sandbox")
	if x.Reason != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "reason")
		protobuf_go_lite.TextWriteString(&sb, x.Reason)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *Sandbox) String() string {
	return x.MarshalProtoText()
}

func (x *Input) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "Input")
	switch body := x.Body.(type) {
	case *Input_Command:
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "command")
		protobuf_go_lite.TextWriteString(&sb, body.Command)
	case *Input_Press:
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "press")
		if body.Press == nil {
			protobuf_go_lite.TextWriteTextMarshaler(&sb, &Press{})
		} else {
			protobuf_go_lite.TextWriteTextMarshaler(&sb, body.Press)
		}
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *Input) String() string {
	return x.MarshalProtoText()
}

func (x *Press) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "Press")
	if x.Mod != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "mod")
		protobuf_go_lite.TextWriteString(&sb, x.Mod)
	}
	if x.Slot != 0 {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "slot")
		protobuf_go_lite.TextWriteInt(&sb, x.Slot)
	}
	if x.Node != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "node")
		protobuf_go_lite.TextWriteString(&sb, x.Node)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *Press) String() string {
	return x.MarshalProtoText()
}

func (x *Published) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "Published")
	if x.Provider != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "provider")
		protobuf_go_lite.TextWriteString(&sb, x.Provider)
	}
	if x.Release != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "release")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.Release)
	}
	if x.Location != "" {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "location")
		protobuf_go_lite.TextWriteString(&sb, x.Location)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *Published) String() string {
	return x.MarshalProtoText()
}

func (m *Event) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Event: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Event: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Note", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Body = &Event_Note{Note: v}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Building", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if oneof, ok := m.Body.(*Event_Building); ok {
				if err := oneof.Building.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
					return err
				}
			} else {
				v := &Building{}
				if err := v.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
					return err
				}
				m.Body = &Event_Building{Building: v}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Built", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if oneof, ok := m.Body.(*Event_Built); ok {
				if err := oneof.Built.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
					return err
				}
			} else {
				v := &Built{}
				if err := v.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
					return err
				}
				m.Body = &Event_Built{Built: v}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Host", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if oneof, ok := m.Body.(*Event_Host); ok {
				if err := oneof.Host.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
					return err
				}
			} else {
				v := &control.HostEvent{}
				if err := v.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
					return err
				}
				m.Body = &Event_Host{Host: v}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Published", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if oneof, ok := m.Body.(*Event_Published); ok {
				if err := oneof.Published.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
					return err
				}
			} else {
				v := &Published{}
				if err := v.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
					return err
				}
				m.Body = &Event_Published{Published: v}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sandbox", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if oneof, ok := m.Body.(*Event_Sandbox); ok {
				if err := oneof.Sandbox.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
					return err
				}
			} else {
				v := &Sandbox{}
				if err := v.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
					return err
				}
				m.Body = &Event_Sandbox{Sandbox: v}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *Building) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Building: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Building: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dir", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Dir = v
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *Built) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Built: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Built: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dir", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Dir = v
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ok", wireType)
			}
			var v bool
			v, iNdEx, err = protobuf_go_lite.DecodeVarintBool(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Ok = bool(v)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Error = v
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Diagnostics", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Diagnostics = append(m.Diagnostics, &Diagnostic{})
			if err := m.Diagnostics[len(m.Diagnostics)-1].UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *Diagnostic) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Diagnostic: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Diagnostic: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field File", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.File = v
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Line", wireType)
			}
			m.Line = 0
			m.Line, iNdEx, err = protobuf_go_lite.DecodeVarintUint32(dAtA, iNdEx)
			if err != nil {
				return err
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Column", wireType)
			}
			m.Column = 0
			m.Column, iNdEx, err = protobuf_go_lite.DecodeVarintUint32(dAtA, iNdEx)
			if err != nil {
				return err
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Message = v
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Source = v
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Code = v
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *Sandbox) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Sandbox: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Sandbox: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Reason = v
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *Input) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Input: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Input: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Command", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Body = &Input_Command{Command: v}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Press", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if oneof, ok := m.Body.(*Input_Press); ok {
				if err := oneof.Press.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
					return err
				}
			} else {
				v := &Press{}
				if err := v.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
					return err
				}
				m.Body = &Input_Press{Press: v}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *Press) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Press: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Press: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mod", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Mod = v
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Slot", wireType)
			}
			m.Slot = 0
			m.Slot, iNdEx, err = protobuf_go_lite.DecodeVarintInt32(dAtA, iNdEx)
			if err != nil {
				return err
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Node", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Node = v
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *Published) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Published: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Published: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Provider", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Provider = v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Release", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.Release == nil {
				m.Release = &publish.Release{}
			}
			if err := m.Release.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Location", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Location = v
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
