// @generated by protoc-gen-es-lite unknown with parameter "target=ts,ts_nocheck=false"
// @generated from file github.com/paralin/modlock/proto/modlock/cli/cli.proto (package modlock.cli, syntax proto3)
/* eslint-disable */

import type { MessageType } from "@aptre/protobuf-es-lite/message";
import { createMessageType } from "@aptre/protobuf-es-lite/message";
import { ScalarType } from "@aptre/protobuf-es-lite/scalar";
import type { PartialFieldInfo } from "@aptre/protobuf-es-lite/field";
import { Release } from "../publish/publish.pb.js";
import { HostEvent } from "../control/control.pb.js";

export const protobufPackage = "modlock.cli";

/**
 * Building identifies the project a build started for.
 *
 * @generated from message modlock.cli.Building
 */
export interface Building {
  /**
   * Dir is the project directory.
   *
   * @generated from field: string dir = 1;
   */
  dir?: string;

};

export const Building: MessageType<Building> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.cli.Building",
    fields: [
        { no: 1, name: "dir", kind: "scalar", T: ScalarType.STRING },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * Diagnostic is one problem found in a source file.
 *
 * @generated from message modlock.cli.Diagnostic
 */
export interface Diagnostic {
  /**
   * File is the file's absolute path.
   *
   * @generated from field: string file = 1;
   */
  file?: string;
  /**
   * Line is the 1-based line.
   *
   * @generated from field: uint32 line = 2;
   */
  line?: number;
  /**
   * Column is the 1-based column, zero when unknown.
   *
   * @generated from field: uint32 column = 3;
   */
  column?: number;
  /**
   * Message describes the problem.
   *
   * @generated from field: string message = 4;
   */
  message?: string;
  /**
   * Source names the tool that found it: tsgo, esbuild, go vet or go build.
   *
   * @generated from field: string source = 5;
   */
  source?: string;
  /**
   * Code is the tool's code for the problem, such as TS2322, if it has one.
   *
   * @generated from field: string code = 6;
   */
  code?: string;

};

export const Diagnostic: MessageType<Diagnostic> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.cli.Diagnostic",
    fields: [
        { no: 1, name: "file", kind: "scalar", T: ScalarType.STRING },
        { no: 2, name: "line", kind: "scalar", T: ScalarType.UINT32 },
        { no: 3, name: "column", kind: "scalar", T: ScalarType.UINT32 },
        { no: 4, name: "message", kind: "scalar", T: ScalarType.STRING },
        { no: 5, name: "source", kind: "scalar", T: ScalarType.STRING },
        { no: 6, name: "code", kind: "scalar", T: ScalarType.STRING },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * Built reports a finished build. A failed build leaves the previous built mod
 * in place.
 *
 * @generated from message modlock.cli.Built
 */
export interface Built {
  /**
   * Dir is the project directory.
   *
   * @generated from field: string dir = 1;
   */
  dir?: string;
  /**
   * Ok is true when the build wrote the built mod.
   *
   * @generated from field: bool ok = 2;
   */
  ok?: boolean;
  /**
   * Error explains a failed build in one line.
   *
   * @generated from field: string error = 3;
   */
  error?: string;
  /**
   * Diagnostics lists the problems the checks and compilers found. A finished
   * build replaces the previous build's diagnostics.
   *
   * @generated from field: repeated modlock.cli.Diagnostic diagnostics = 4;
   */
  diagnostics?: Diagnostic[];

};

export const Built: MessageType<Built> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.cli.Built",
    fields: [
        { no: 1, name: "dir", kind: "scalar", T: ScalarType.STRING },
        { no: 2, name: "ok", kind: "scalar", T: ScalarType.BOOL },
        { no: 3, name: "error", kind: "scalar", T: ScalarType.STRING },
        { no: 4, name: "diagnostics", kind: "message", T: () => Diagnostic, repeated: true },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * Published reports a release.
 *
 * @generated from message modlock.cli.Published
 */
export interface Published {
  /**
   * Provider is where the mod went: hyperline, archive or github.
   *
   * @generated from field: string provider = 1;
   */
  provider?: string;
  /**
   * Release is the release hyperline.gg recorded.
   *
   * @generated from field: modlock.publish.Release release = 2;
   */
  release?: Release;
  /**
   * Location is the archive's path or the GitHub release tag.
   *
   * @generated from field: string location = 3;
   */
  location?: string;

};

export const Published: MessageType<Published> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.cli.Published",
    fields: [
        { no: 1, name: "provider", kind: "scalar", T: ScalarType.STRING },
        { no: 2, name: "release", kind: "message", T: () => Release },
        { no: 3, name: "location", kind: "scalar", T: ScalarType.STRING },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * Event is one thing the command line did or saw.
 *
 * @generated from message modlock.cli.Event
 */
export interface Event {

  /**
   * Body selects the event.
   *
   * @generated from oneof modlock.cli.Event.body
   */
  body?: {
    value?: undefined,
    case: undefined
  } | {
    /**
     * Note is a line of progress for the creator.
     *
     * @generated from field: string note = 1;
     */
    value: string;
    case: "note";
  } | {
    /**
     * Building reports that a build of the project started.
     *
     * @generated from field: modlock.cli.Building building = 2;
     */
    value: Building;
    case: "building";
  } | {
    /**
     * Built reports a finished build.
     *
     * @generated from field: modlock.cli.Built built = 3;
     */
    value: Built;
    case: "built";
  } | {
    /**
     * Host carries an event from the running server.
     *
     * @generated from field: modlock.control.HostEvent host = 4;
     */
    value: HostEvent;
    case: "host";
  } | {
    /**
     * Published reports a release the provider recorded.
     *
     * @generated from field: modlock.cli.Published published = 5;
     */
    value: Published;
    case: "published";
  };

};

export const Event: MessageType<Event> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.cli.Event",
    fields: [
        { no: 1, name: "note", kind: "scalar", T: ScalarType.STRING, oneof: "body" },
        { no: 2, name: "building", kind: "message", T: () => Building, oneof: "body" },
        { no: 3, name: "built", kind: "message", T: () => Built, oneof: "body" },
        { no: 4, name: "host", kind: "message", T: () => HostEvent, oneof: "body" },
        { no: 5, name: "published", kind: "message", T: () => Published, oneof: "body" },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

