// @generated by protoc-gen-es-lite unknown with parameter "target=ts,ts_nocheck=false"
// @generated from file github.com/paralin/modlock/proto/modlock/game_signatures.proto (package modlock.gamedata, syntax proto3)
/* eslint-disable */

import { createEnumType } from "@aptre/protobuf-es-lite/enum";
import type { MessageType } from "@aptre/protobuf-es-lite/message";
import { createMessageType } from "@aptre/protobuf-es-lite/message";
import { ScalarType } from "@aptre/protobuf-es-lite/scalar";
import type { PartialFieldInfo } from "@aptre/protobuf-es-lite/field";

export const protobufPackage = "modlock.gamedata";

/**
 * GameModule is one game binary that carries scanned code.
 *
 * @generated from enum modlock.gamedata.GameModule
 */
export enum GameModule {
  /**
   * GAME_MODULE_UNKNOWN names no binary; an entry that lists it is skipped.
   *
   * @generated from enum value: GAME_MODULE_UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * GAME_MODULE_SERVER is server.dll.
   *
   * @generated from enum value: GAME_MODULE_SERVER = 1;
   */
  SERVER = 1,

  /**
   * GAME_MODULE_CLIENT is client.dll.
   *
   * @generated from enum value: GAME_MODULE_CLIENT = 2;
   */
  CLIENT = 2,

  /**
   * GAME_MODULE_ENGINE is engine2.dll.
   *
   * @generated from enum value: GAME_MODULE_ENGINE = 3;
   */
  ENGINE = 3,
}

export const GameModule_Enum = /* @__PURE__ */ createEnumType("modlock.gamedata.GameModule", [
  [0, "GAME_MODULE_UNKNOWN"],
  [1, "GAME_MODULE_SERVER"],
  [2, "GAME_MODULE_CLIENT"],
  [3, "GAME_MODULE_ENGINE"],
]);

/**
 * GameSignature is one byte pattern and the address its unique match
 * resolves to.
 *
 * @generated from message modlock.gamedata.GameSignature
 */
export interface GameSignature {
  /**
   * Id is the stable name callers resolve, such as "pawn.respawn".
   *
   * @generated from field: string id = 1;
   */
  id?: string;
  /**
   * Modules lists every binary whose image carries the pattern exactly once.
   *
   * @generated from field: repeated modlock.gamedata.GameModule modules = 2;
   */
  modules?: GameModule[];
  /**
   * Pattern is the byte signature for the current game build in hex pairs;
   * "??" marks a wildcard byte.
   *
   * @generated from field: string pattern = 3;
   */
  pattern?: string;
  /**
   * Shape describes the native function or instruction that was matched.
   *
   * @generated from field: string shape = 6;
   */
  shape?: string;

  /**
   * Target selects a relative operand inside the match. Without one, the
   * entry resolves to the first matched byte, usually a function entry.
   *
   * @generated from oneof modlock.gamedata.GameSignature.target
   */
  target?: {
    value?: undefined,
    case: undefined
  } | {
    /**
     * CallAt is the offset into the match of an E8 rel32 call; the entry
     * resolves to the call's target.
     *
     * @generated from field: uint32 call_at = 4;
     */
    value: number;
    case: "callAt";
  } | {
    /**
     * RipRelativeAt is the offset into the match of a seven-byte REX.W
     * instruction (LEA or MOV) with rel32 at offset + 3; the entry resolves to
     * its address operand.
     *
     * @generated from field: uint32 rip_relative_at = 5;
     */
    value: number;
    case: "ripRelativeAt";
  };

};

export const GameSignature: MessageType<GameSignature> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.gamedata.GameSignature",
    fields: [
        { no: 1, name: "id", kind: "scalar", T: ScalarType.STRING },
        { no: 2, name: "modules", kind: "enum", T: GameModule_Enum, repeated: true },
        { no: 3, name: "pattern", kind: "scalar", T: ScalarType.STRING },
        { no: 4, name: "call_at", kind: "scalar", T: ScalarType.UINT32, oneof: "target" },
        { no: 5, name: "rip_relative_at", kind: "scalar", T: ScalarType.UINT32, oneof: "target" },
        { no: 6, name: "shape", kind: "scalar", T: ScalarType.STRING },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * GameSignatureFile is the game data file modlock-host reads at start: every
 * byte pattern modlock scans for in the game binaries, keyed by the ids
 * callers resolve.
 *
 * @generated from message modlock.gamedata.GameSignatureFile
 */
export interface GameSignatureFile {
  /**
   * Signatures holds one entry per id, sorted by id.
   *
   * @generated from field: repeated modlock.gamedata.GameSignature signatures = 1;
   */
  signatures?: GameSignature[];

};

export const GameSignatureFile: MessageType<GameSignatureFile> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.gamedata.GameSignatureFile",
    fields: [
        { no: 1, name: "signatures", kind: "message", T: () => GameSignature, repeated: true },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

