//go:build deps_only && cgo

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: github.com/paralin/modlock/proto/modlock/game_signatures.proto
// Protobuf C++ Version: 6.33.4

#ifndef github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fgame_5fsignatures_2eproto_2epb_2eh
#define github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fgame_5fsignatures_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fgame_5fsignatures_2eproto MODLOCK_API

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct MODLOCK_API TableStruct_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fgame_5fsignatures_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
MODLOCK_API extern const ::google::protobuf::internal::DescriptorTable descriptor_table_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fgame_5fsignatures_2eproto;
}  // extern "C"
namespace modlock {
namespace gamedata {
enum GameModule : int;
extern const uint32_t GameModule_internal_data_[];
class GameSignature;
struct GameSignatureDefaultTypeInternal;
MODLOCK_API extern GameSignatureDefaultTypeInternal _GameSignature_default_instance_;
MODLOCK_API extern const ::google::protobuf::internal::ClassDataFull GameSignature_class_data_;
class GameSignatureFile;
struct GameSignatureFileDefaultTypeInternal;
MODLOCK_API extern GameSignatureFileDefaultTypeInternal _GameSignatureFile_default_instance_;
MODLOCK_API extern const ::google::protobuf::internal::ClassDataFull GameSignatureFile_class_data_;
}  // namespace gamedata
}  // namespace modlock
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::modlock::gamedata::GameModule_internal_data_>
    internal::EnumTraitsImpl::value<::modlock::gamedata::GameModule>;
}  // namespace protobuf
}  // namespace google

namespace modlock {
namespace gamedata {
enum GameModule : int {
  GAME_MODULE_UNKNOWN = 0,
  GAME_MODULE_SERVER = 1,
  GAME_MODULE_CLIENT = 2,
  GAME_MODULE_ENGINE = 3,
  GameModule_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  GameModule_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t GameModule_internal_data_[];
inline constexpr GameModule GameModule_MIN =
    static_cast<GameModule>(0);
inline constexpr GameModule GameModule_MAX =
    static_cast<GameModule>(3);
inline bool GameModule_IsValid(int value) {
  return 0 <= value && value <= 3;
}
inline constexpr int GameModule_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL GameModule_descriptor();
template <typename T>
const ::std::string& GameModule_Name(T value) {
  static_assert(::std::is_same<T, GameModule>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to GameModule_Name().");
  return GameModule_Name(static_cast<GameModule>(value));
}
template <>
inline const ::std::string& GameModule_Name(GameModule value) {
  return ::google::protobuf::internal::NameOfDenseEnum<GameModule_descriptor, 0, 3>(
      static_cast<int>(value));
}
inline bool GameModule_Parse(
    ::absl::string_view name, GameModule* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<GameModule>(GameModule_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class MODLOCK_API GameSignature final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:modlock.gamedata.GameSignature) */ {
 public:
  inline GameSignature() : GameSignature(nullptr) {}
  ~GameSignature() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GameSignature* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GameSignature));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GameSignature(::google::protobuf::internal::ConstantInitialized);

  inline GameSignature(const GameSignature& from) : GameSignature(nullptr, from) {}
  inline GameSignature(GameSignature&& from) noexcept
      : GameSignature(nullptr, ::std::move(from)) {}
  inline GameSignature& operator=(const GameSignature& from) {
    CopyFrom(from);
    return *this;
  }
  inline GameSignature& operator=(GameSignature&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GameSignature& default_instance() {
    return *reinterpret_cast<const GameSignature*>(
        &_GameSignature_default_instance_);
  }
  enum TargetCase {
    kCallAt = 4,
    kRipRelativeAt = 5,
    TARGET_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(GameSignature& a, GameSignature& b) { a.Swap(&b); }
  inline void Swap(GameSignature* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GameSignature* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GameSignature* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<GameSignature>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GameSignature& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GameSignature& from) { GameSignature::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GameSignature* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "modlock.gamedata.GameSignature"; }

  explicit GameSignature(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  GameSignature(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const GameSignature& from);
  GameSignature(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, GameSignature&& from) noexcept
      : GameSignature(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kModulesFieldNumber = 2,
    kIdFieldNumber = 1,
    kPatternFieldNumber = 3,
    kShapeFieldNumber = 6,
    kCallAtFieldNumber = 4,
    kRipRelativeAtFieldNumber = 5,
  };
  // repeated .modlock.gamedata.GameModule modules = 2;
  int modules_size() const;
  private:
  int _internal_modules_size() const;

  public:
  void clear_modules() ;
  public:
  ::modlock::gamedata::GameModule modules(int index) const;
  void set_modules(int index, ::modlock::gamedata::GameModule value);
  void add_modules(::modlock::gamedata::GameModule value);
  const ::google::protobuf::RepeatedField<int>& modules() const;
  ::google::protobuf::RepeatedField<int>* PROTOBUF_NONNULL mutable_modules();

  private:
  const ::google::protobuf::RepeatedField<int>& _internal_modules() const;
  ::google::protobuf::RepeatedField<int>* PROTOBUF_NONNULL _internal_mutable_modules();

  public:
  // string id = 1;
  void clear_id() ;
  const ::std::string& id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_id();
  void set_allocated_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_id();

  public:
  // string pattern = 3;
  void clear_pattern() ;
  const ::std::string& pattern() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_pattern(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_pattern();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_pattern();
  void set_allocated_pattern(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_pattern() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_pattern(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_pattern();

  public:
  // string shape = 6;
  void clear_shape() ;
  const ::std::string& shape() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_shape(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_shape();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_shape();
  void set_allocated_shape(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_shape() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_shape(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_shape();

  public:
  // uint32 call_at = 4;
  bool has_call_at() const;
  void clear_call_at() ;
  ::uint32_t call_at() const;
  void set_call_at(::uint32_t value);

  private:
  ::uint32_t _internal_call_at() const;
  void _internal_set_call_at(::uint32_t value);

  public:
  // uint32 rip_relative_at = 5;
  bool has_rip_relative_at() const;
  void clear_rip_relative_at() ;
  ::uint32_t rip_relative_at() const;
  void set_rip_relative_at(::uint32_t value);

  private:
  ::uint32_t _internal_rip_relative_at() const;
  void _internal_set_rip_relative_at(::uint32_t value);

  public:
  void clear_target();
  TargetCase target_case() const;
  // @@protoc_insertion_point(class_scope:modlock.gamedata.GameSignature)
 private:
  class _Internal;
  void set_has_call_at();
  void set_has_rip_relative_at();
  inline bool has_target() const;
  inline void clear_has_target();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 6,
                                   0, 53,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const GameSignature& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<int> modules_;
    ::google::protobuf::internal::CachedSize _modules_cached_byte_size_;
    ::google::protobuf::internal::ArenaStringPtr id_;
    ::google::protobuf::internal::ArenaStringPtr pattern_;
    ::google::protobuf::internal::ArenaStringPtr shape_;
    union TargetUnion {
      constexpr TargetUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::uint32_t call_at_;
      ::uint32_t rip_relative_at_;
    } target_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fgame_5fsignatures_2eproto;
};

MODLOCK_API extern const ::google::protobuf::internal::ClassDataFull GameSignature_class_data_;
// -------------------------------------------------------------------

class MODLOCK_API GameSignatureFile final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:modlock.gamedata.GameSignatureFile) */ {
 public:
  inline GameSignatureFile() : GameSignatureFile(nullptr) {}
  ~GameSignatureFile() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GameSignatureFile* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GameSignatureFile));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GameSignatureFile(::google::protobuf::internal::ConstantInitialized);

  inline GameSignatureFile(const GameSignatureFile& from) : GameSignatureFile(nullptr, from) {}
  inline GameSignatureFile(GameSignatureFile&& from) noexcept
      : GameSignatureFile(nullptr, ::std::move(from)) {}
  inline GameSignatureFile& operator=(const GameSignatureFile& from) {
    CopyFrom(from);
    return *this;
  }
  inline GameSignatureFile& operator=(GameSignatureFile&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GameSignatureFile& default_instance() {
    return *reinterpret_cast<const GameSignatureFile*>(
        &_GameSignatureFile_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(GameSignatureFile& a, GameSignatureFile& b) { a.Swap(&b); }
  inline void Swap(GameSignatureFile* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GameSignatureFile* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GameSignatureFile* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<GameSignatureFile>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GameSignatureFile& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GameSignatureFile& from) { GameSignatureFile::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GameSignatureFile* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "modlock.gamedata.GameSignatureFile"; }

  explicit GameSignatureFile(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  GameSignatureFile(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const GameSignatureFile& from);
  GameSignatureFile(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, GameSignatureFile&& from) noexcept
      : GameSignatureFile(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSignaturesFieldNumber = 1,
  };
  // repeated .modlock.gamedata.GameSignature signatures = 1;
  int signatures_size() const;
  private:
  int _internal_signatures_size() const;

  public:
  void clear_signatures() ;
  ::modlock::gamedata::GameSignature* PROTOBUF_NONNULL mutable_signatures(int index);
  ::google::protobuf::RepeatedPtrField<::modlock::gamedata::GameSignature>* PROTOBUF_NONNULL mutable_signatures();

  private:
  const ::google::protobuf::RepeatedPtrField<::modlock::gamedata::GameSignature>& _internal_signatures() const;
  ::google::protobuf::RepeatedPtrField<::modlock::gamedata::GameSignature>* PROTOBUF_NONNULL _internal_mutable_signatures();
  public:
  const ::modlock::gamedata::GameSignature& signatures(int index) const;
  ::modlock::gamedata::GameSignature* PROTOBUF_NONNULL add_signatures();
  const ::google::protobuf::RepeatedPtrField<::modlock::gamedata::GameSignature>& signatures() const;
  // @@protoc_insertion_point(class_scope:modlock.gamedata.GameSignatureFile)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const GameSignatureFile& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::modlock::gamedata::GameSignature > signatures_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fgame_5fsignatures_2eproto;
};

MODLOCK_API extern const ::google::protobuf::internal::ClassDataFull GameSignatureFile_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// GameSignatureFile

// repeated .modlock.gamedata.GameSignature signatures = 1;
inline int GameSignatureFile::_internal_signatures_size() const {
  return _internal_signatures().size();
}
inline int GameSignatureFile::signatures_size() const {
  return _internal_signatures_size();
}
inline void GameSignatureFile::clear_signatures() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.signatures_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::modlock::gamedata::GameSignature* PROTOBUF_NONNULL GameSignatureFile::mutable_signatures(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:modlock.gamedata.GameSignatureFile.signatures)
  return _internal_mutable_signatures()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::modlock::gamedata::GameSignature>* PROTOBUF_NONNULL GameSignatureFile::mutable_signatures()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:modlock.gamedata.GameSignatureFile.signatures)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_signatures();
}
inline const ::modlock::gamedata::GameSignature& GameSignatureFile::signatures(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:modlock.gamedata.GameSignatureFile.signatures)
  return _internal_signatures().Get(index);
}
inline ::modlock::gamedata::GameSignature* PROTOBUF_NONNULL GameSignatureFile::add_signatures()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::modlock::gamedata::GameSignature* _add =
      _internal_mutable_signatures()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:modlock.gamedata.GameSignatureFile.signatures)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::modlock::gamedata::GameSignature>& GameSignatureFile::signatures() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:modlock.gamedata.GameSignatureFile.signatures)
  return _internal_signatures();
}
inline const ::google::protobuf::RepeatedPtrField<::modlock::gamedata::GameSignature>&
GameSignatureFile::_internal_signatures() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.signatures_;
}
inline ::google::protobuf::RepeatedPtrField<::modlock::gamedata::GameSignature>* PROTOBUF_NONNULL
GameSignatureFile::_internal_mutable_signatures() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.signatures_;
}

// -------------------------------------------------------------------

// GameSignature

// string id = 1;
inline void GameSignature::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& GameSignature::id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:modlock.gamedata.GameSignature.id)
  return _internal_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void GameSignature::set_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:modlock.gamedata.GameSignature.id)
}
inline ::std::string* PROTOBUF_NONNULL GameSignature::mutable_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:modlock.gamedata.GameSignature.id)
  return _s;
}
inline const ::std::string& GameSignature::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_.Get();
}
inline void GameSignature::_internal_set_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL GameSignature::_internal_mutable_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE GameSignature::release_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:modlock.gamedata.GameSignature.id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.id_.Set("", GetArena());
  }
  return released;
}
inline void GameSignature::set_allocated_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.id_.IsDefault()) {
    _impl_.id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:modlock.gamedata.GameSignature.id)
}

// repeated .modlock.gamedata.GameModule modules = 2;
inline int GameSignature::_internal_modules_size() const {
  return _internal_modules().size();
}
inline int GameSignature::modules_size() const {
  return _internal_modules_size();
}
inline void GameSignature::clear_modules() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.modules_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::modlock::gamedata::GameModule GameSignature::modules(int index) const {
  // @@protoc_insertion_point(field_get:modlock.gamedata.GameSignature.modules)
  return static_cast<::modlock::gamedata::GameModule>(_internal_modules().Get(index));
}
inline void GameSignature::set_modules(int index, ::modlock::gamedata::GameModule value) {
  _internal_mutable_modules()->Set(index, value);
  // @@protoc_insertion_point(field_set:modlock.gamedata.GameSignature.modules)
}
inline void GameSignature::add_modules(::modlock::gamedata::GameModule value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_modules()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:modlock.gamedata.GameSignature.modules)
}
inline const ::google::protobuf::RepeatedField<int>& GameSignature::modules() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:modlock.gamedata.GameSignature.modules)
  return _internal_modules();
}
inline ::google::protobuf::RepeatedField<int>* PROTOBUF_NONNULL GameSignature::mutable_modules()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:modlock.gamedata.GameSignature.modules)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_modules();
}
inline const ::google::protobuf::RepeatedField<int>& GameSignature::_internal_modules()
    const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.modules_;
}
inline ::google::protobuf::RepeatedField<int>* PROTOBUF_NONNULL
GameSignature::_internal_mutable_modules() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.modules_;
}

// string pattern = 3;
inline void GameSignature::clear_pattern() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pattern_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& GameSignature::pattern() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:modlock.gamedata.GameSignature.pattern)
  return _internal_pattern();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void GameSignature::set_pattern(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.pattern_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:modlock.gamedata.GameSignature.pattern)
}
inline ::std::string* PROTOBUF_NONNULL GameSignature::mutable_pattern()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_pattern();
  // @@protoc_insertion_point(field_mutable:modlock.gamedata.GameSignature.pattern)
  return _s;
}
inline const ::std::string& GameSignature::_internal_pattern() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pattern_.Get();
}
inline void GameSignature::_internal_set_pattern(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pattern_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL GameSignature::_internal_mutable_pattern() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.pattern_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE GameSignature::release_pattern() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:modlock.gamedata.GameSignature.pattern)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.pattern_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.pattern_.Set("", GetArena());
  }
  return released;
}
inline void GameSignature::set_allocated_pattern(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.pattern_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.pattern_.IsDefault()) {
    _impl_.pattern_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:modlock.gamedata.GameSignature.pattern)
}

// uint32 call_at = 4;
inline bool GameSignature::has_call_at() const {
  return target_case() == kCallAt;
}
inline void GameSignature::set_has_call_at() {
  _impl_._oneof_case_[0] = kCallAt;
}
inline void GameSignature::clear_call_at() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (target_case() == kCallAt) {
    _impl_.target_.call_at_ = 0u;
    clear_has_target();
  }
}
inline ::uint32_t GameSignature::call_at() const {
  // @@protoc_insertion_point(field_get:modlock.gamedata.GameSignature.call_at)
  return _internal_call_at();
}
inline void GameSignature::set_call_at(::uint32_t value) {
  if (target_case() != kCallAt) {
    clear_target();
    set_has_call_at();
  }
  _impl_.target_.call_at_ = value;
  // @@protoc_insertion_point(field_set:modlock.gamedata.GameSignature.call_at)
}
inline ::uint32_t GameSignature::_internal_call_at() const {
  if (target_case() == kCallAt) {
    return _impl_.target_.call_at_;
  }
  return 0u;
}

// uint32 rip_relative_at = 5;
inline bool GameSignature::has_rip_relative_at() const {
  return target_case() == kRipRelativeAt;
}
inline void GameSignature::set_has_rip_relative_at() {
  _impl_._oneof_case_[0] = kRipRelativeAt;
}
inline void GameSignature::clear_rip_relative_at() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (target_case() == kRipRelativeAt) {
    _impl_.target_.rip_relative_at_ = 0u;
    clear_has_target();
  }
}
inline ::uint32_t GameSignature::rip_relative_at() const {
  // @@protoc_insertion_point(field_get:modlock.gamedata.GameSignature.rip_relative_at)
  return _internal_rip_relative_at();
}
inline void GameSignature::set_rip_relative_at(::uint32_t value) {
  if (target_case() != kRipRelativeAt) {
    clear_target();
    set_has_rip_relative_at();
  }
  _impl_.target_.rip_relative_at_ = value;
  // @@protoc_insertion_point(field_set:modlock.gamedata.GameSignature.rip_relative_at)
}
inline ::uint32_t GameSignature::_internal_rip_relative_at() const {
  if (target_case() == kRipRelativeAt) {
    return _impl_.target_.rip_relative_at_;
  }
  return 0u;
}

// string shape = 6;
inline void GameSignature::clear_shape() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.shape_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline const ::std::string& GameSignature::shape() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:modlock.gamedata.GameSignature.shape)
  return _internal_shape();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void GameSignature::set_shape(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.shape_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:modlock.gamedata.GameSignature.shape)
}
inline ::std::string* PROTOBUF_NONNULL GameSignature::mutable_shape()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::std::string* _s = _internal_mutable_shape();
  // @@protoc_insertion_point(field_mutable:modlock.gamedata.GameSignature.shape)
  return _s;
}
inline const ::std::string& GameSignature::_internal_shape() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.shape_.Get();
}
inline void GameSignature::_internal_set_shape(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.shape_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL GameSignature::_internal_mutable_shape() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.shape_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE GameSignature::release_shape() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:modlock.gamedata.GameSignature.shape)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000008U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  auto* released = _impl_.shape_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.shape_.Set("", GetArena());
  }
  return released;
}
inline void GameSignature::set_allocated_shape(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  _impl_.shape_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.shape_.IsDefault()) {
    _impl_.shape_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:modlock.gamedata.GameSignature.shape)
}

inline bool GameSignature::has_target() const {
  return target_case() != TARGET_NOT_SET;
}
inline void GameSignature::clear_has_target() {
  _impl_._oneof_case_[0] = TARGET_NOT_SET;
}
inline GameSignature::TargetCase GameSignature::target_case() const {
  return GameSignature::TargetCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace gamedata
}  // namespace modlock


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::modlock::gamedata::GameModule> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::modlock::gamedata::GameModule>() {
  return ::modlock::gamedata::GameModule_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // github_2ecom_2fparalin_2fmodlock_2fproto_2fmodlock_2fgame_5fsignatures_2eproto_2epb_2eh
