package main

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
	"unicode"
)

// goPreamble opens the generated Go source with the entity root.
const goPreamble = `// Code generated by modlock-entitygen. DO NOT EDIT.

package entity

import "github.com/paralin/modlock/mod"

// CEntityInstance is the root of every entity class: one entity's handle.
type CEntityInstance struct {
	// Handle names the entity, as mod.Pawn.Entity does.
	Handle uint32
}

// NewCEntityInstance addresses the entity named by handle.
func NewCEntityInstance(handle uint32) CEntityInstance {
	return CEntityInstance{Handle: handle}
}
`

// goNumbers maps each numeric wire field type to its Go type.
var goNumbers = map[string]string{
	"int8":    "int8",
	"int16":   "int16",
	"int32":   "int32",
	"uint8":   "uint8",
	"uint16":  "uint16",
	"uint32":  "uint32",
	"int64":   "int64",
	"uint64":  "uint64",
	"float32": "float32",
	"float64": "float64",
	"handle":  "uint32",
}

// goFields maps each other wire field type to its field type in package
// entity.
var goFields = map[string]string{
	"bool":   "Bool",
	"string": "Text",
	"vector": "Vector",
}

// writeGo writes the entity classes as one Go source file of package entity.
// Each field is one method returning a value that gets and sets the field, so
// a setter adds no method to every class that inherits it.
func writeGo(s *schema, classes []*class) []byte {
	var out bytes.Buffer
	out.WriteString(goPreamble)
	for _, c := range classes[1:] {
		// Write the class and its constructor.
		fmt.Fprintf(&out, "\n// %s is the server's %s entity class.\n", c.name, c.name)
		fmt.Fprintf(&out, "type %s struct {\n\t%s\n}\n", c.name, c.base)
		fmt.Fprintf(&out, "\n// New%s addresses the %s named by handle.\n", c.name, c.name)
		fmt.Fprintf(&out, "func New%s(handle uint32) %s {\n\treturn %s{New%s(handle)}\n}\n", c.name, c.name, c.name, c.base)

		// A method may not share its name with the embedded base or hide the
		// root's Handle, and two fields may map to one method name; keep the
		// first.
		taken := map[string]bool{c.base: true, "Handle": true}
		for _, f := range s.readableFields(c) {
			method := goMethod(f.name)
			if taken[method] {
				continue
			}
			taken[method] = true
			typ, value := goField(c.name, f)
			fmt.Fprintf(&out, "\n// %s is %s.\n", method, f.name)
			fmt.Fprintf(&out, "func (e %s) %s() %s {\n\treturn %s\n}\n", c.name, method, typ, value)
		}
	}

	// Format the source, which the generator writes only in valid Go.
	formatted, err := format.Source(out.Bytes())
	if err != nil {
		panic(fmt.Sprintf("generated Go does not parse: %v", err))
	}
	return formatted
}

// goMethod returns the method name for a schema field name: the name without
// its m_ prefix, capitalized, so m_iHealth is IHealth.
func goMethod(field string) string {
	name := []rune(strings.TrimPrefix(field, "m_"))
	name[0] = unicode.ToUpper(name[0])
	if !unicode.IsLetter(name[0]) {
		return "F" + string(name)
	}
	return string(name)
}

// goField returns the type of field f of className and the expression that
// addresses it on entity e.
func goField(className string, f readable) (typ, value string) {
	constant := "mod.FieldType" + strings.ToUpper(f.wire[:1]) + f.wire[1:]
	field := fmt.Sprintf("Field{e.Handle, %q, %q, %s}", className, f.name, constant)
	switch {
	case f.angles:
		typ = "Angles"
	case f.target != "":
		typ = "Handle[" + f.target + "]"
		return typ, fmt.Sprintf("%s{%s, New%s}", typ, field, f.target)
	case goFields[f.wire] != "":
		typ = goFields[f.wire]
	default:
		typ = "Number[" + goNumbers[f.wire] + "]"
	}
	return typ, fmt.Sprintf("%s{%s}", typ, field)
}
