package main

import (
	"bytes"
	"fmt"
	"slices"
	"strings"
)

// luauPreamble opens the generated module with the accessors every class
// shares: an entity is a handle and its class name, and indexing it reads or
// writes the field of that name through the class chain. Each class's type
// extends its base's with an intersection; flattening the fields into every
// class instead makes the module seven times larger and no easier to check.
const luauPreamble = `--!strict
-- Code generated by modlock-entitygen. DO NOT EDIT.

local modlock = require("@modlock")

-- entities is the module's table. entities.new addresses an entity as a
-- class and entities.create creates one of a designer name. Both return any
-- and create takes untyped spawn keys, because the analyzer gives up on a
-- module whose table holds every class's type, so a mod names the type where
-- it keeps an entity or its keys:
--
--   local pawn: entities.CCitadelPlayerPawn = entities.new("CCitadelPlayerPawn", handle)
--   local keys: entities.CNPC_TrooperBossKeys = { LaneNum = 2 }
--   local boss: entities.CNPC_TrooperBoss? = entities.create("npc_trooper_boss", {
--   	position = { x = 0, y = 0, z = 0 },
--   	keys = keys,
--   })
local entities = {}

-- invalidHandle is the handle of no entity.
local invalidHandle = 0xffffffff

-- Field is one field or input a class declares. A field has its wire type,
-- and for a handle, the class of entity it names, or for a rotation, angles.
-- An input, which a method named after it sends, has its name and the case of
-- EntityValue it takes, if any.
type Field = {
	type: modlock.FieldType?,
	target: string?,
	angles: boolean?,
	input: string?,
	value: string?,
}

-- Class is one class's base, the fields it declares and the metatable its
-- instances share.
type Class = { base: string?, fields: { [string]: Field }, meta: any }

-- CEntityInstance is the root of every entity class: one entity's handle.
export type CEntityInstance = { handle: number }

-- classes describes every class, filled in below.
local classes: { [string]: Class } = {}

-- fieldTypes are the FieldTypes a field's accessors read directly.
local fieldTypes: { [string]: boolean } = {
	bool = true,
	float32 = true,
	float64 = true,
	handle = true,
	int16 = true,
	int32 = true,
	int64 = true,
	int8 = true,
	string = true,
	uint16 = true,
	uint32 = true,
	uint64 = true,
	uint8 = true,
	vector = true,
}

-- Hit is a field and the class in a chain that declares it.
type Hit = { owner: string, field: Field }

-- found caches each class's resolved fields, false for a field it lacks.
local found: { [string]: { [string]: Hit | false } } = {}

-- lookup walks className's chain for the class that declares name.
local function lookup(className: string, name: string): Hit | false
	local owner: string? = className
	while owner ~= nil do
		local field = classes[owner].fields[name]
		if field ~= nil then
			return { owner = owner, field = field }
		end
		owner = classes[owner].base
	end
	return false
end

-- resolve finds the class in className's chain that declares name, or nil
-- when none does.
local function resolve(className: string, name: string): (string?, Field?)
	local cache = found[className]
	if cache == nil then
		cache = {}
		found[className] = cache
	end
	local hit = cache[name]
	if hit == nil then
		hit = lookup(className, name)
		cache[name] = hit
	end
	if not hit then
		print(` + "`{className} has no field {name}`" + `)
		return nil, nil
	end
	return hit.owner, hit.field
end

-- new addresses the entity named by handle as an instance of className.
local function new(className: string, handle: number): any
	return setmetatable({ handle = handle }, classes[className].meta)
end

-- describe adds one class. Each of its fields maps to its FieldType, angles,
-- or the class of entity its handle names, and each input to the case of
-- EntityValue it sends, or to the empty string for none. Its instances read a
-- field by indexing and write one by assigning; a field the class lacks reads
-- as nil and ignores writes, after a line in the server log.
local function describe(className: string, base: string?, entries: { [string]: string }, inputs: { [string]: string }?)
	local fields: { [string]: Field } = {}
	for name, entry in entries do
		local field: Field = if entry == "angles"
			then { type = "vector", angles = true }
			elseif fieldTypes[entry] then { type = entry :: modlock.FieldType }
			else { type = "handle", target = entry }
		fields[name] = field
	end
	for input, case in inputs or {} do
		local field: Field = { input = input, value = if case == "" then nil else case }
		fields["input" .. input] = field
	end
	local meta = {
		__index = function(entity: any, name: string): any
			local owner, field = resolve(className, name)
			if owner == nil or field == nil then
				return nil
			end
			local input, case = field.input, field.value
			if input ~= nil then
				return function(_: any, value: any): boolean
					return modlock.fireInput(entity.handle, input, if case == nil then nil else { [case] = value } :: any)
				end
			end
			local value = modlock.readField(entity.handle, owner, name, field.type :: modlock.FieldType)
			if value == nil then
				return nil
			end
			if field.angles then
				local vector = value :: modlock.Vector
				return { pitch = vector.x, yaw = vector.y, roll = vector.z }
			end
			if field.target ~= nil then
				return if value == invalidHandle then nil else new(field.target, value :: number)
			end
			return value
		end,
		__newindex = function(entity: any, name: string, value: any)
			local owner, field = resolve(className, name)
			if owner == nil or field == nil or field.input ~= nil then
				return
			end
			if field.angles then
				value = { x = value.pitch, y = value.yaw, z = value.roll }
			elseif field.target ~= nil then
				value = if value == nil then invalidHandle else value.handle
			end
			modlock.writeField(entity.handle, owner, name, field.type :: modlock.FieldType, value)
		end,
	}
	classes[className] = { base = base, fields = fields, meta = meta }
end

describe("CEntityInstance", nil, {})

-- Spawn describes an entity entities.create creates: the options of modlock.createEntity but the designer name, with typed spawn key
-- values.
export type Spawn<Keys> = {
	-- subclass names the entity's game data entry, such as npc_boss_tier1 for
	-- the lane Guardian. An NPC needs one.
	subclass: string?,
	-- team is the entity's team number; 4 is neutral.
	team: number?,
	-- position is the entity's origin.
	position: modlock.Vector,
	-- facing is where the entity faces.
	facing: modlock.Angles?,
	-- keys are the entity's spawn key values, each typed as the entity reads
	-- it.
	keys: Keys?,
	-- keyValues are further key values, as modlock.createEntity takes them.
	keyValues: { modlock.KeyValue }?,
	-- fields are schema fields written before the entity spawns.
	fields: { modlock.FieldWrite }?,
}

-- KeyMap is one data description: its base and how each key it adds
-- travels, as a case of EntityValue or as angles.
type KeyMap = { base: string?, keys: { [string]: string } }

-- keyMaps describes every data description, filled in below.
local keyMaps: { [string]: KeyMap } = {}

-- keyValue encodes one typed key value, whose type map or a base gives.
local function keyValue(map: string?, key: string, value: any): modlock.KeyValue?
	while map ~= nil do
		local case = keyMaps[map].keys[key]
		if case == "angles" then
			return { key = key, value = { vector = { x = value.pitch, y = value.yaw, z = value.roll } } }
		elseif case ~= nil then
			return { key = key, value = { [case] = value } :: any }
		end
		map = keyMaps[map].base
	end
	return nil
end

-- new addresses the entity named by handle as an instance of className.
function entities.new(className: ClassName, handle: number): any
	return new(className, handle)
end
`

// luauCreate closes the module with entities.create, which reads the
// designers table written before it.
const luauCreate = `
-- DesignerName is a designer name entities.create can create.
export type DesignerName = keyof<typeof(designers)>

-- create creates an entity of designerName from options and addresses it as
-- the class that implements it, or returns nil when the host refuses.
function entities.create(designerName: DesignerName, options: Spawn<any>): any
	local entry = designers[designerName]
	local className, map, subclass = entry[1], entry[2], entry[3]
	local keyValues = table.clone(options.keyValues or {})
	for key, value in (options.keys or {}) :: { [string]: any } do
		local encoded = keyValue(map, key, value)
		if encoded ~= nil then
			table.insert(keyValues, encoded)
		end
	end
	local handle = modlock.createEntity({
		designerName = designerName,
		subclass = options.subclass or subclass or "",
		team = options.team or 0,
		position = options.position,
		facing = options.facing,
		keyValues = keyValues,
		fields = options.fields,
	})
	return if handle == nil then nil else new(className, handle)
end
`

// luauValues maps each value to the type a key or input takes.
var luauValues = map[value]string{
	"boolean": "boolean",
	"integer": "number",
	"number":  "number",
	"text":    "string",
	"vector":  "modlock.Vector",
	"color":   "number",
	"angles":  "modlock.Angles",
}

// luauTypes maps each wire field type to the type its field holds.
var luauTypes = map[string]string{
	"bool":    "boolean",
	"int8":    "number",
	"int16":   "number",
	"int32":   "number",
	"uint8":   "number",
	"uint16":  "number",
	"uint32":  "number",
	"int64":   "number",
	"uint64":  "number",
	"float32": "number",
	"float64": "number",
	"vector":  "modlock.Vector",
	"handle":  "number",
	"string":  "string",
}

// writeLuau writes the entity classes as one Luau module: a type for each
// class and its fields and inputs described for the shared accessors; then
// each data description's key value type; then the class and designer names
// entities.new and entities.create take.
func writeLuau(s *schema, classes []*class, e *entities, c *console) map[string][]byte {
	// Open with the shared accessors.
	var out bytes.Buffer
	out.WriteString(luauPreamble)

	// visible maps each class to the type of every field it has, its own and
	// inherited, so a class skips a field whose type conflicts with an
	// inherited one of the same name. The root's handle conflicts with every
	// field.
	visible := map[string]map[string]string{entityRoot: {"handle": ""}}
	for _, c := range classes[1:] {
		own := map[string]string{}
		for name, typ := range visible[c.base] {
			own[name] = typ
		}
		visible[c.name] = own

		// Gather the fields and inputs the class adds, in declaration order.
		var types, fields, inputs []string
		for _, f := range s.readableFields(c) {
			typ := luauType(f.kind)
			if inherited, ok := own[f.name]; ok && inherited != typ {
				continue
			}
			own[f.name] = typ
			types = append(types, fmt.Sprintf("\t%s: %s?,\n", f.name, typ))
			fields = append(fields, fmt.Sprintf("\t%s = %q,\n", f.name, luauEntry(f)))
		}
		for _, in := range e.inputs[c.name] {
			method := "input" + in.name
			if inherited, ok := own[method]; ok && inherited != string(in.value) {
				continue
			}
			own[method] = string(in.value)
			parameter := ""
			if in.value != "" {
				parameter = ", value: " + luauValues[in.value]
			}
			if doc := sentence(in.description); doc != "" {
				types = append(types, wrap("\t-- ", doc))
			}
			types = append(types, fmt.Sprintf("\t%s: (self: any%s) -> boolean,\n", method, parameter))
			inputs = append(inputs, fmt.Sprintf("\t%s = %q,\n", in.name, in.value))
		}

		// Write the type and the description.
		out.WriteString("\n")
		if len(types) == 0 {
			fmt.Fprintf(&out, "export type %s = %s\n", c.name, c.base)
		} else {
			fmt.Fprintf(&out, "export type %s = %s & {\n%s}\n", c.name, c.base, strings.Join(types, ""))
		}
		fmt.Fprintf(&out, "describe(%q, %q, %s", c.name, c.base, luauTable(fields))
		if len(inputs) != 0 {
			fmt.Fprintf(&out, ", %s", luauTable(inputs))
		}
		out.WriteString(")\n")
	}

	// Describe each data description's keys as a type and as the table create
	// reads.
	for _, m := range e.keyMaps {
		var types, cases []string
		for _, k := range m.keys {
			types = append(types, fmt.Sprintf("\t%s: %s?,\n", k.name, luauValues[k.value]))
			cases = append(cases, fmt.Sprintf("%s = %q", k.name, k.value))
		}
		base, own := "nil", "{\n"+strings.Join(types, "")+"}"
		if m.base != nil {
			base = fmt.Sprintf("%q", m.base.name)
			own = m.base.name + "Keys & " + own
			if len(types) == 0 {
				own = m.base.name + "Keys"
			}
		}
		out.WriteString("\n")
		fmt.Fprintf(&out, "export type %sKeys = %s\n", m.name, own)
		fmt.Fprintf(&out, "keyMaps.%s = { base = %s, keys = { %s } }\n", m.name, base, strings.Join(cases, ", "))
	}

	// Name every class, and map each designer name to its class and data
	// description, for entities.new and entities.create.
	names := make([]string, len(classes))
	for i, c := range classes {
		names[i] = c.name
	}
	out.WriteString(luauUnion("ClassName", names))
	out.WriteString("\n-- designers maps each designer name to the class that implements it, its\n-- data description and the subclass it needs, if any.\nlocal designers = {\n")
	for _, d := range e.designers {
		if d.subclass == "" {
			fmt.Fprintf(&out, "\t%s = { %q, %q },\n", d.name, d.class, d.keys.name)
		} else {
			fmt.Fprintf(&out, "\t%s = { %q, %q, %q },\n", d.name, d.class, d.keys.name, d.subclass)
		}
	}
	out.WriteString("}\n")
	out.WriteString(luauCreate)
	out.WriteString("\nreturn entities\n")
	return map[string][]byte{"entities.luau": out.Bytes(), "console.luau": luauConsole(c)}
}

// luauConsolePreamble opens the console module.
const luauConsolePreamble = `--!strict
-- Code generated by modlock-entitygen. DO NOT EDIT.

local modlock = require("@modlock")

-- console sets the server's console variables and runs its console commands
-- through modlock.serverCommand, which may set a development-only or
-- cheat-protected variable.
local console = {}
`

// luauConsoleFunctions closes the console module with a setter per value
// type and run. One set overloaded by value type is too complex for the
// analyzer.
const luauConsoleFunctions = `
-- set sets the console variable name to value. It returns false when the
-- host refuses.
local function set(name: string, value: boolean | number | string): boolean
	local text = if type(value) == "boolean"
		then (if value then "1" else "0")
		elseif type(value) == "string" then ` + "`\"{value}\"`" + `
		else tostring(value)
	return modlock.serverCommand(` + "`{name} {text}`" + `)
end

-- setBoolean sets the boolean console variable name to value.
function console.setBoolean(name: BooleanVariable, value: boolean): boolean
	return set(name, value)
end

-- setNumber sets the numeric console variable name to value.
function console.setNumber(name: NumberVariable, value: number): boolean
	return set(name, value)
end

-- setString sets the string console variable name to value.
function console.setString(name: StringVariable, value: string): boolean
	return set(name, value)
end

-- run runs the console command name with args, each one word of the line.
function console.run(name: CommandName, ...: string): boolean
	return modlock.serverCommand(table.concat({ name, ... }, " "))
end

return console
`

// luauConsole writes the console module: a union of the variables of each
// value type, which its setter takes, and one of the commands, which run
// takes.
func luauConsole(c *console) []byte {
	var out bytes.Buffer
	out.WriteString(luauConsolePreamble)
	variables := map[string][]string{}
	for _, v := range c.variables {
		variables[v.scriptType()] = append(variables[v.scriptType()], v.name)
	}
	for _, typ := range []string{"boolean", "number", "string"} {
		out.WriteString(luauUnion(strings.ToUpper(typ[:1])+typ[1:]+"Variable", variables[typ]))
	}
	commands := make([]string, len(c.commands))
	for i, command := range c.commands {
		commands[i] = command.name
	}
	out.WriteString(luauUnion("CommandName", commands))
	out.WriteString(luauConsoleFunctions)
	return out.Bytes()
}

// luauType returns the type a field of kind k holds.
func luauType(k kind) string {
	switch {
	case k.angles:
		return "modlock.Angles"
	case k.target != "":
		return k.target
	}
	return luauTypes[k.wire]
}

// luauEntry returns field f's entry in its class's description: angles, the
// class its handle names, or its FieldType.
func luauEntry(f readable) string {
	switch {
	case f.angles:
		return "angles"
	case f.target != "":
		return f.target
	}
	return f.wire
}

// luauTable returns a table constructor of entries, each a line.
func luauTable(entries []string) string {
	if len(entries) == 0 {
		return "{}"
	}
	return "{\n" + strings.Join(entries, "") + "}"
}

// luauUnionLength is the most members one union type holds; the analyzer
// refuses a longer type.
const luauUnionLength = 400

// luauUnion returns the exported type name, a union of the string singleton
// types of members, joined from unions of at most luauUnionLength members.
func luauUnion(name string, members []string) string {
	var out strings.Builder
	var parts []string
	for chunk := range slices.Chunk(members, luauUnionLength) {
		part := fmt.Sprintf("%s%d", name, len(parts))
		parts = append(parts, part)
		fmt.Fprintf(&out, "\ntype %s =\n", part)
		for _, member := range chunk {
			fmt.Fprintf(&out, "\t| %q\n", member)
		}
	}
	fmt.Fprintf(&out, "\nexport type %s = %s\n", name, strings.Join(parts, " | "))
	return out.String()
}
