package main

import (
	"bytes"
	"fmt"
	"strings"
)

// luauPreamble opens the generated module with the accessors every class
// shares: an entity is a handle and its class name, and indexing it reads or
// writes the field of that name through the class chain. Each class's type
// extends its base's with an intersection; flattening the fields into every
// class instead makes the module seven times larger and no easier to check.
const luauPreamble = `--!strict
-- Code generated by modlock-entitygen. DO NOT EDIT.

local modlock = require("@modlock")

-- entities is the module's table, which every class constructor joins. A
-- constructor returns any: the analyzer gives up on a module whose table
-- holds every class's type, so a mod names the type where it keeps one:
--
--   local pawn: entities.CCitadelPlayerPawn = entities.CCitadelPlayerPawn(handle)
local entities = {}

-- invalidHandle is the handle of no entity.
local invalidHandle = 0xffffffff

-- Field is one field a class declares: its wire type, and for a handle, the
-- class of entity it names, or for a rotation, angles.
type Field = { type: modlock.FieldType, target: string?, angles: boolean? }

-- Class is one class's base, the fields it declares and the metatable its
-- instances share.
type Class = { base: string?, fields: { [string]: Field }, meta: any }

-- CEntityInstance is the root of every entity class: one entity's handle.
export type CEntityInstance = { handle: number }

-- classes describes every class, filled in below.
local classes: { [string]: Class } = {}

-- Hit is a field and the class in a chain that declares it.
type Hit = { owner: string, field: Field }

-- found caches each class's resolved fields, false for a field it lacks.
local found: { [string]: { [string]: Hit | false } } = {}

-- lookup walks className's chain for the class that declares name.
local function lookup(className: string, name: string): Hit | false
	local owner: string? = className
	while owner ~= nil do
		local field = classes[owner].fields[name]
		if field ~= nil then
			return { owner = owner, field = field }
		end
		owner = classes[owner].base
	end
	return false
end

-- resolve finds the class in className's chain that declares name, or nil
-- when none does.
local function resolve(className: string, name: string): (string?, Field?)
	local cache = found[className]
	if cache == nil then
		cache = {}
		found[className] = cache
	end
	local hit = cache[name]
	if hit == nil then
		hit = lookup(className, name)
		cache[name] = hit
	end
	if not hit then
		print(` + "`{className} has no field {name}`" + `)
		return nil, nil
	end
	return hit.owner, hit.field
end

-- new addresses the entity named by handle as an instance of className.
local function new(className: string, handle: number): any
	return setmetatable({ handle = handle }, classes[className].meta)
end

-- describe adds one class. Its instances read a field by indexing and write
-- one by assigning; a field the class lacks reads as nil and ignores writes,
-- after a line in the server log.
local function describe(className: string, base: string?, fields: { [string]: Field })
	local meta = {
		__index = function(entity: any, name: string): any
			local owner, field = resolve(className, name)
			if owner == nil or field == nil then
				return nil
			end
			local value = modlock.readField(entity.handle, owner, name, field.type)
			if value == nil then
				return nil
			end
			if field.angles then
				local vector = value :: modlock.Vector
				return { pitch = vector.x, yaw = vector.y, roll = vector.z }
			end
			if field.target ~= nil then
				return if value == invalidHandle then nil else new(field.target, value :: number)
			end
			return value
		end,
		__newindex = function(entity: any, name: string, value: any)
			local owner, field = resolve(className, name)
			if owner == nil or field == nil then
				return
			end
			if field.angles then
				value = { x = value.pitch, y = value.yaw, z = value.roll }
			elseif field.target ~= nil then
				value = if value == nil then invalidHandle else value.handle
			end
			modlock.writeField(entity.handle, owner, name, field.type, value)
		end,
	}
	classes[className] = { base = base, fields = fields, meta = meta }
end

describe("CEntityInstance", nil, {})
`

// luauTypes maps each wire field type to the type its field holds.
var luauTypes = map[string]string{
	"bool":    "boolean",
	"int8":    "number",
	"int16":   "number",
	"int32":   "number",
	"uint8":   "number",
	"uint16":  "number",
	"uint32":  "number",
	"int64":   "number",
	"uint64":  "number",
	"float32": "number",
	"float64": "number",
	"vector":  "modlock.Vector",
	"handle":  "number",
	"string":  "string",
}

// writeLuau writes the entity classes as one Luau module: a type for each
// class, its fields described for the shared accessors, and its constructor.
func writeLuau(s *schema, classes []*class) []byte {
	// Open with the shared accessors.
	var out bytes.Buffer
	out.WriteString(luauPreamble)

	// visible maps each class to the type of every field it has, its own and
	// inherited, so a class skips a field whose type conflicts with an
	// inherited one of the same name. The root's handle conflicts with every
	// field.
	visible := map[string]map[string]string{entityRoot: {"handle": ""}}
	for _, c := range classes[1:] {
		own := map[string]string{}
		for name, typ := range visible[c.base] {
			own[name] = typ
		}
		visible[c.name] = own

		// Gather the fields the class adds, in declaration order.
		var types, descriptions []string
		for _, f := range s.readableFields(c) {
			typ := luauType(f.kind)
			if inherited, ok := own[f.name]; ok && inherited != typ {
				continue
			}
			own[f.name] = typ
			types = append(types, fmt.Sprintf("\t%s: %s?,\n", f.name, typ))
			descriptions = append(descriptions, fmt.Sprintf("\t%s = %s,\n", f.name, luauField(f)))
		}

		// Write the type, the description and the constructor.
		fmt.Fprintf(&out, "\n-- %s is the server's %s entity class.\n", c.name, c.name)
		if len(types) == 0 {
			fmt.Fprintf(&out, "export type %s = %s\n", c.name, c.base)
			fmt.Fprintf(&out, "describe(%q, %q, {})\n", c.name, c.base)
		} else {
			fmt.Fprintf(&out, "export type %s = %s & {\n%s}\n", c.name, c.base, strings.Join(types, ""))
			fmt.Fprintf(&out, "describe(%q, %q, {\n%s})\n", c.name, c.base, strings.Join(descriptions, ""))
		}
		fmt.Fprintf(&out, "function entities.%s(handle: number): any\n\treturn new(%q, handle)\nend\n", c.name, c.name)
	}
	out.WriteString("\nreturn entities\n")
	return out.Bytes()
}

// luauType returns the type a field of kind k holds.
func luauType(k kind) string {
	switch {
	case k.angles:
		return "modlock.Angles"
	case k.target != "":
		return k.target
	}
	return luauTypes[k.wire]
}

// luauField returns the description of field f that the accessors read.
func luauField(f readable) string {
	parts := []string{fmt.Sprintf("type = %q", f.wire)}
	if f.target != "" {
		parts = append(parts, fmt.Sprintf("target = %q", f.target))
	}
	if f.angles {
		parts = append(parts, "angles = true")
	}
	return "{ " + strings.Join(parts, ", ") + " }"
}
