package main

import (
	"bytes"
	"fmt"
	"maps"
	"slices"
	"strings"
)

// typeScriptPreamble opens the generated module with the root class and the
// helpers that install accessors and create entities.
const typeScriptPreamble = `// Code generated by modlock-entitygen. DO NOT EDIT.

import {
  createEntity,
  fireInput,
  readField,
  writeField,
  type Angles,
  type EntityOptions,
  type EntityValue,
  type FieldType,
  type KeyValue,
  type Vector,
} from 'modlock'

/** invalidHandle is the handle of no entity. */
const invalidHandle = 0xffffffff

/** CEntityInstance is the root of every entity class: one entity's handle. */
export class CEntityInstance {
  /** handle names the entity, as Pawn.entity does. */
  readonly handle: number

  constructor(handle: number) {
    this.handle = handle
  }
}

/** Class makes an entity class's instance from a handle. */
type Class<C = CEntityInstance> = new (handle: number) => C

/** classes maps each class name to its class, for the handle fields that name it. */
const classes: Record<string, Class> = {}

/**
 * define installs the field accessors and input methods of make, the class
 * named className. Each field maps to its FieldType, angles, or the class name
 * of the entity its handle names. Each input maps to the case of EntityValue
 * it sends, or to the empty string for none.
 */
function define(
  make: Class,
  className: string,
  fields: Readonly<Record<string, string>>,
  inputs: Readonly<Record<string, string>> = {},
): void {
  classes[className] = make
  for (const [field, type] of Object.entries(fields)) {
    Object.defineProperty(make.prototype, field, accessor(className, field, type))
  }
  for (const [input, value] of Object.entries(inputs)) {
    Object.defineProperty(make.prototype, 'input' + input, {
      value(this: CEntityInstance, argument?: unknown): boolean {
        return fireInput(this.handle, input, value ? ({ [value]: argument } as EntityValue) : undefined)
      },
    })
  }
}

/**
 * accessor returns the getter and setter of one field of className. Setting
 * undefined leaves a field unchanged, but clears a handle field.
 */
function accessor(className: string, field: string, type: string): PropertyDescriptor {
  if (type === 'angles') {
    return {
      get(this: CEntityInstance): Angles | undefined {
        const value = readField(this.handle, className, field, 'vector') as Vector | undefined
        return value && { pitch: value.x, yaw: value.y, roll: value.z }
      },
      set(this: CEntityInstance, value: Angles | undefined) {
        if (value) {
          writeField(this.handle, className, field, 'vector', { x: value.pitch, y: value.yaw, z: value.roll })
        }
      },
    }
  }
  if (!fieldTypes.has(type)) {
    return {
      get(this: CEntityInstance): CEntityInstance | undefined {
        const target = readField(this.handle, className, field, 'handle') as number | undefined
        const make = classes[type]
        return target === undefined || target === invalidHandle || !make ? undefined : new make(target)
      },
      set(this: CEntityInstance, value: CEntityInstance | undefined) {
        writeField(this.handle, className, field, 'handle', value?.handle ?? invalidHandle)
      },
    }
  }
  return {
    get(this: CEntityInstance) {
      return readField(this.handle, className, field, type as FieldType)
    },
    set(this: CEntityInstance, value: never) {
      if (value !== undefined) {
        writeField(this.handle, className, field, type as FieldType, value)
      }
    },
  }
}

/**
 * KeyType is how one spawn key value travels: as a case of EntityValue, or as
 * angles, which travel as a vector of pitch, yaw and roll.
 */
type KeyType = 'boolean' | 'integer' | 'number' | 'text' | 'vector' | 'color' | 'angles'

/** KeyTypes maps each KeyType to the type of the values it takes. */
interface KeyTypes {
  boolean: boolean
  integer: number
  number: number
  text: string
  vector: Vector
  color: number
  angles: Angles
}

/**
 * KeyMap is one data description: its base and the type of each key it adds.
 * Keys is the type of the key values it and its bases take.
 */
type KeyMap<Keys = unknown> = readonly [base: KeyMap | undefined, keys: Readonly<Record<string, KeyType>>] & {
  readonly spawnKeys?: Keys
}

/** KeysOf is the type of the key values map takes. */
type KeysOf<Map> = Map extends KeyMap<infer Keys> ? Keys : never

/** FieldTypes maps each entry of a class's field table to the type it holds. */
interface FieldTypes {
  bool: boolean
  int8: number
  int16: number
  int32: number
  uint8: number
  uint16: number
  uint32: number
  int64: bigint
  uint64: bigint
  float32: number
  float64: number
  vector: Vector
  handle: number
  string: string
  angles: Angles
}

/** FieldOf is the type a field of table entry T holds. */
type FieldOf<T> = T extends keyof FieldTypes ? FieldTypes[T] : T extends keyof Targets ? Targets[T] : never

/**
 * Fields declares the fields a table installs. A string field is read only,
 * since the host cannot write text.
 */
type Fields<T> = {
  -readonly [K in keyof T as T[K] extends 'string' ? never : K]: FieldOf<T[K]> | undefined
} & { readonly [K in keyof T as T[K] extends 'string' ? K : never]: string | undefined }

/** Inputs declares the input methods a table installs. */
type Inputs<T> = {
  readonly [K in keyof T as ` + "`input${K & string}`" + `]: T[K] extends keyof KeyTypes
    ? (value: KeyTypes[T[K]]) => boolean
    : () => boolean
}

/** Typed is the type of the key values a table of key types takes. */
type Typed<Keys extends Readonly<Record<string, KeyType>>> = { readonly [Key in keyof Keys]?: KeyTypes[Keys[Key]] }

/**
 * Spawn describes an entity create creates: the options of createEntity but
 * the designer name, with typed spawn key values.
 */
export type Spawn<Keys> = Omit<EntityOptions, 'designerName' | 'subclass' | 'team'> & {
  /**
   * subclass names the entity's game data entry, such as npc_boss_tier1 for
   * the lane Guardian. An NPC needs one.
   */
  subclass?: string
  /** team is the entity's team number; 4 is neutral. */
  team?: number
  /** keys are the entity's spawn key values, each typed as the entity reads it. */
  keys?: Keys
}

/** keyValue encodes one typed key value, whose type map or a base gives. */
function keyValue(map: KeyMap | undefined, key: string, value: unknown): KeyValue | undefined {
  for (; map; map = map[0]) {
    const type = map[1][key]
    if (type === 'angles') {
      const angles = value as Angles
      return { key, value: { vector: { x: angles.pitch, y: angles.yaw, z: angles.roll } } }
    }
    if (type) {
      return { key, value: { [type]: value } as EntityValue }
    }
  }
  return undefined
}

/** DesignerName is a designer name create can create. */
export type DesignerName = keyof typeof designers

/** DesignerClass is the class that implements designer name D. */
export type DesignerClass<D extends DesignerName> = InstanceType<(typeof designers)[D][0]>

/** DesignerKeys is the type of the spawn key values of designer name D. */
export type DesignerKeys<D extends DesignerName> = KeysOf<(typeof designers)[D][1]>

/**
 * create creates an entity of designerName from options and addresses it as
 * the class that implements it, or returns undefined when the host refuses.
 */
export function create<D extends DesignerName>(
  designerName: D,
  options: Spawn<DesignerKeys<D>>,
): DesignerClass<D> | undefined {
  const [make, map] = designers[designerName] as readonly [Class, KeyMap]
  const keyValues = [...(options.keyValues ?? [])]
  for (const [key, value] of Object.entries(options.keys ?? {})) {
    const encoded = value === undefined ? undefined : keyValue(map, key, value)
    if (encoded) {
      keyValues.push(encoded)
    }
  }
  const handle = createEntity({
    ...options,
    designerName,
    subclass: options.subclass ?? '',
    team: options.team ?? 0,
    keyValues,
  })
  return handle === undefined ? undefined : (new make(handle) as DesignerClass<D>)
}
`

// typeScriptTypes maps each wire field type to the type its getter returns.
var typeScriptTypes = map[string]string{
	"bool":    "boolean",
	"int8":    "number",
	"int16":   "number",
	"int32":   "number",
	"uint8":   "number",
	"uint16":  "number",
	"uint32":  "number",
	"int64":   "bigint",
	"uint64":  "bigint",
	"float32": "number",
	"float64": "number",
	"vector":  "Vector",
	"handle":  "number",
	"string":  "string",
}

// writeTypeScript writes the entity classes as one TypeScript module. Each
// class's fields and inputs are two constant tables: define installs them as
// accessors and methods, and Fields and Inputs map them to the interface
// merged with the class, so a field costs one table entry. The designer names
// follow as one table create reads.
func writeTypeScript(s *schema, classes []*class, e *entities) map[string][]byte {
	// Open with the imports and shared helpers, and the field types the
	// accessors read directly.
	var out bytes.Buffer
	out.WriteString(typeScriptPreamble)
	wires := slices.Sorted(maps.Keys(typeScriptTypes))
	fmt.Fprintf(&out, "\n/** fieldTypes are the FieldTypes a field's accessor reads directly. */\nconst fieldTypes: ReadonlySet<string> = new Set(['%s'])\n", strings.Join(wires, "', '"))

	// getters maps each class to the type of every getter it has, its own
	// and inherited, so a class skips a field whose type conflicts with an
	// inherited getter of the same name. The root's handle conflicts with
	// every field.
	getters := map[string]map[string]string{entityRoot: {"handle": ""}}
	targets := map[string]bool{}
	for _, c := range classes[1:] {
		own := maps.Clone(getters[c.base])
		getters[c.name] = own

		// Gather the tables of fields and inputs.
		var fields, inputs []string
		for _, f := range s.readableFields(c) {
			typ := typeScriptType(f.kind)
			if inherited, ok := own[f.name]; ok && inherited != typ {
				continue
			}
			own[f.name] = typ
			if f.target != "" {
				targets[f.target] = true
			}
			fields = append(fields, fmt.Sprintf("%s: '%s'", f.name, typeScriptEntry(f)))
		}
		for _, in := range e.inputs[c.name] {
			inputs = append(inputs, typeScriptInput(in))
		}

		// Write the tables, the class, the interface they declare and the
		// call that installs them.
		var bases []string
		arguments := "{}"
		out.WriteString("\n")
		if len(fields) != 0 {
			fmt.Fprintf(&out, "const fields%s = %s as const\n", c.name, typeScriptTable(fields))
			bases = append(bases, "Fields<typeof fields"+c.name+">")
			arguments = "fields" + c.name
		}
		if len(inputs) != 0 {
			fmt.Fprintf(&out, "const inputs%s = {\n%s} as const\n", c.name, strings.Join(inputs, ""))
			bases = append(bases, "Inputs<typeof inputs"+c.name+">")
			arguments += ", inputs" + c.name
		}
		fmt.Fprintf(&out, "export class %s extends %s {}\n", c.name, c.base)
		if len(bases) != 0 {
			fmt.Fprintf(&out, "export interface %s extends %s {}\n", c.name, strings.Join(bases, ", "))
		}
		fmt.Fprintf(&out, "define(%s, '%s', %s)\n", c.name, c.name, arguments)
	}

	// Name each class a handle field names, for FieldOf.
	out.WriteString("\n/** Targets maps each class a handle field names to its instances. */\ninterface Targets {\n")
	for _, target := range slices.Sorted(maps.Keys(targets)) {
		fmt.Fprintf(&out, "  %s: %s\n", target, target)
	}
	out.WriteString("}\n")

	// Write each data description's keys after its base's: the table of key
	// types create reads, the type it gives, and the map that joins them.
	for _, m := range e.keyMaps {
		var types, bases []string
		for _, k := range m.keys {
			types = append(types, fmt.Sprintf("%s: '%s'", k.name, k.value))
		}
		base, table := "undefined", "{}"
		if m.base != nil {
			base = "keys" + m.base.name
			bases = append(bases, m.base.name+"Keys")
		}
		out.WriteString("\n")
		if len(types) != 0 {
			table = "table" + m.name
			bases = append(bases, "Typed<typeof "+table+">")
			fmt.Fprintf(&out, "const %s = %s as const\n", table, typeScriptTable(types))
		}
		if len(bases) == 0 {
			fmt.Fprintf(&out, "export interface %sKeys {}\n", m.name)
		} else {
			fmt.Fprintf(&out, "export interface %sKeys extends %s {}\n", m.name, strings.Join(bases, ", "))
		}
		fmt.Fprintf(&out, "const keys%s: KeyMap<%sKeys> = [%s, %s]\n", m.name, m.name, base, table)
	}

	// Write the designer names, each with its class and key value table.
	out.WriteString("\n/** designers maps each designer name to its class and key value table. */\nconst designers = {\n")
	for _, d := range e.designers {
		fmt.Fprintf(&out, "  %s: [%s, keys%s],\n", d.name, d.class, d.keys.name)
	}
	out.WriteString("} as const\n")
	return map[string][]byte{"": out.Bytes()}
}

// typeScriptTable returns an object literal of entries, each a line, as the
// formatter writes it.
func typeScriptTable(entries []string) string {
	if len(entries) == 0 {
		return "{}"
	}
	return "{\n  " + strings.Join(entries, ",\n  ") + ",\n}"
}

// typeScriptEntry returns field f's entry in its class's table: angles, the
// class its handle names, or its FieldType.
func typeScriptEntry(f readable) string {
	switch {
	case f.angles:
		return "angles"
	case f.target != "":
		return f.target
	}
	return f.wire
}

// typeScriptInput returns input in's entry in its class's table of inputs:
// the case of EntityValue it sends, or the empty string for none.
func typeScriptInput(in input) string {
	entry := fmt.Sprintf("  %s: '%s',\n", in.name, in.value)
	doc := in.doc()
	switch {
	case doc == "":
		return entry
	case len(doc) <= 70:
		return "  /** " + doc + " */\n" + entry
	}
	return "  /**\n" + wrap("   * ", doc) + "   */\n" + entry
}

// typeScriptType returns the type a getter for a field of kind k returns.
func typeScriptType(k kind) string {
	switch {
	case k.angles:
		return "Angles"
	case k.target != "":
		return k.target
	}
	return typeScriptTypes[k.wire]
}
