package main

import (
	"bytes"
	"fmt"
	"strings"
)

// typeScriptPreamble opens the generated module with the readers its
// getters share.
const typeScriptPreamble = `// Code generated by modlock-entitygen. DO NOT EDIT.

import { readField, type Angles, type FieldType, type Vector } from 'modlock'

/** invalidHandle is the handle of no entity. */
const invalidHandle = 0xffffffff

/** read reads one field of an entity as the type its getter declares. */
function read<T>(handle: number, className: string, field: string, type: FieldType): T | undefined {
  return readField(handle, className, field, type) as T | undefined
}

/** angles reads a rotation field. */
function angles(handle: number, className: string, field: string): Angles | undefined {
  const value = read<Vector>(handle, className, field, 'vector')
  return value && { pitch: value.x, yaw: value.y, roll: value.z }
}

/** entity reads a handle field as the class of entity it names. */
function entity<C>(
  make: new (handle: number) => C,
  handle: number,
  className: string,
  field: string,
): C | undefined {
  const target = read<number>(handle, className, field, 'handle')
  return target === undefined || target === invalidHandle ? undefined : new make(target)
}

/** CEntityInstance is the root of every entity class: one entity's handle. */
export class CEntityInstance {
  /** handle names the entity, as Pawn.entity does. */
  readonly handle: number

  constructor(handle: number) {
    this.handle = handle
  }
}
`

// typeScriptTypes maps each wire field type to the type its getter returns.
var typeScriptTypes = map[string]string{
	"bool":    "boolean",
	"int8":    "number",
	"int16":   "number",
	"int32":   "number",
	"uint8":   "number",
	"uint16":  "number",
	"uint32":  "number",
	"int64":   "bigint",
	"uint64":  "bigint",
	"float32": "number",
	"float64": "number",
	"vector":  "Vector",
	"handle":  "number",
	"string":  "string",
}

// writeTypeScript writes the entity classes as one TypeScript module.
func writeTypeScript(s *schema, classes []*class) []byte {
	var out bytes.Buffer
	out.WriteString(typeScriptPreamble)

	// getters maps each class to the type of every getter it has, its own
	// and inherited, so a class skips a field whose type conflicts with an
	// inherited getter of the same name. The root's handle conflicts with
	// every field.
	getters := map[string]map[string]string{entityRoot: {"handle": ""}}
	for _, c := range classes[1:] {
		own := map[string]string{}
		for name, typ := range getters[c.base] {
			own[name] = typ
		}
		getters[c.name] = own

		fmt.Fprintf(&out, "\n/** %s is the server's %s entity class. */\n", c.name, c.name)
		var methods []string
		for _, f := range s.readableFields(c) {
			typ := typeScriptType(f.kind)
			if inherited, ok := own[f.name]; ok && inherited != typ {
				continue
			}
			own[f.name] = typ
			methods = append(methods, fmt.Sprintf("  get %s(): %s | undefined {\n    return %s\n  }\n", f.name, typ, typeScriptRead(c.name, f)))
		}
		if len(methods) == 0 {
			fmt.Fprintf(&out, "export class %s extends %s {}\n", c.name, c.base)
			continue
		}
		fmt.Fprintf(&out, "export class %s extends %s {\n%s}\n", c.name, c.base, strings.Join(methods, "\n"))
	}
	return out.Bytes()
}

// typeScriptType returns the type a getter for a field of kind k returns.
func typeScriptType(k kind) string {
	switch {
	case k.angles:
		return "Angles"
	case k.target != "":
		return k.target
	}
	return typeScriptTypes[k.wire]
}

// typeScriptRead returns the expression that reads field f of className.
func typeScriptRead(className string, f readable) string {
	switch {
	case f.angles:
		return fmt.Sprintf("angles(this.handle, '%s', '%s')", className, f.name)
	case f.target != "":
		return fmt.Sprintf("entity(%s, this.handle, '%s', '%s')", f.target, className, f.name)
	}
	return fmt.Sprintf("read<%s>(this.handle, '%s', '%s', '%s')", typeScriptTypes[f.wire], className, f.name, f.wire)
}
