// @generated by protoc-gen-es-lite unknown with parameter "target=ts,ts_nocheck=false"
// @generated from file github.com/paralin/modlock/proto/modlock/dump/dump.proto (package modlock.dump, syntax proto3)
/* eslint-disable */

import { createEnumType } from "@aptre/protobuf-es-lite/enum";
import type { MessageType } from "@aptre/protobuf-es-lite/message";
import { createMessageType } from "@aptre/protobuf-es-lite/message";
import { ScalarType } from "@aptre/protobuf-es-lite/scalar";
import type { PartialFieldInfo } from "@aptre/protobuf-es-lite/field";

export const protobufPackage = "modlock.dump";

/**
 * KeyType is a data description field's type. Each known value is the game's
 * own field type plus one.
 *
 * @generated from enum modlock.dump.KeyType
 */
export enum KeyType {
  /**
   * KEY_TYPE_UNKNOWN is a value the dump does not know.
   *
   * @generated from enum value: KEY_TYPE_UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * KEY_TYPE_VOID carries no value.
   *
   * @generated from enum value: KEY_TYPE_VOID = 1;
   */
  VOID = 1,

  /**
   * KEY_TYPE_FLOAT32 is a 32-bit float.
   *
   * @generated from enum value: KEY_TYPE_FLOAT32 = 2;
   */
  FLOAT32 = 2,

  /**
   * KEY_TYPE_STRING is a symbol string.
   *
   * @generated from enum value: KEY_TYPE_STRING = 3;
   */
  STRING = 3,

  /**
   * KEY_TYPE_VECTOR is a three-float vector.
   *
   * @generated from enum value: KEY_TYPE_VECTOR = 4;
   */
  VECTOR = 4,

  /**
   * KEY_TYPE_QUATERNION is a four-float quaternion.
   *
   * @generated from enum value: KEY_TYPE_QUATERNION = 5;
   */
  QUATERNION = 5,

  /**
   * KEY_TYPE_INT32 is a 32-bit signed integer.
   *
   * @generated from enum value: KEY_TYPE_INT32 = 6;
   */
  INT32 = 6,

  /**
   * KEY_TYPE_BOOLEAN is a Boolean.
   *
   * @generated from enum value: KEY_TYPE_BOOLEAN = 7;
   */
  BOOLEAN = 7,

  /**
   * KEY_TYPE_INT16 is a 16-bit signed integer.
   *
   * @generated from enum value: KEY_TYPE_INT16 = 8;
   */
  INT16 = 8,

  /**
   * KEY_TYPE_CHARACTER is a single byte character.
   *
   * @generated from enum value: KEY_TYPE_CHARACTER = 9;
   */
  CHARACTER = 9,

  /**
   * KEY_TYPE_COLOR32 is an RGBA color of four bytes.
   *
   * @generated from enum value: KEY_TYPE_COLOR32 = 10;
   */
  COLOR32 = 10,

  /**
   * KEY_TYPE_EMBEDDED is a field with its own data map.
   *
   * @generated from enum value: KEY_TYPE_EMBEDDED = 11;
   */
  EMBEDDED = 11,

  /**
   * KEY_TYPE_EHANDLE is an entity handle.
   *
   * @generated from enum value: KEY_TYPE_EHANDLE = 12;
   */
  EHANDLE = 12,

  /**
   * KEY_TYPE_POSITION_VECTOR is a world position.
   *
   * @generated from enum value: KEY_TYPE_POSITION_VECTOR = 13;
   */
  POSITION_VECTOR = 13,

  /**
   * KEY_TYPE_TIME is a game time in seconds.
   *
   * @generated from enum value: KEY_TYPE_TIME = 14;
   */
  TIME = 14,

  /**
   * KEY_TYPE_TICK is a game tick.
   *
   * @generated from enum value: KEY_TYPE_TICK = 15;
   */
  TICK = 15,

  /**
   * KEY_TYPE_SOUNDNAME is a sound event name.
   *
   * @generated from enum value: KEY_TYPE_SOUNDNAME = 16;
   */
  SOUNDNAME = 16,

  /**
   * KEY_TYPE_VECTOR2D is a two-float vector.
   *
   * @generated from enum value: KEY_TYPE_VECTOR2D = 17;
   */
  VECTOR2D = 17,

  /**
   * KEY_TYPE_INT64 is a 64-bit signed integer.
   *
   * @generated from enum value: KEY_TYPE_INT64 = 18;
   */
  INT64 = 18,

  /**
   * KEY_TYPE_VECTOR4D is a four-float vector.
   *
   * @generated from enum value: KEY_TYPE_VECTOR4D = 19;
   */
  VECTOR4D = 19,

  /**
   * KEY_TYPE_UINT64 is a 64-bit unsigned integer.
   *
   * @generated from enum value: KEY_TYPE_UINT64 = 20;
   */
  UINT64 = 20,

  /**
   * KEY_TYPE_UINT32 is a 32-bit unsigned integer.
   *
   * @generated from enum value: KEY_TYPE_UINT32 = 21;
   */
  UINT32 = 21,

  /**
   * KEY_TYPE_UTLSTRINGTOKEN is a hashed string token.
   *
   * @generated from enum value: KEY_TYPE_UTLSTRINGTOKEN = 22;
   */
  UTLSTRINGTOKEN = 22,

  /**
   * KEY_TYPE_QANGLE is a pitch, yaw and roll angle.
   *
   * @generated from enum value: KEY_TYPE_QANGLE = 23;
   */
  QANGLE = 23,

  /**
   * KEY_TYPE_NETWORK_ORIGIN_CELL_QUANTIZED_VECTOR is a position networked as a cell and an offset.
   *
   * @generated from enum value: KEY_TYPE_NETWORK_ORIGIN_CELL_QUANTIZED_VECTOR = 24;
   */
  NETWORK_ORIGIN_CELL_QUANTIZED_VECTOR = 24,

  /**
   * KEY_TYPE_HMATERIAL is a material resource handle.
   *
   * @generated from enum value: KEY_TYPE_HMATERIAL = 25;
   */
  HMATERIAL = 25,

  /**
   * KEY_TYPE_HMODEL is a model resource handle.
   *
   * @generated from enum value: KEY_TYPE_HMODEL = 26;
   */
  HMODEL = 26,

  /**
   * KEY_TYPE_NETWORK_QUANTIZED_VECTOR is a vector networked in quantized form.
   *
   * @generated from enum value: KEY_TYPE_NETWORK_QUANTIZED_VECTOR = 27;
   */
  NETWORK_QUANTIZED_VECTOR = 27,

  /**
   * KEY_TYPE_NETWORK_QUANTIZED_FLOAT is a float networked in quantized form.
   *
   * @generated from enum value: KEY_TYPE_NETWORK_QUANTIZED_FLOAT = 28;
   */
  NETWORK_QUANTIZED_FLOAT = 28,

  /**
   * KEY_TYPE_DIRECTION_VECTOR_WORLDSPACE is a direction in world space.
   *
   * @generated from enum value: KEY_TYPE_DIRECTION_VECTOR_WORLDSPACE = 29;
   */
  DIRECTION_VECTOR_WORLDSPACE = 29,

  /**
   * KEY_TYPE_QANGLE_WORLDSPACE is an angle in world space.
   *
   * @generated from enum value: KEY_TYPE_QANGLE_WORLDSPACE = 30;
   */
  QANGLE_WORLDSPACE = 30,

  /**
   * KEY_TYPE_QUATERNION_WORLDSPACE is a quaternion in world space.
   *
   * @generated from enum value: KEY_TYPE_QUATERNION_WORLDSPACE = 31;
   */
  QUATERNION_WORLDSPACE = 31,

  /**
   * KEY_TYPE_UTLSTRING is an owned string.
   *
   * @generated from enum value: KEY_TYPE_UTLSTRING = 32;
   */
  UTLSTRING = 32,

  /**
   * KEY_TYPE_HRENDERTEXTURE is a render texture resource handle.
   *
   * @generated from enum value: KEY_TYPE_HRENDERTEXTURE = 33;
   */
  HRENDERTEXTURE = 33,

  /**
   * KEY_TYPE_HPARTICLESYSTEMDEFINITION is a particle system resource handle.
   *
   * @generated from enum value: KEY_TYPE_HPARTICLESYSTEMDEFINITION = 34;
   */
  HPARTICLESYSTEMDEFINITION = 34,

  /**
   * KEY_TYPE_UINT8 is an 8-bit unsigned integer.
   *
   * @generated from enum value: KEY_TYPE_UINT8 = 35;
   */
  UINT8 = 35,

  /**
   * KEY_TYPE_UINT16 is a 16-bit unsigned integer.
   *
   * @generated from enum value: KEY_TYPE_UINT16 = 36;
   */
  UINT16 = 36,

  /**
   * KEY_TYPE_HPOSTPROCESSING is a post-processing resource handle.
   *
   * @generated from enum value: KEY_TYPE_HPOSTPROCESSING = 37;
   */
  HPOSTPROCESSING = 37,

  /**
   * KEY_TYPE_AMMO_INDEX is an ammunition type index.
   *
   * @generated from enum value: KEY_TYPE_AMMO_INDEX = 38;
   */
  AMMO_INDEX = 38,

  /**
   * KEY_TYPE_MODIFIER_HANDLE is a modifier handle.
   *
   * @generated from enum value: KEY_TYPE_MODIFIER_HANDLE = 39;
   */
  MODIFIER_HANDLE = 39,

  /**
   * KEY_TYPE_HVDATA is a VData record handle.
   *
   * @generated from enum value: KEY_TYPE_HVDATA = 40;
   */
  HVDATA = 40,

  /**
   * KEY_TYPE_GLOBALSYMBOL is a global symbol string.
   *
   * @generated from enum value: KEY_TYPE_GLOBALSYMBOL = 41;
   */
  GLOBALSYMBOL = 41,

  /**
   * KEY_TYPE_NETWORK_QUANTIZED_VECTORWS is a world space vector networked in quantized form.
   *
   * @generated from enum value: KEY_TYPE_NETWORK_QUANTIZED_VECTORWS = 42;
   */
  NETWORK_QUANTIZED_VECTORWS = 42,

  /**
   * KEY_TYPE_NETWORK_ORIGIN_CELL_QUANTIZED_VECTORWS is a world space position networked as a cell and an offset.
   *
   * @generated from enum value: KEY_TYPE_NETWORK_ORIGIN_CELL_QUANTIZED_VECTORWS = 43;
   */
  NETWORK_ORIGIN_CELL_QUANTIZED_VECTORWS = 43,
}

export const KeyType_Enum = /* @__PURE__ */ createEnumType("modlock.dump.KeyType", [
  [0, "KEY_TYPE_UNKNOWN"],
  [1, "KEY_TYPE_VOID"],
  [2, "KEY_TYPE_FLOAT32"],
  [3, "KEY_TYPE_STRING"],
  [4, "KEY_TYPE_VECTOR"],
  [5, "KEY_TYPE_QUATERNION"],
  [6, "KEY_TYPE_INT32"],
  [7, "KEY_TYPE_BOOLEAN"],
  [8, "KEY_TYPE_INT16"],
  [9, "KEY_TYPE_CHARACTER"],
  [10, "KEY_TYPE_COLOR32"],
  [11, "KEY_TYPE_EMBEDDED"],
  [12, "KEY_TYPE_EHANDLE"],
  [13, "KEY_TYPE_POSITION_VECTOR"],
  [14, "KEY_TYPE_TIME"],
  [15, "KEY_TYPE_TICK"],
  [16, "KEY_TYPE_SOUNDNAME"],
  [17, "KEY_TYPE_VECTOR2D"],
  [18, "KEY_TYPE_INT64"],
  [19, "KEY_TYPE_VECTOR4D"],
  [20, "KEY_TYPE_UINT64"],
  [21, "KEY_TYPE_UINT32"],
  [22, "KEY_TYPE_UTLSTRINGTOKEN"],
  [23, "KEY_TYPE_QANGLE"],
  [24, "KEY_TYPE_NETWORK_ORIGIN_CELL_QUANTIZED_VECTOR"],
  [25, "KEY_TYPE_HMATERIAL"],
  [26, "KEY_TYPE_HMODEL"],
  [27, "KEY_TYPE_NETWORK_QUANTIZED_VECTOR"],
  [28, "KEY_TYPE_NETWORK_QUANTIZED_FLOAT"],
  [29, "KEY_TYPE_DIRECTION_VECTOR_WORLDSPACE"],
  [30, "KEY_TYPE_QANGLE_WORLDSPACE"],
  [31, "KEY_TYPE_QUATERNION_WORLDSPACE"],
  [32, "KEY_TYPE_UTLSTRING"],
  [33, "KEY_TYPE_HRENDERTEXTURE"],
  [34, "KEY_TYPE_HPARTICLESYSTEMDEFINITION"],
  [35, "KEY_TYPE_UINT8"],
  [36, "KEY_TYPE_UINT16"],
  [37, "KEY_TYPE_HPOSTPROCESSING"],
  [38, "KEY_TYPE_AMMO_INDEX"],
  [39, "KEY_TYPE_MODIFIER_HANDLE"],
  [40, "KEY_TYPE_HVDATA"],
  [41, "KEY_TYPE_GLOBALSYMBOL"],
  [42, "KEY_TYPE_NETWORK_QUANTIZED_VECTORWS"],
  [43, "KEY_TYPE_NETWORK_ORIGIN_CELL_QUANTIZED_VECTORWS"],
]);

/**
 * ConstructionStatus is what creating an entity did.
 *
 * @generated from enum modlock.dump.ConstructionStatus
 */
export enum ConstructionStatus {
  /**
   * CONSTRUCTION_STATUS_UNSPECIFIED is not surveyed.
   *
   * @generated from enum value: CONSTRUCTION_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * CONSTRUCTION_STATUS_ALIVE spawned an entity that lived two frames later.
   *
   * @generated from enum value: CONSTRUCTION_STATUS_ALIVE = 1;
   */
  ALIVE = 1,

  /**
   * CONSTRUCTION_STATUS_VANISHED spawned an entity that was gone two frames
   * later.
   *
   * @generated from enum value: CONSTRUCTION_STATUS_VANISHED = 2;
   */
  VANISHED = 2,

  /**
   * CONSTRUCTION_STATUS_FAILED was refused with an error.
   *
   * @generated from enum value: CONSTRUCTION_STATUS_FAILED = 3;
   */
  FAILED = 3,

  /**
   * CONSTRUCTION_STATUS_CRASHED crashed the server.
   *
   * @generated from enum value: CONSTRUCTION_STATUS_CRASHED = 4;
   */
  CRASHED = 4,
}

export const ConstructionStatus_Enum = /* @__PURE__ */ createEnumType("modlock.dump.ConstructionStatus", [
  [0, "CONSTRUCTION_STATUS_UNSPECIFIED"],
  [1, "CONSTRUCTION_STATUS_ALIVE"],
  [2, "CONSTRUCTION_STATUS_VANISHED"],
  [3, "CONSTRUCTION_STATUS_FAILED"],
  [4, "CONSTRUCTION_STATUS_CRASHED"],
]);

/**
 * ConsoleVariableType is a console variable's value type. Each known value is
 * the game's own type plus one.
 *
 * @generated from enum modlock.dump.ConsoleVariableType
 */
export enum ConsoleVariableType {
  /**
   * CONSOLE_VARIABLE_TYPE_UNKNOWN is a value the dump does not know.
   *
   * @generated from enum value: CONSOLE_VARIABLE_TYPE_UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * CONSOLE_VARIABLE_TYPE_BOOL is a Boolean.
   *
   * @generated from enum value: CONSOLE_VARIABLE_TYPE_BOOL = 1;
   */
  BOOL = 1,

  /**
   * CONSOLE_VARIABLE_TYPE_INT16 is a 16-bit signed integer.
   *
   * @generated from enum value: CONSOLE_VARIABLE_TYPE_INT16 = 2;
   */
  INT16 = 2,

  /**
   * CONSOLE_VARIABLE_TYPE_UINT16 is a 16-bit unsigned integer.
   *
   * @generated from enum value: CONSOLE_VARIABLE_TYPE_UINT16 = 3;
   */
  UINT16 = 3,

  /**
   * CONSOLE_VARIABLE_TYPE_INT32 is a 32-bit signed integer.
   *
   * @generated from enum value: CONSOLE_VARIABLE_TYPE_INT32 = 4;
   */
  INT32 = 4,

  /**
   * CONSOLE_VARIABLE_TYPE_UINT32 is a 32-bit unsigned integer.
   *
   * @generated from enum value: CONSOLE_VARIABLE_TYPE_UINT32 = 5;
   */
  UINT32 = 5,

  /**
   * CONSOLE_VARIABLE_TYPE_INT64 is a 64-bit signed integer.
   *
   * @generated from enum value: CONSOLE_VARIABLE_TYPE_INT64 = 6;
   */
  INT64 = 6,

  /**
   * CONSOLE_VARIABLE_TYPE_UINT64 is a 64-bit unsigned integer.
   *
   * @generated from enum value: CONSOLE_VARIABLE_TYPE_UINT64 = 7;
   */
  UINT64 = 7,

  /**
   * CONSOLE_VARIABLE_TYPE_FLOAT32 is a 32-bit float.
   *
   * @generated from enum value: CONSOLE_VARIABLE_TYPE_FLOAT32 = 8;
   */
  FLOAT32 = 8,

  /**
   * CONSOLE_VARIABLE_TYPE_FLOAT64 is a 64-bit float.
   *
   * @generated from enum value: CONSOLE_VARIABLE_TYPE_FLOAT64 = 9;
   */
  FLOAT64 = 9,

  /**
   * CONSOLE_VARIABLE_TYPE_STRING is a string.
   *
   * @generated from enum value: CONSOLE_VARIABLE_TYPE_STRING = 10;
   */
  STRING = 10,

  /**
   * CONSOLE_VARIABLE_TYPE_COLOR is an RGBA color of four bytes.
   *
   * @generated from enum value: CONSOLE_VARIABLE_TYPE_COLOR = 11;
   */
  COLOR = 11,

  /**
   * CONSOLE_VARIABLE_TYPE_VECTOR2 is a two-float vector.
   *
   * @generated from enum value: CONSOLE_VARIABLE_TYPE_VECTOR2 = 12;
   */
  VECTOR2 = 12,

  /**
   * CONSOLE_VARIABLE_TYPE_VECTOR3 is a three-float vector.
   *
   * @generated from enum value: CONSOLE_VARIABLE_TYPE_VECTOR3 = 13;
   */
  VECTOR3 = 13,

  /**
   * CONSOLE_VARIABLE_TYPE_VECTOR4 is a four-float vector.
   *
   * @generated from enum value: CONSOLE_VARIABLE_TYPE_VECTOR4 = 14;
   */
  VECTOR4 = 14,

  /**
   * CONSOLE_VARIABLE_TYPE_QANGLE is a pitch, yaw and roll angle.
   *
   * @generated from enum value: CONSOLE_VARIABLE_TYPE_QANGLE = 15;
   */
  QANGLE = 15,

  /**
   * CONSOLE_VARIABLE_TYPE_VECTOR_WS is a three-float vector in world space.
   *
   * @generated from enum value: CONSOLE_VARIABLE_TYPE_VECTOR_WS = 16;
   */
  VECTOR_WS = 16,
}

export const ConsoleVariableType_Enum = /* @__PURE__ */ createEnumType("modlock.dump.ConsoleVariableType", [
  [0, "CONSOLE_VARIABLE_TYPE_UNKNOWN"],
  [1, "CONSOLE_VARIABLE_TYPE_BOOL"],
  [2, "CONSOLE_VARIABLE_TYPE_INT16"],
  [3, "CONSOLE_VARIABLE_TYPE_UINT16"],
  [4, "CONSOLE_VARIABLE_TYPE_INT32"],
  [5, "CONSOLE_VARIABLE_TYPE_UINT32"],
  [6, "CONSOLE_VARIABLE_TYPE_INT64"],
  [7, "CONSOLE_VARIABLE_TYPE_UINT64"],
  [8, "CONSOLE_VARIABLE_TYPE_FLOAT32"],
  [9, "CONSOLE_VARIABLE_TYPE_FLOAT64"],
  [10, "CONSOLE_VARIABLE_TYPE_STRING"],
  [11, "CONSOLE_VARIABLE_TYPE_COLOR"],
  [12, "CONSOLE_VARIABLE_TYPE_VECTOR2"],
  [13, "CONSOLE_VARIABLE_TYPE_VECTOR3"],
  [14, "CONSOLE_VARIABLE_TYPE_VECTOR4"],
  [15, "CONSOLE_VARIABLE_TYPE_QANGLE"],
  [16, "CONSOLE_VARIABLE_TYPE_VECTOR_WS"],
]);

/**
 * SchemaBase is one base class of a schema class.
 *
 * @generated from message modlock.dump.SchemaBase
 */
export interface SchemaBase {
  /**
   * Name is the base class's schema name.
   *
   * @generated from field: string name = 1;
   */
  name?: string;
  /**
   * Module is the base class's declaring project.
   *
   * @generated from field: string module = 2;
   */
  module?: string;
  /**
   * Offset is where the base's fields start in the derived class.
   *
   * @generated from field: uint32 offset = 3;
   */
  offset?: number;

};

export const SchemaBase: MessageType<SchemaBase> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.dump.SchemaBase",
    fields: [
        { no: 1, name: "name", kind: "scalar", T: ScalarType.STRING },
        { no: 2, name: "module", kind: "scalar", T: ScalarType.STRING },
        { no: 3, name: "offset", kind: "scalar", T: ScalarType.UINT32 },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * SchemaField is one field a schema class declares.
 *
 * @generated from message modlock.dump.SchemaField
 */
export interface SchemaField {
  /**
   * Name is the field's name, such as m_iHealth.
   *
   * @generated from field: string name = 1;
   */
  name?: string;
  /**
   * Type is the field's C++ type as the schema spells it, such as int32.
   *
   * @generated from field: string type = 2;
   */
  type?: string;
  /**
   * Offset is the field's byte offset in its class.
   *
   * @generated from field: uint32 offset = 3;
   */
  offset?: number;
  /**
   * Metadata names the field's metadata entries, such as MNetworkEnable.
   *
   * @generated from field: repeated string metadata = 4;
   */
  metadata?: string[];

};

export const SchemaField: MessageType<SchemaField> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.dump.SchemaField",
    fields: [
        { no: 1, name: "name", kind: "scalar", T: ScalarType.STRING },
        { no: 2, name: "type", kind: "scalar", T: ScalarType.STRING },
        { no: 3, name: "offset", kind: "scalar", T: ScalarType.UINT32 },
        { no: 4, name: "metadata", kind: "scalar", T: ScalarType.STRING, repeated: true },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * SchemaClass is one declared class.
 *
 * @generated from message modlock.dump.SchemaClass
 */
export interface SchemaClass {
  /**
   * Name is the class's schema name, such as CCitadelPlayerPawn.
   *
   * @generated from field: string name = 1;
   */
  name?: string;
  /**
   * Module is the declaring project, such as server.
   *
   * @generated from field: string module = 2;
   */
  module?: string;
  /**
   * Size is the native allocation size in bytes.
   *
   * @generated from field: uint32 size = 3;
   */
  size?: number;
  /**
   * Alignment is the native alignment in bytes.
   *
   * @generated from field: uint32 alignment = 4;
   */
  alignment?: number;
  /**
   * Bases are the direct base classes in declaration order.
   *
   * @generated from field: repeated modlock.dump.SchemaBase bases = 5;
   */
  bases?: SchemaBase[];
  /**
   * Fields are the class's own fields in declaration order.
   *
   * @generated from field: repeated modlock.dump.SchemaField fields = 6;
   */
  fields?: SchemaField[];
  /**
   * Metadata names the class's metadata entries, such as MNetworkVarNames.
   *
   * @generated from field: repeated string metadata = 7;
   */
  metadata?: string[];
  /**
   * Flags names the class's set flags, such as abstract.
   *
   * @generated from field: repeated string flags = 8;
   */
  flags?: string[];

};

export const SchemaClass: MessageType<SchemaClass> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.dump.SchemaClass",
    fields: [
        { no: 1, name: "name", kind: "scalar", T: ScalarType.STRING },
        { no: 2, name: "module", kind: "scalar", T: ScalarType.STRING },
        { no: 3, name: "size", kind: "scalar", T: ScalarType.UINT32 },
        { no: 4, name: "alignment", kind: "scalar", T: ScalarType.UINT32 },
        { no: 5, name: "bases", kind: "message", T: () => SchemaBase, repeated: true },
        { no: 6, name: "fields", kind: "message", T: () => SchemaField, repeated: true },
        { no: 7, name: "metadata", kind: "scalar", T: ScalarType.STRING, repeated: true },
        { no: 8, name: "flags", kind: "scalar", T: ScalarType.STRING, repeated: true },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * SchemaEnumerator is one named value of an enum.
 *
 * @generated from message modlock.dump.SchemaEnumerator
 */
export interface SchemaEnumerator {
  /**
   * Name is the enumerator's name.
   *
   * @generated from field: string name = 1;
   */
  name?: string;
  /**
   * Value is the enumerator's value.
   *
   * @generated from field: int64 value = 2;
   */
  value?: bigint;

};

export const SchemaEnumerator: MessageType<SchemaEnumerator> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.dump.SchemaEnumerator",
    fields: [
        { no: 1, name: "name", kind: "scalar", T: ScalarType.STRING },
        { no: 2, name: "value", kind: "scalar", T: ScalarType.INT64 },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * SchemaEnum is one declared enum.
 *
 * @generated from message modlock.dump.SchemaEnum
 */
export interface SchemaEnum {
  /**
   * Name is the enum's schema name.
   *
   * @generated from field: string name = 1;
   */
  name?: string;
  /**
   * Module is the declaring project.
   *
   * @generated from field: string module = 2;
   */
  module?: string;
  /**
   * Size is the enum's storage size in bytes.
   *
   * @generated from field: uint32 size = 3;
   */
  size?: number;
  /**
   * Enumerators are in declaration order.
   *
   * @generated from field: repeated modlock.dump.SchemaEnumerator enumerators = 4;
   */
  enumerators?: SchemaEnumerator[];
  /**
   * Metadata names the enum's metadata entries.
   *
   * @generated from field: repeated string metadata = 5;
   */
  metadata?: string[];

};

export const SchemaEnum: MessageType<SchemaEnum> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.dump.SchemaEnum",
    fields: [
        { no: 1, name: "name", kind: "scalar", T: ScalarType.STRING },
        { no: 2, name: "module", kind: "scalar", T: ScalarType.STRING },
        { no: 3, name: "size", kind: "scalar", T: ScalarType.UINT32 },
        { no: 4, name: "enumerators", kind: "message", T: () => SchemaEnumerator, repeated: true },
        { no: 5, name: "metadata", kind: "scalar", T: ScalarType.STRING, repeated: true },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * Schemas lists the schema classes and enums of every loaded game module.
 *
 * @generated from message modlock.dump.Schemas
 */
export interface Schemas {
  /**
   * Build is the game's ClientVersion from steam.inf.
   *
   * @generated from field: string build = 1;
   */
  build?: string;
  /**
   * Classes are sorted by module, then name.
   *
   * @generated from field: repeated modlock.dump.SchemaClass classes = 2;
   */
  classes?: SchemaClass[];
  /**
   * Enums are sorted by module, then name.
   *
   * @generated from field: repeated modlock.dump.SchemaEnum enums = 3;
   */
  enums?: SchemaEnum[];

};

export const Schemas: MessageType<Schemas> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.dump.Schemas",
    fields: [
        { no: 1, name: "build", kind: "scalar", T: ScalarType.STRING },
        { no: 2, name: "classes", kind: "message", T: () => SchemaClass, repeated: true },
        { no: 3, name: "enums", kind: "message", T: () => SchemaEnum, repeated: true },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * EntityClass is one designer name the server can create.
 *
 * @generated from message modlock.dump.EntityClass
 */
export interface EntityClass {
  /**
   * DesignerName is the name a map or CreateEntity uses, such as
   * npc_trooper_boss.
   *
   * @generated from field: string designer_name = 1;
   */
  designerName?: string;
  /**
   * ClassName is the schema class that implements it.
   *
   * @generated from field: string class_name = 2;
   */
  className?: string;
  /**
   * Description is the class's own description, when it has one.
   *
   * @generated from field: string description = 3;
   */
  description?: string;
  /**
   * DataMap names the class's data description in data_maps.
   *
   * @generated from field: string data_map = 4;
   */
  dataMap?: string;
  /**
   * Base is the designer name of the nearest entity class this one derives
   * from. A class also has its base's key values, inputs and outputs.
   *
   * @generated from field: string base = 5;
   */
  base?: string;

};

export const EntityClass: MessageType<EntityClass> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.dump.EntityClass",
    fields: [
        { no: 1, name: "designer_name", kind: "scalar", T: ScalarType.STRING },
        { no: 2, name: "class_name", kind: "scalar", T: ScalarType.STRING },
        { no: 3, name: "description", kind: "scalar", T: ScalarType.STRING },
        { no: 4, name: "data_map", kind: "scalar", T: ScalarType.STRING },
        { no: 5, name: "base", kind: "scalar", T: ScalarType.STRING },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * KeyValue is one spawn key value and the field it sets.
 *
 * @generated from message modlock.dump.KeyValue
 */
export interface KeyValue {
  /**
   * Name is the key, such as targetname.
   *
   * @generated from field: string name = 1;
   */
  name?: string;
  /**
   * Field is the class field the key sets, such as m_iszName.
   *
   * @generated from field: string field = 2;
   */
  field?: string;
  /**
   * Type is the value's type.
   *
   * @generated from field: modlock.dump.KeyType type = 3;
   */
  type?: KeyType;
  /**
   * Count is the number of array elements, or 1.
   *
   * @generated from field: uint32 count = 4;
   */
  count?: number;

};

export const KeyValue: MessageType<KeyValue> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.dump.KeyValue",
    fields: [
        { no: 1, name: "name", kind: "scalar", T: ScalarType.STRING },
        { no: 2, name: "field", kind: "scalar", T: ScalarType.STRING },
        { no: 3, name: "type", kind: "enum", T: KeyType_Enum },
        { no: 4, name: "count", kind: "scalar", T: ScalarType.UINT32 },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * EmbeddedMap is a field whose own data map contributes key values.
 *
 * @generated from message modlock.dump.EmbeddedMap
 */
export interface EmbeddedMap {
  /**
   * Field is the embedding field's name.
   *
   * @generated from field: string field = 1;
   */
  field?: string;
  /**
   * DataMap names the field's data map in data_maps.
   *
   * @generated from field: string data_map = 2;
   */
  dataMap?: string;

};

export const EmbeddedMap: MessageType<EmbeddedMap> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.dump.EmbeddedMap",
    fields: [
        { no: 1, name: "field", kind: "scalar", T: ScalarType.STRING },
        { no: 2, name: "data_map", kind: "scalar", T: ScalarType.STRING },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * DataMap is one class's data description. A class's complete set is its own
 * map followed by each base map.
 *
 * @generated from message modlock.dump.DataMap
 */
export interface DataMap {
  /**
   * Name is the data description's class name.
   *
   * @generated from field: string name = 1;
   */
  name?: string;
  /**
   * Base names the base class's data map, if any.
   *
   * @generated from field: string base = 2;
   */
  base?: string;
  /**
   * KeyValues are the spawn key values this map adds.
   *
   * @generated from field: repeated modlock.dump.KeyValue key_values = 3;
   */
  keyValues?: KeyValue[];
  /**
   * Embedded are the fields whose own data maps add key values.
   *
   * @generated from field: repeated modlock.dump.EmbeddedMap embedded = 4;
   */
  embedded?: EmbeddedMap[];

};

export const DataMap: MessageType<DataMap> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.dump.DataMap",
    fields: [
        { no: 1, name: "name", kind: "scalar", T: ScalarType.STRING },
        { no: 2, name: "base", kind: "scalar", T: ScalarType.STRING },
        { no: 3, name: "key_values", kind: "message", T: () => KeyValue, repeated: true },
        { no: 4, name: "embedded", kind: "message", T: () => EmbeddedMap, repeated: true },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * Parameter is one value an input or output passes.
 *
 * @generated from message modlock.dump.Parameter
 */
export interface Parameter {
  /**
   * Name is the parameter's name.
   *
   * @generated from field: string name = 1;
   */
  name?: string;
  /**
   * Type is the parameter's Pulse type, such as PVAL_FLOAT32 or
   * PVAL_EHANDLE:npc_trooper.
   *
   * @generated from field: string type = 2;
   */
  type?: string;

};

export const Parameter: MessageType<Parameter> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.dump.Parameter",
    fields: [
        { no: 1, name: "name", kind: "scalar", T: ScalarType.STRING },
        { no: 2, name: "type", kind: "scalar", T: ScalarType.STRING },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * Input is one input an entity accepts.
 *
 * @generated from message modlock.dump.Input
 */
export interface Input {
  /**
   * Entity is the designer name of the entity class that accepts the input,
   * and the classes derived from it accept it too. Empty means every entity.
   *
   * @generated from field: string entity = 1;
   */
  entity?: string;
  /**
   * Name is the input's name, such as Kill.
   *
   * @generated from field: string name = 2;
   */
  name?: string;
  /**
   * Description is the input's help text, when it has one.
   *
   * @generated from field: string description = 3;
   */
  description?: string;
  /**
   * Parameters are the values the input takes, sorted by name. An input
   * with more than one parameter can be called only from Pulse.
   *
   * @generated from field: repeated modlock.dump.Parameter parameters = 4;
   */
  parameters?: Parameter[];
  /**
   * Returns are the values the input returns to Pulse, sorted by name.
   *
   * @generated from field: repeated modlock.dump.Parameter returns = 5;
   */
  returns?: Parameter[];

};

export const Input: MessageType<Input> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.dump.Input",
    fields: [
        { no: 1, name: "entity", kind: "scalar", T: ScalarType.STRING },
        { no: 2, name: "name", kind: "scalar", T: ScalarType.STRING },
        { no: 3, name: "description", kind: "scalar", T: ScalarType.STRING },
        { no: 4, name: "parameters", kind: "message", T: () => Parameter, repeated: true },
        { no: 5, name: "returns", kind: "message", T: () => Parameter, repeated: true },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * Output is one output an entity fires.
 *
 * @generated from message modlock.dump.Output
 */
export interface Output {
  /**
   * Entity is the designer name of the entity class that fires the output,
   * and the classes derived from it fire it too. Empty means every entity.
   *
   * @generated from field: string entity = 1;
   */
  entity?: string;
  /**
   * Name is the output's name, such as OnDeath.
   *
   * @generated from field: string name = 2;
   */
  name?: string;
  /**
   * Description is the output's help text, when it has one.
   *
   * @generated from field: string description = 3;
   */
  description?: string;
  /**
   * Parameters are the values the output passes, sorted by name.
   *
   * @generated from field: repeated modlock.dump.Parameter parameters = 4;
   */
  parameters?: Parameter[];

};

export const Output: MessageType<Output> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.dump.Output",
    fields: [
        { no: 1, name: "entity", kind: "scalar", T: ScalarType.STRING },
        { no: 2, name: "name", kind: "scalar", T: ScalarType.STRING },
        { no: 3, name: "description", kind: "scalar", T: ScalarType.STRING },
        { no: 4, name: "parameters", kind: "message", T: () => Parameter, repeated: true },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * Entities lists the server's entity classes, the data descriptions that
 * define their key values, and the inputs and outputs the server binds to
 * Pulse.
 *
 * @generated from message modlock.dump.Entities
 */
export interface Entities {
  /**
   * Build is the game's ClientVersion from steam.inf.
   *
   * @generated from field: string build = 1;
   */
  build?: string;
  /**
   * Classes are sorted by designer name.
   *
   * @generated from field: repeated modlock.dump.EntityClass classes = 2;
   */
  classes?: EntityClass[];
  /**
   * DataMaps are sorted by name and include every base and embedded map the
   * classes reach.
   *
   * @generated from field: repeated modlock.dump.DataMap data_maps = 3;
   */
  dataMaps?: DataMap[];
  /**
   * Inputs are sorted by entity, then name.
   *
   * @generated from field: repeated modlock.dump.Input inputs = 4;
   */
  inputs?: Input[];
  /**
   * Outputs are sorted by entity, then name.
   *
   * @generated from field: repeated modlock.dump.Output outputs = 5;
   */
  outputs?: Output[];

};

export const Entities: MessageType<Entities> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.dump.Entities",
    fields: [
        { no: 1, name: "build", kind: "scalar", T: ScalarType.STRING },
        { no: 2, name: "classes", kind: "message", T: () => EntityClass, repeated: true },
        { no: 3, name: "data_maps", kind: "message", T: () => DataMap, repeated: true },
        { no: 4, name: "inputs", kind: "message", T: () => Input, repeated: true },
        { no: 5, name: "outputs", kind: "message", T: () => Output, repeated: true },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * Construction is what creating one designer name, with one subclass or none,
 * did.
 *
 * @generated from message modlock.dump.Construction
 */
export interface Construction {
  /**
   * DesignerName is the designer name created.
   *
   * @generated from field: string designer_name = 1;
   */
  designerName?: string;
  /**
   * Subclass names the game data entry the creation gave it, if any.
   *
   * @generated from field: string subclass = 2;
   */
  subclass?: string;
  /**
   * Status is what the creation did.
   *
   * @generated from field: modlock.dump.ConstructionStatus status = 3;
   */
  status?: ConstructionStatus;
  /**
   * Error is why the server refused the creation, when it did.
   *
   * @generated from field: string error = 4;
   */
  error?: string;

};

export const Construction: MessageType<Construction> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.dump.Construction",
    fields: [
        { no: 1, name: "designer_name", kind: "scalar", T: ScalarType.STRING },
        { no: 2, name: "subclass", kind: "scalar", T: ScalarType.STRING },
        { no: 3, name: "status", kind: "enum", T: ConstructionStatus_Enum },
        { no: 4, name: "error", kind: "scalar", T: ScalarType.STRING },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * Survey records what creating each designer name at a position, with no key
 * values, did on a running server: alone, and again with a game data subclass
 * when the game's data has one for it.
 *
 * @generated from message modlock.dump.Survey
 */
export interface Survey {
  /**
   * Build is the game's ClientVersion from steam.inf.
   *
   * @generated from field: string build = 1;
   */
  build?: string;
  /**
   * Constructions are sorted by designer name, then subclass.
   *
   * @generated from field: repeated modlock.dump.Construction constructions = 2;
   */
  constructions?: Construction[];

};

export const Survey: MessageType<Survey> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.dump.Survey",
    fields: [
        { no: 1, name: "build", kind: "scalar", T: ScalarType.STRING },
        { no: 2, name: "constructions", kind: "message", T: () => Construction, repeated: true },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * ConsoleVariable is one registered console variable.
 *
 * @generated from message modlock.dump.ConsoleVariable
 */
export interface ConsoleVariable {
  /**
   * Name is the variable's name, such as sv_cheats.
   *
   * @generated from field: string name = 1;
   */
  name?: string;
  /**
   * Type is the value's type.
   *
   * @generated from field: modlock.dump.ConsoleVariableType type = 2;
   */
  type?: ConsoleVariableType;
  /**
   * DefaultValue is the default as the console prints it, such as 800 or
   * [0, 0, 0].
   *
   * @generated from field: string default_value = 3;
   */
  defaultValue?: string;
  /**
   * Min is the lower bound, when the variable has one.
   *
   * @generated from field: string min = 4;
   */
  min?: string;
  /**
   * Max is the upper bound, when the variable has one.
   *
   * @generated from field: string max = 5;
   */
  max?: string;
  /**
   * Help is the variable's help text.
   *
   * @generated from field: string help = 6;
   */
  help?: string;
  /**
   * Flags names the set flags, such as cheat and replicated. A bit without a
   * known name appears as flag_<bit>.
   *
   * @generated from field: repeated string flags = 7;
   */
  flags?: string[];

};

export const ConsoleVariable: MessageType<ConsoleVariable> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.dump.ConsoleVariable",
    fields: [
        { no: 1, name: "name", kind: "scalar", T: ScalarType.STRING },
        { no: 2, name: "type", kind: "enum", T: ConsoleVariableType_Enum },
        { no: 3, name: "default_value", kind: "scalar", T: ScalarType.STRING },
        { no: 4, name: "min", kind: "scalar", T: ScalarType.STRING },
        { no: 5, name: "max", kind: "scalar", T: ScalarType.STRING },
        { no: 6, name: "help", kind: "scalar", T: ScalarType.STRING },
        { no: 7, name: "flags", kind: "scalar", T: ScalarType.STRING, repeated: true },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * ConsoleCommand is one registered console command.
 *
 * @generated from message modlock.dump.ConsoleCommand
 */
export interface ConsoleCommand {
  /**
   * Name is the command's name, such as changelevel.
   *
   * @generated from field: string name = 1;
   */
  name?: string;
  /**
   * Help is the command's help text.
   *
   * @generated from field: string help = 2;
   */
  help?: string;
  /**
   * Flags names the set flags, as for ConsoleVariable.
   *
   * @generated from field: repeated string flags = 3;
   */
  flags?: string[];

};

export const ConsoleCommand: MessageType<ConsoleCommand> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.dump.ConsoleCommand",
    fields: [
        { no: 1, name: "name", kind: "scalar", T: ScalarType.STRING },
        { no: 2, name: "help", kind: "scalar", T: ScalarType.STRING },
        { no: 3, name: "flags", kind: "scalar", T: ScalarType.STRING, repeated: true },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * Console lists the server's console variables and commands.
 *
 * @generated from message modlock.dump.Console
 */
export interface Console {
  /**
   * Build is the game's ClientVersion from steam.inf.
   *
   * @generated from field: string build = 1;
   */
  build?: string;
  /**
   * Variables are sorted by name.
   *
   * @generated from field: repeated modlock.dump.ConsoleVariable variables = 2;
   */
  variables?: ConsoleVariable[];
  /**
   * Commands are sorted by name.
   *
   * @generated from field: repeated modlock.dump.ConsoleCommand commands = 3;
   */
  commands?: ConsoleCommand[];

};

export const Console: MessageType<Console> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.dump.Console",
    fields: [
        { no: 1, name: "build", kind: "scalar", T: ScalarType.STRING },
        { no: 2, name: "variables", kind: "message", T: () => ConsoleVariable, repeated: true },
        { no: 3, name: "commands", kind: "message", T: () => ConsoleCommand, repeated: true },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

