// @generated by protoc-gen-es-lite unknown with parameter "target=ts,ts_nocheck=false"
// @generated from file github.com/paralin/modlock/proto/modlock/control/control.proto (package modlock.control, syntax proto3)
/* eslint-disable */

import { createEnumType } from "@aptre/protobuf-es-lite/enum";
import type { MessageType } from "@aptre/protobuf-es-lite/message";
import { createMessageType } from "@aptre/protobuf-es-lite/message";
import { ScalarType } from "@aptre/protobuf-es-lite/scalar";
import type { PartialFieldInfo } from "@aptre/protobuf-es-lite/field";
import { Change } from "../ui.pb.js";

export const protobufPackage = "modlock.control";

/**
 * MessageKind is where a message shows on the player's screen.
 *
 * @generated from enum modlock.control.MessageKind
 */
export enum MessageKind {
  /**
   * MESSAGE_KIND_CHAT is a line in chat.
   *
   * @generated from enum value: MESSAGE_KIND_CHAT = 0;
   */
  CHAT = 0,

  /**
   * MESSAGE_KIND_CENTER is the text in the center of the screen.
   *
   * @generated from enum value: MESSAGE_KIND_CENTER = 1;
   */
  CENTER = 1,

  /**
   * MESSAGE_KIND_ANNOUNCEMENT is a game announcement with a title.
   *
   * @generated from enum value: MESSAGE_KIND_ANNOUNCEMENT = 2;
   */
  ANNOUNCEMENT = 2,
}

export const MessageKind_Enum = /* @__PURE__ */ createEnumType("modlock.control.MessageKind", [
  [0, "MESSAGE_KIND_CHAT"],
  [1, "MESSAGE_KIND_CENTER"],
  [2, "MESSAGE_KIND_ANNOUNCEMENT"],
]);

/**
 * ReloadRequest replaces one mod in place. The mod keeps its place among the
 * host's plugins; its old instance stops and the new build starts.
 *
 * @generated from message modlock.control.ReloadRequest
 */
export interface ReloadRequest {
  /**
   * Path is the built mod to load: a directory with mod.json or a .wasm file,
   * as the host sees it.
   *
   * @generated from field: string path = 1;
   */
  path?: string;

};

export const ReloadRequest: MessageType<ReloadRequest> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.control.ReloadRequest",
    fields: [
        { no: 1, name: "path", kind: "scalar", T: ScalarType.STRING },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * ControlRequest is one request from the controller.
 *
 * @generated from message modlock.control.ControlRequest
 */
export interface ControlRequest {

  /**
   * Body selects the request.
   *
   * @generated from oneof modlock.control.ControlRequest.body
   */
  body?: {
    value?: undefined,
    case: undefined
  } | {
    /**
     * Reload replaces a running mod with a new build.
     *
     * @generated from field: modlock.control.ReloadRequest reload = 1;
     */
    value: ReloadRequest;
    case: "reload";
  };

};

export const ControlRequest: MessageType<ControlRequest> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.control.ControlRequest",
    fields: [
        { no: 1, name: "reload", kind: "message", T: () => ReloadRequest, oneof: "body" },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * ModStarted identifies a mod that started.
 *
 * @generated from message modlock.control.ModStarted
 */
export interface ModStarted {
  /**
   * Mod is the mod's name.
   *
   * @generated from field: string mod = 1;
   */
  mod?: string;
  /**
   * Reloaded is true when a reload replaced an earlier instance.
   *
   * @generated from field: bool reloaded = 2;
   */
  reloaded?: boolean;

};

export const ModStarted: MessageType<ModStarted> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.control.ModStarted",
    fields: [
        { no: 1, name: "mod", kind: "scalar", T: ScalarType.STRING },
        { no: 2, name: "reloaded", kind: "scalar", T: ScalarType.BOOL },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * ModLog carries one log line.
 *
 * @generated from message modlock.control.ModLog
 */
export interface ModLog {
  /**
   * Mod is the name of the mod that logged.
   *
   * @generated from field: string mod = 1;
   */
  mod?: string;
  /**
   * Text is the line, without a trailing newline.
   *
   * @generated from field: string text = 2;
   */
  text?: string;

};

export const ModLog: MessageType<ModLog> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.control.ModLog",
    fields: [
        { no: 1, name: "mod", kind: "scalar", T: ScalarType.STRING },
        { no: 2, name: "text", kind: "scalar", T: ScalarType.STRING },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * ModFailed explains why a mod stopped or a reload failed. A failed reload
 * leaves the previous instance running.
 *
 * @generated from message modlock.control.ModFailed
 */
export interface ModFailed {
  /**
   * Mod is the mod's name.
   *
   * @generated from field: string mod = 1;
   */
  mod?: string;
  /**
   * Error describes the failure.
   *
   * @generated from field: string error = 2;
   */
  error?: string;

};

export const ModFailed: MessageType<ModFailed> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.control.ModFailed",
    fields: [
        { no: 1, name: "mod", kind: "scalar", T: ScalarType.STRING },
        { no: 2, name: "error", kind: "scalar", T: ScalarType.STRING },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * PlayerJoined identifies a player who joined.
 *
 * @generated from message modlock.control.PlayerJoined
 */
export interface PlayerJoined {
  /**
   * Slot is the player's slot.
   *
   * @generated from field: int32 slot = 1;
   */
  slot?: number;
  /**
   * Name is the player's name.
   *
   * @generated from field: string name = 2;
   */
  name?: string;
  /**
   * SteamId is the player's Steam ID, zero for a bot.
   *
   * @generated from field: fixed64 steam_id = 3;
   */
  steamId?: bigint;

};

export const PlayerJoined: MessageType<PlayerJoined> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.control.PlayerJoined",
    fields: [
        { no: 1, name: "slot", kind: "scalar", T: ScalarType.INT32 },
        { no: 2, name: "name", kind: "scalar", T: ScalarType.STRING },
        { no: 3, name: "steam_id", kind: "scalar", T: ScalarType.FIXED64 },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * ServerReady reports the loaded map.
 *
 * @generated from message modlock.control.ServerReady
 */
export interface ServerReady {
  /**
   * Map is the map the server loaded.
   *
   * @generated from field: string map = 1;
   */
  map?: string;

};

export const ServerReady: MessageType<ServerReady> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.control.ServerReady",
    fields: [
        { no: 1, name: "map", kind: "scalar", T: ScalarType.STRING },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * UiChanged carries a change to the interface a mod shows a player.
 *
 * @generated from message modlock.control.UiChanged
 */
export interface UiChanged {
  /**
   * Mod is the mod's name.
   *
   * @generated from field: string mod = 1;
   */
  mod?: string;
  /**
   * Slot identifies the player.
   *
   * @generated from field: int32 slot = 2;
   */
  slot?: number;
  /**
   * Change updates the player's tree for the mod.
   *
   * @generated from field: modlock.ui.Change change = 3;
   */
  change?: Change;

};

export const UiChanged: MessageType<UiChanged> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.control.UiChanged",
    fields: [
        { no: 1, name: "mod", kind: "scalar", T: ScalarType.STRING },
        { no: 2, name: "slot", kind: "scalar", T: ScalarType.INT32 },
        { no: 3, name: "change", kind: "message", T: () => Change },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * PlayerLeft identifies a player who left. Bots leave too; a controller drops
 * a slot it never saw join.
 *
 * @generated from message modlock.control.PlayerLeft
 */
export interface PlayerLeft {
  /**
   * Slot is the player's former slot.
   *
   * @generated from field: int32 slot = 1;
   */
  slot?: number;

};

export const PlayerLeft: MessageType<PlayerLeft> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.control.PlayerLeft",
    fields: [
        { no: 1, name: "slot", kind: "scalar", T: ScalarType.INT32 },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * PlayerMessage is a message a mod showed one player.
 *
 * @generated from message modlock.control.PlayerMessage
 */
export interface PlayerMessage {
  /**
   * Mod is the name of the mod that showed it.
   *
   * @generated from field: string mod = 1;
   */
  mod?: string;
  /**
   * Slot identifies the player.
   *
   * @generated from field: int32 slot = 2;
   */
  slot?: number;
  /**
   * Kind is where the message shows.
   *
   * @generated from field: modlock.control.MessageKind kind = 3;
   */
  kind?: MessageKind;
  /**
   * Title heads an announcement.
   *
   * @generated from field: string title = 4;
   */
  title?: string;
  /**
   * Text is the message; empty center text clears it.
   *
   * @generated from field: string text = 5;
   */
  text?: string;

};

export const PlayerMessage: MessageType<PlayerMessage> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.control.PlayerMessage",
    fields: [
        { no: 1, name: "mod", kind: "scalar", T: ScalarType.STRING },
        { no: 2, name: "slot", kind: "scalar", T: ScalarType.INT32 },
        { no: 3, name: "kind", kind: "enum", T: MessageKind_Enum },
        { no: 4, name: "title", kind: "scalar", T: ScalarType.STRING },
        { no: 5, name: "text", kind: "scalar", T: ScalarType.STRING },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

/**
 * HostEvent is one thing that happened in the host.
 *
 * @generated from message modlock.control.HostEvent
 */
export interface HostEvent {

  /**
   * Body selects the event.
   *
   * @generated from oneof modlock.control.HostEvent.body
   */
  body?: {
    value?: undefined,
    case: undefined
  } | {
    /**
     * Started reports a mod that started or restarted after a reload.
     *
     * @generated from field: modlock.control.ModStarted started = 1;
     */
    value: ModStarted;
    case: "started";
  } | {
    /**
     * Log carries one line a mod logged.
     *
     * @generated from field: modlock.control.ModLog log = 2;
     */
    value: ModLog;
    case: "log";
  } | {
    /**
     * Failed reports a mod that stopped or a reload that did not load.
     *
     * @generated from field: modlock.control.ModFailed failed = 3;
     */
    value: ModFailed;
    case: "failed";
  } | {
    /**
     * Joined reports a player who finished joining the server.
     *
     * @generated from field: modlock.control.PlayerJoined joined = 4;
     */
    value: PlayerJoined;
    case: "joined";
  } | {
    /**
     * Ready reports that players can join the server.
     *
     * @generated from field: modlock.control.ServerReady ready = 5;
     */
    value: ServerReady;
    case: "ready";
  } | {
    /**
     * Ui carries a change to the interface a mod shows a player. The host
     * sends every tree as a reset change when the call opens.
     *
     * @generated from field: modlock.control.UiChanged ui = 6;
     */
    value: UiChanged;
    case: "ui";
  } | {
    /**
     * Left reports a player who left the server.
     *
     * @generated from field: modlock.control.PlayerLeft left = 7;
     */
    value: PlayerLeft;
    case: "left";
  } | {
    /**
     * Message carries a message a mod showed a player: a chat line, center
     * text or an announcement.
     *
     * @generated from field: modlock.control.PlayerMessage message = 8;
     */
    value: PlayerMessage;
    case: "message";
  };

};

export const HostEvent: MessageType<HostEvent> = /* @__PURE__ */ createMessageType({
    typeName: "modlock.control.HostEvent",
    fields: [
        { no: 1, name: "started", kind: "message", T: () => ModStarted, oneof: "body" },
        { no: 2, name: "log", kind: "message", T: () => ModLog, oneof: "body" },
        { no: 3, name: "failed", kind: "message", T: () => ModFailed, oneof: "body" },
        { no: 4, name: "joined", kind: "message", T: () => PlayerJoined, oneof: "body" },
        { no: 5, name: "ready", kind: "message", T: () => ServerReady, oneof: "body" },
        { no: 6, name: "ui", kind: "message", T: () => UiChanged, oneof: "body" },
        { no: 7, name: "left", kind: "message", T: () => PlayerLeft, oneof: "body" },
        { no: 8, name: "message", kind: "message", T: () => PlayerMessage, oneof: "body" },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
});

